### ISSUE TITLE
Firing up govCMS on SimplyTest.me delivers vanilla D7

### ISSUE THREAD

**Issue by kattekrab** [govCMS/GovCMS7#1]
( replicating from https://www.drupal.org/node/2532610 )

Fantastic to see govCMS now on drupal.org. Kudos to all on this significant milestone.

I just fired it up on simplytest.me though and it's delivering a vanilla drupal 7 install rather than govCMS.

http://SimplyTest.me is a great, zero barrier way of evaluating drupal projects. Many people would find it helpful to review the distro if they could take it for a spin this way.

**Comment by seanhamlin** [comment]
From https://simplytest.me/qa

```
How are distributions build?
Simplytest.me chooses a makefile to build a distribution in the following order:
• simplytest.make: Should be similar to a build-[distro].make file, build the complete site and download all dependencies.
• build-[distro].make: Should build the complete site and download all dependencies.
• No makefile: Current Drupal core is downloaded, dependencies will be resolved as referenced in .info files.
```

So it seems we need a make file I am guessing?

**Comment by seanhamlin** [comment]
Yeap, there even is a TODO in the code ;) https://github.com/govCMS/govCMS/blob/master/build-govcms.make#L12

**Comment by kattekrab** [comment]
\o/
Via mobile.

**Comment by kattekrab** [comment]
This isn't actually fixed as far as I can tell.

**Comment by seanhamlin** [comment]
Yeah, we need to push the codebase to d.o. There is some magic in TravisCI that is supposed to do this. I will raise another issue for that.

**Comment by seanhamlin** [comment]
Raised #23

**Comment by typhonius** [comment]
The issue that fixes this is #24. As soon as that's pushed we should _hopefully_ restart our automated deployments :8ball:

**Comment by seanhamlin** [comment]
@kattekrab with the new release of beta2, this is confirmed working now. Thanks!

**Comment by kattekrab** [comment]
Yep. Fired it up yesterday. Works a treat.  Thank you.

**Comment by wiifm69** [comment]
:grinning:
