### ISSUE TITLE
As an Administrator, I want to give the Site Builder role permission to manage modules, but have a blacklist of modules they can't disable

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#106]
We would like to allow Site Builders to enable/disable modules as required, however, some modules, such as Password Policy, should not be turned off.

Is there a way to implement a more granular approach to module management for Site Builders?

**Comment by aleayr** [comment]
Another ticket I've since discovered, lists module_whitelist as a potential solution to this problem.

That ticket was for Site Editors, this for Site Builders.
Thoughts?

**Comment by stooit** [comment]
`module_whitelist` is definitely a good solution here -- each time a new module is added to the distribution you'll want a process to evaluate and update the default whitelist rules.

**Comment by invisigoth** [comment]
module_whitelist is certainly a good solution. However this module by itself does not allow users to then grand permissions of whitelisted modules to other roles/users. For example, if a site builder is allowed to turn on and off Views UI module, they should also be allowed to control which other users should be allowed to access Views UI module. This probably require another custom module to work with module_whitelist to provide all the features we wanted.

**Comment by aleayr** [comment]
@invisigoth should have a prototype of this shortly.

**Comment by invisigoth** [comment]
A new solution has been developed: https://www.drupal.org/project/module_permissions and is now being tested by our tester (GOVCMS-576). We will create a pull request when it passes the tests.

The module permissions module allows site administrator to define a subset of modules and allow users of another role to manage those selected modules. Those users can turn on and off those modules as well as manage permissions for them. It also allows delegates to enable dependencies.

Future improvements will be to allow delegates to configure modules in the managed list.

**Comment by fiasco** [comment]
Feature is in but not enabled at present. Please contact Dept of Finance if you're interested in getting early access to this feature.
