### ISSUE TITLE
Add autocomplete functionality to Search API

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#109]
An site has stories requiring autocomplete functionality for the search feature. The Search API Autocomplete module would meet that requirement.

**Comment by fiasco** [comment]
Sounds fine and sounds like the sort of thing we should do out of the box?

**Comment by invisigoth** [comment]
The autocomplete function provided by Solr could may not function in the same way most user would expect as for example Google.

For example, www.australia.gov.au is using this function and Acquia search. If you search "does australia" it suggests:
- does australia
- does australia will
- does australia reports
- does australia resource
- does australia regional
- does australia public
- does australia releases
- does australia private
- does australia 2015
- does australia rise
- does australia section
- does australia while
- does australia privacy

Maybe we should consider offering a curated list of suggestions that can be easily controlled?

**Comment by invisigoth** [comment]
On australia.gov.au, autocomplete suggestions are managed as a type of content and can be seeded through a CSV feed. This also allows content managers to put suggestions in categories (try entering "visa" on http://www.australia.gov.au/). My understanding is this feature is not difficult to be migrated to GovCMS and it also works with database search.

**Comment by pandaskii** [comment]
Apache Solr 3.x "Suggester" ("autocomplete", also known as SuggestComponent) reuses much of the SpellCheckComponent infrastructure and based on [lucene suggest module](lucene suggest module).

This is why #138 and this discussion are on same page. IMO, spellcheck is a partial "Suggester"

"search autocomplete" on http://www.australia.gov.au/ is quite impressive, and we may take it into considerations.

**Comment by aleayr** [comment]
Given the issues with this functionality, I'm closing this issue.
