### ISSUE TITLE
Agency cannot turn comments on/off

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#114]
An agency advises that while they have comments turned on for their site they do not have the ability to turn them off globally.  This is in response to a suggestion they turn off comments for the upcoming fork release, "We don’t have access to the permissions tab. I assumed this was locked out for all environments"

When agencies have comments on they should be able to turn them off.  This could be due to scenarios as the above, or because the site is getting spammed/trolled in a fashion that comments are making it past spam filters.

Is there something that is needed to be done to facilitate agencies to self service for this functionality?

**Comment by fiasco** [comment]
Do we provide comment functionality? I thought that was not yet a supported capability for govCMS?

**Comment by aleayr** [comment]
Interesting. Might have to look into this one a bit more.

**Comment by rooby** [comment]
The comment module is definitely enabled on a fresh install 7.x-2.0-beta8

**Comment by pandaskii** [comment]
@rooby Confirmed it is "ON" on a fresh install

Additionally, comments permissions are defined in govcms_permissions feature module
- Site editor has the permission "Administer comments and comment settings"

**Comment by aleayr** [comment]
Since comments are on by default now, this should now be solved.
