### ISSUE TITLE
Custom content types don't feature Moderate or Edit Draft tabs

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#115]
On a local install of govCMS when I use standard content types there are the moderate and edit draft tabs available after content is created.

I created a custom content type and the moderate and edit draft tabs are no longer present.

**Comment by stooit** [comment]
This is the standard behaviour provided by the Workbench moderation module -- you need to enable moderation when creating the content type:
<img width="651" alt="screen shot 2015-11-25 at 2 16 21 pm" src="https://cloud.githubusercontent.com/assets/1256274/11388206/39c637b0-937f-11e5-8986-a6c2d239fc0c.png">

ok to close?

**Comment by aleayr** [comment]
Can do.
