### ISSUE TITLE
404 Everywhere

### ISSUE THREAD

**Issue by barbun** [govCMS/GovCMS7#12]
Hey guys, sorry for being a pain in the ass but I'm just trying to get it working.

After a successful build, I created the host that points to govcms/docroot folder.
When I navigate to the website I get the homepage that looks like on the attached file:
![govcms](https://cloud.githubusercontent.com/assets/7392927/8714875/94acabb6-2bbd-11e5-8176-f9eaf4a6dc60.png)

When I try to navigate anywhere (contact, publications etc) I get 404 Not found. Even /user doesn't work.

Did I just do something stupid or missed an important part?

Thanks.

**Comment by stooit** [comment]
Hi @barbun,

This looks like an issue with your webserver configuration. For clean URLs to work you'll need your web server to allow certain things in the .htaccess file.  This is outlined in detail here: https://www.drupal.org/getting-started/clean-urls

You can also disable clean URLs: https://www.drupal.org/node/5590

**Comment by barbun** [comment]
My apologies, I'm running a fresh install of Ubuntu and missed that part out. Works like a charm:)
