### ISSUE TITLE
Remove master branch

### ISSUE THREAD

**Issue by pandaskii** [govCMS/GovCMS7#123]
Although master branches are commonly used in the Git world, the Drupal community uses major version branches (e.g., 7.x-1.x) instead, since master could be compatible with D6, D7, or even D8.

Drupal community also suggests that "Git's default master branch should not be used and no downloadable releases can be tied to that branch."

Reference: 

https://www.drupal.org/node/1015226

https://www.drupal.org/empty-git-master

**Comment by fiasco** [comment]
I totally agree! I think we should cut a 7.x-2.x branch for the existing govCMS project. This also gives us namespace availability for a govCMS 3.0 on Drupal 8 (8.0.x-3.x).

**Comment by aleayr** [comment]
I support this as well, well worth tying this to the 2.0 milestone as suggested by @fiasco and tying to the release of a stable version (#99).

**Comment by nathan-w** [comment]
Has this been done? I don't see a Master branch in the repo. Can we close this?

**Comment by fiasco** [comment]
Yup, this has been done-ski!
