### ISSUE TITLE
As a site editor I want to curate lists of content so that I can promote items that are considered important

### ISSUE THREAD

**Issue by gollyg** [govCMS/GovCMS7#124]
A current project requires control over promotional items on various landing pages. This control includes:
- the ability to promote arbitrary items to various promotional areas within the site
- the ability to control the order of the items in these lists
- a usable interface for adding, removing, and sorting items.

This functionality has come up in a number of projects, and is a common requirement when using landing pages with promoted content.

Node queue http://drupal.org/project/nodequeue would appear to satisfy these requirements.

**Comment by fiasco** [comment]
We were discussing this in #108 and were heading towards EntityQueue as it has the flexibility to order any entity. Thoughts?

**Comment by gollyg** [comment]
Would be happy with that as an approach.
