### ISSUE TITLE
As a content editor I would like an accessibility checker so that I can have an automated check for simple mistakes

### ISSUE THREAD

**Issue by WebProject2015** [govCMS/GovCMS7#129]
In organisations where end users are producing content within govCMS, it is important that they are enabled to produce accessible content. There will always need to be an accessibility assurance check performed by hand, however an automated checker will help to eliminate the majority of common mistakes and accidental exclusions. As well as being a useful checklist tool, such a module will function as an additional form of training for new users, by gently reminding them of the basics of accessibility.  

 While it is possible to achieve this goal using browser plugins, such plugins are not always possible to install in standardised operating environments, and users are less likely to use checkers which are out of context. Moreover, it would be best if there were a whole of government govCMS standard automated checker.    

 We aren't proposing a specific module, as there are a lot of alternate solutions and this is a whole of govCMS decision. Our preference would be for a solution or combination of solutions which also included readability analysis.

**Comment by aleayr** [comment]
Thanks @WebProject2015, definitely hear you on this one. We've been working to get this in, and will hopefully do so shortly, in fact we have a couple of pull requests for this currently #48, #49.

Do you think this would solve the problem you're trying to address?

**Comment by WebProject2015** [comment]
Yes, that looks like it meets our requirements,  sorry we missed it.

**Comment by aleayr** [comment]
No, not a problem at all! Just confirming we weren't about to put something in that might not have considered all the factors people were looking for. We'll be merging that in shortly.
