### ISSUE TITLE
As a website administrator I want to export views so that I can use this data in other ways. 

### ISSUE THREAD

**Issue by WebProject2015** [govCMS/GovCMS7#130]
Due to govcms being such a powerful tool for managing content, there is often a business requirement to use this managed content outside of the system itself. Views allow lists and tables to be generated programatically in ways which are not possible using internal tools, and websites often combined information from various disperate areas of an organisation.  As such there are often requests to web teams for reports, or for excel versions of dynamically generated tables from the site. This will be a universal challenge for all agency web teams.  

 Examples might be a request from management for a list of all pages on the site, or for a list of all pages edited by a specific person, or for a spreasheet showing all website users by role. I could list examples all day, the fundamental point is that govcms is extremely capable of producing powerful datasets, but fundamentally incapable of exporting this information in any meaningful way. As such, we would like the Views Data Export module to be considered for inclusion.

**Comment by aleayr** [comment]
Well worth considering in my book. Coming from a corporate web team myself, I know the exact requests you're talking about. We used to manually compile and send out spreadsheets when content review time came around, this would help in that situation (and many others).

**Comment by fiasco** [comment]
@srowlands @gollyg - what views export options do we have to date?

**Comment by gollyg** [comment]
None at this point. The obvious choice would be [Views Data Export](https://www.drupal.org/project/views_data_export) (currently at 7.x-3.0-beta9). Another approach would be to expose it through services, but services is not currently in the distribution either, and it would need [Services Views](https://www.drupal.org/project/services_views).

**Comment by WebProject2015** [comment]
While Services is not in the distribution, there does appear to be a UUID module which is in the distribution and has an unmet dependency on Services, so inclusion of Services would enable that module.  The inclusion of Services Views may also be of use in creating a data.gov.au bridge as described in issue 146

**Comment by fiasco** [comment]
I've long advocated for Services module and see that as a more elegant implementation. Though it doesn't have CSV as a exportable format that Views Data Export will have.

**Comment by gollyg** [comment]
The user story here mentions exporting data to be used in other ways. Services seems a good fit for this, and will easily expose methods to sort on that data etc. Obviously, the provision of json, jsonp, xml, and yaml formats supports a wide range of applications. 

Depending upon the structure of the data being requested and returned, a transformation into a CSV client side should be possible, although obviously complex nested data structures could be problematic.

But this is clearly not as easy to configure and use as the Views Data Export option in the specific case of CSVs.

More broadly, the addition of services would greatly enhance the usefulness of govCMS and its interoperability.

Another approach might be to include both approaches, although this would need to be considered in terms of module crossover and bloat.

**Comment by kurtfoster** [comment]
I have two clients that require dynamic maps based on data from data.gov.au. Services module would allow me to load the data in as json in order to render the polygons via Google Maps API in the theme. 

One client requires polygons that have ~3,000 lat long data points per polygon for ~200 polygons. Loading these in via the modules mentioned in [issue #110](https://github.com/govCMS/govCMS/issues/110) will be too slow. The requirement for this site is for a single page website with almost all navigation handled via the map. govCMS PaaS is mandated. Services views would also be required to allow pulling in other nodes related to each polygon area via ajax. 

As it stands I can't see another option for creating this website.

**Comment by fiasco** [comment]
I'm keen to see Services module and Services Views in govCMS - @kurtsalsa are you happy to provide a pull request.

@teamglenny / @aleayr - any thoughts about whether it should be enabled out of the box?

**Comment by kurtfoster** [comment]
@fiasco, yep, that's my plan. I'm just finishing off another project. I should be able to get to it by the end of the week.

**Comment by kurtfoster** [comment]
@fiasco. What are the chances of getting this into govCMS in the next couple of weeks. Is there anything I could do to try and speed it up?

**Comment by fiasco** [comment]
@kurtsalsa I just committed it in for you. In its current state, you don't get any controls enforced by govCMS yet but you'll be able to do what you need for your site build.

**Comment by kurtfoster** [comment]
@aleayr, I've replied to an email from @fiasco re this module. We have a current requirement for this for our Vic Govt client, however I initially created this PR for another Federal Govt Client for a site that should be scheduled after the May budget.

**Comment by Podgkin** [comment]
I just wanted to drop in and say that this solution doesn't seem like a very user friendly or intuitive solution for the original use case of exporting views to excel.  

I can just imagine the look on the face of publishers and editors when they're told to raise a ticket to configure services to use XML, then clone each view to create a service, then assuming it can handle the size of your query, save the resulting webpage as an XML file and and then import it into Excel.  

Has anyone found a good way to actually make this work for producing excel spreadsheets?
