### ISSUE TITLE
hide compiled Drupal files under docroot from Git version control

### ISSUE THREAD

**Issue by pandaskii** [govCMS/GovCMS7#134]
From the distribution contributor's perspective, it is not necessary to leave complied Drupal files in Git under docroot in the distribution.

In fact having those compiled files in docroot may cause confusion in Git after following the documented build process. Thousands of newly compiled files will appear in Git post-build and it makes making simple contributions very difficult.

Reviews of some popular distributions in the Drupal community for example Commerce Kickstart, Drupal Commons, OpenChurch, Acquia Drupal etc revealed that none leaves compiled Drupal files in Git.

It however could be beneficial for non-distribution maintainers/developers to track compiled files in their own Git repos. However from the distro's perspective the file structure as it stands today is more of a impediment. Ultimately compiled files should be left out of distribution version control.

**Comment by fiasco** [comment]
@jozhao could you please explain why this is a blocker for upstream contributors? Omitting docroot from your commit is all you need to do to ensure its not added to your contribution. That doesn't seem so hard?

**Comment by pandaskii** [comment]
It is not hard for a upstream contributor omitting docroot from commit, so downstream that adding it.

I raised this discussion more from distribution level and Drupal community practise.

It could be beneficial for non-distribution maintainers/developers to track compiled files in their own Git repos. However from the distro's perspective the file structure as it stands today is more of a impediment. Ultimately compiled files should be left out of distribution version control.

**Comment by typhonius** [comment]
@jozhao I'm looking at this from the perspective of a distribution maintainer. After building the site using composer and Drush make, the only change I see when I check my `git status` is the `docroot` directory. As long as we don't `git add` this directory then we won't see any of the contents with `git status` or `git diff`.
![](https://i.imgur.com/evam9XJ.png) 

Additionally, as an upstream distribution maintainer, we're typically not ever going to be working with the `docroot` directory. Instead we're going to be seeing the effects of our changes made above the docroot before cleaning that out and creating PRs of our upstream changes.

If this is proving difficult to ignore, individual developers could consider adding the `docroot` directory to their global `gitignore` -> https://help.github.com/articles/ignoring-files/#create-a-global-gitignore

**Comment by pandaskii** [comment]
No problems with either approach. :)

Are you guys happy to add this to our official wiki? I think it could be helpful for govcms community.

**Comment by fiasco** [comment]
I agree that this should be better documented!
