### ISSUE TITLE
As a content editor I want to be able to easily find broken links on the site so that I can ensure all site links are useful to site visitors

### ISSUE THREAD

**Issue by kurtfoster** [govCMS/GovCMS7#145]
The linkchecker module is great but the report doesn't provide any filtering. I know there have been several clients so far that have found this lack of filtering difficult. This issue needs some further work to get the patch working https://www.drupal.org/node/1796882. I think it will be a good addition to govCMS.

**Comment by fiasco** [comment]
I agree, if we can apply a patch from that issue queue and assign the permission to content editors in govCMS, the PR would likely be accepted.

**Comment by kurtfoster** [comment]
I've created a few fixes on my local. I haven't had a chance to finish them off yet. I've got a few busy weekends coming up, but I'll try and get it done asap. It'll save me (and probably others) some headaches re the module.

**Comment by aleayr** [comment]
That would be great @kurtsalsa, look forward to seeing the PR.

**Comment by aleayr** [comment]
Just a nudge on this one @kurtsalsa as to whether you've had any time to refine this?

**Comment by kurtfoster** [comment]
Sorry @aleayr, still working most weekends right now so I haven't had a second to look at it.

**Comment by aleayr** [comment]
No rush, don't work too hard mate :)

**Comment by aleayr** [comment]
Noted this was merged, closing.
