### ISSUE TITLE
Managing webform select options with taxonomy

### ISSUE THREAD

**Issue by dylan-oxide** [govCMS/GovCMS7#147]
Hi,

We have a use case where our client wants to manage the select options on their webform using Taxonomy.

Is it possible to include something like https://www.drupal.org/project/webform_term_opts in the distribution?

Thanks

**Comment by aleayr** [comment]
Terribly sorry I missed this one @dylan-oxide 

Do you have a fleshed out use case of what they're trying to do that they can't do currently? Is it a permissions thing, or ease of use in updating a taxonomy rather than the webform itself?

**Comment by dylan-oxide** [comment]
@aleayr  TBH it was mainly ease of use. They are used to being able to bulk upload and manage terms via taxonomy. However realistically it is not that different to just use the field version that webforms has. So I think I will close this issue as there really isn't a strong enough business case for a substantial difference in ease of use.
