### ISSUE TITLE
First sidebar appears over the top of the content area

### ISSUE THREAD

**Issue by rooby** [govCMS/GovCMS7#149]
When I assign blocks to the first sidebar the sidebar appears over the top of the content area, breaking the layout.

I am currently using govcms 7.x-2.0-beta8 with a sub-theme of govcms_zen that has not had any CSS changes since setting up the site.

This is what it looks like with a block in the second sidebar. Looks normal.
![govcms-contact_second_sidebar](https://cloud.githubusercontent.com/assets/610162/12539981/f185719c-c352-11e5-8398-6ccd71661f5a.png)

This is what it looks like with a block in the first sidebar when logged out:
![govcms-contact_first_sidebar_anon](https://cloud.githubusercontent.com/assets/610162/12539979/f182967a-c352-11e5-9e57-8fce5766bf72.png)

This is what it looks like with a block in the first sidebar when logged in as user 1:
![govcms-contact_first_sidebar](https://cloud.githubusercontent.com/assets/610162/12539980/f183842c-c352-11e5-8c75-05e9f994661e.png)

**Comment by aleayr** [comment]
Thanks for letting us know @rooby, I'll take a look shortly and try to reproduce as well.

**Comment by aleayr** [comment]
@rooby, Can I understand how you did this? I've tried to reproduce, setup the same version of govCMS, and activated the govcms_zen theme, but I can't find a reference to a 'first sidebar' region by default in the theme.

I imagine I'm missing something that you've enabled or similar, so it would be helpful to know what I've missed so I can confirm this issue for you.

**Comment by rooby** [comment]
@aleayr 

The theme I was referring to actually a sub-theme of the the govcms_zen theme. So the GOVCMS_STARTERKIT theme, with the name changed but with no other modifications.

Then assign any block to first sidebar.

I have just done another fresh install and the default theme after install is govCMS (Barton) and has the same problem if I put a block in the first sidebar.

As a side note, it seems like a bug that govcms has no sidebar_first region since both zen, STARTERKIT and GOVCMS_STARTERKIT all have that region.

**Comment by teamglenny** [comment]
Is it in all browsers, or only one browser (and if so which one), @rooby ?

**Comment by rooby** [comment]
I have tested in FireFox 43 & 44, Chrome 47 & 48 and IE 11 and it happens in all of them.

I've tried 2 separate installs of GovCMS and it happens on both.

**Comment by fiasco** [comment]
Is this still a bug in 2.0? If so, please file a  pull request for us to review. Thanks!

**Comment by rooby** [comment]
Yes it is still a problem.

To reproduce:
1. Install default installation of GovCMS 2.0 (I included the example content).
2. Go to the block admin page and move all blocks in the second sidebar to the first sidebar.
3. Go to any page that has a sidebar (eg. publications or contact).

Unfortunately I don't have much time for front end work at the moment so realistically I won't be able to work on a pull request any time soon.

**Comment by pandaskii** [comment]
thanks @rooby I can reproduce the same issue and a fix is in PR queue now

**Comment by fiasco** [comment]
@rooby does that PR resolve the issue for you?

**Comment by rooby** [comment]
@aleayr do you know why this issue was closed? It wasn't fixed.

Since I can't reopen issues I have created a follow up #660.
