### ISSUE TITLE
As a web publisher i want global search and replace so i can update my content

### ISSUE THREAD

**Issue by WebProject2015** [govCMS/GovCMS7#151]
As a website grows it can be difficult to keep track of all the places a given piece of information is listed. This is especially true if the website had a lot of legacy content to begin with.  Often a request will come through to change all instances of one piece of information the website.   Examples include business areas which have changed names, important individuals who have moved on, or specific phone numbers or email addresses which need to be updated.  It is possible to search the site using external tools, but those methods cannot see all nodes, and govCMS should be able to perform this role itself.  Given we do not have access to use Drush or the ability to export and interrogate the database, there are not many options when it comes to maintaining the accuracy of content across a large site. 

 There would ideally be some protections to ensure replacement mistakes were not published. Search and replace should be separate permissions so it is possible to let editors search while only publishers can replace.  Replacing text on a piece of content should trigger workbench workflow for that piece of content, so that the relevant approvals process can be undertaken. There should be undo functionality so that mistaken changes can be mass reverted.  We have not found a module which fulfils all these needs, however Search and Replace Scanner comes the closest.  https://www.drupal.org/project/scanner

**Comment by aleayr** [comment]
When I was working on corporate web projects, this was something that came up a little bit.

That said, to frame expectations, I doubt this will be something implemented in the short term, but something that will need further discussion about how this should work and be implemented. The module you suggested doesn't seem to reference Workbench, so that would have to be something to look into as well, if that was identified as a critical request (which certainly makes sense).

@teamglenny Thoughts?

**Comment by stooit** [comment]
Generally you wouldn't want to run a long-running process against a production database, especially when not correctly batched.

The following statement leads me to believe there is no batch processing, which is a little disconcerting..

"Will dynamically expand PHP's maximum execution time for scripts up to 10 minutes on servers that support it. This allows complex queries on large bodies of content"

**Comment by WebProject2015** [comment]
@aleayr  We have had these discussions internally, and we had the same concerns.  However we felt that even just a global find capability, without the replace, would be highly beneficial. In that instance you would not need to trigger workbench since it would be a non-destructive query.  It would also reduce the permformance impact by quite a lot.  You could then still identify all the places a given term was mentioned and action them individually. This ultimately meets the core requirement, albeit with a manual component.  We don't feel this scales particularly well over thousands or tens of thousands of nodes, but it would still be better than having nothing.

**Comment by stooit** [comment]
@WebProject2015 it sounds like you could achieve what you're looking for with a combination of a custom search index (fulltext on all content fields you want to search) and an administrative view.

Using SOLR as a backend and letting Search API keep indexes up to date would make the performance concerns a non-issue.

**Comment by fiasco** [comment]
I agree with @srowlands. Its important to build a site with structured data so that tasks like this can utilise the structured data to find what you need. Full text search can be very powerful in this context.

From a hosted platform perspective, a scanner is more overhead requiring CPU and memory. Given to every site on the platform, we'd need a lot more resources per site. To implement a scanner IMO would be a poor architectural choice.

**Comment by gollyg** [comment]
Yep, +1 for the Solr approach, and it is OOTB.

**Comment by WebProject2015** [comment]
There is significant distrust of our search both internally and externally, it will be difficult to convince people to trust it, even if Solr does end up returning every value of any given keyword. Our initial thought is that it may not work for things like mailtos and classes.

**Comment by fiasco** [comment]
find and replace of classes shouldn't be the function of a content management system. Nevertheless it seems we can't discard Solr as a solution as its not been proven it can't solve the problem. 

If you have distrust in search tools to conduct the search part of search and replace - I'm not sure we can really fix that.

**Comment by invisigoth** [comment]
+1 for the Solr approach. To perform accurate search however some additional settings/search algorithms may be required, which could be a problem on Acquia platforms as the settings are locked up. There is however no reason a GovCMS site cannot be connected to a secondary Solr instance managed by agencies themselves for internal content management purpose. For agencies with SharePoint licence you can also consider the FAST Search Server as an option. When configured properly, FAST can also provide excellent results.

**Comment by fiasco** [comment]
Solr looks like the way to go. Closing. Thanks for all the help!
