### ISSUE TITLE
Embedded video and sound via media are being removed

### ISSUE THREAD

**Issue by dylan-oxide** [govCMS/GovCMS7#152]
If you use the media browser to embed video or audio sources, the WYSIWYG filter will strip these tags out. I would suggest adding the following to the WYSIWYG Filter options:

`video[controls|data-fid|data-media-element],source[src|type|data-cke-saved-src],audio[controls|data-fid|data-media-element],`

**Comment by aleayr** [comment]
Thanks Dylan, good to know. I imagine when this happens you need to switch back to HTML mode? Then if a content editor switches back for subsequent edits that they disappear again?

**Comment by dylan-oxide** [comment]
Correct, if you use the Full HTML text format, the markup is preserved. However if you use Rich text, the markup is removed.

For some more information, this is what is output by the WYSIWYG:

**Video**
`<video controls="controls" data-fid="7" data-media-element="1" class="media-element file-default"><source src="video.mp4" type="video/mp4"></video>
`

**Audio**
`<audio controls="controls" data-fid="8" data-media-element="1" class="media-element file-default"><source src="audio.mp3" type="audio/mpeg"></audio>
`

**Comment by aleayr** [comment]
Cheers. I'm wondering whether this is the same issue as #175, in which case we could kill two birds with one stone and get this resolved. I'll confirm when Pixie74943 replies in the other issue, and get a PR in place.

**Comment by aleayr** [comment]
Looks like a different issue, but I agree with this getting fixed. No use having a media browser if you can't insert all the media :)

**Comment by nathan-w** [comment]
Can we package this one up with #153 ?

**Comment by fiasco** [comment]
If they're different issues then we should have different PRs. But I've put them in the same milestone if we can get PRs in-time for them (👉  @dylan-oxide 😜 )

**Comment by samChinACT** [comment]
fixed in #337

**Comment by Venkata-modgu** [comment]
Audio and video tags are not been removed by the wysiwyg filter.
Test passed.
