### ISSUE TITLE
address and pre tags being removed by wysiwyg filter

### ISSUE THREAD

**Issue by dylan-oxide** [govCMS/GovCMS7#153]
The styles address and format are not retained after the page is saved. They use the `address` and `pre` tags which are removed by the wysiwyg filter.

I would suggest adding these to the settings
`address,pre`

Alternatively these styles could be removed from the styles dropdown if they are not supported.

**Comment by fiasco** [comment]
This seems like a no brainer fix to implement. address and pre tags are harmless, there isn't any reason why we wouldn't support them.

**Comment by teamglenny** [comment]
Agreed.

**Comment by nathan-w** [comment]
Id like to see some priority on this given it's a no-brainer and its been hanging around for a while. Would be sensible to give our filter settings a sanity check in case there are a few other no-brainer tweaks we can do.

**Comment by fiasco** [comment]
@dylan-oxide if you're able to put together a PR for this, we've ear-marked it for the 2.7 release.

**Comment by Venkata-modgu** [comment]
Address and pre tags are not been removed by the wysiwyg filter.
Test passed.
