### ISSUE TITLE
Google Analytics Reports module 1.x branch unsupported

### ISSUE THREAD

**Issue by rooby** [govCMS/GovCMS7#154]
GovCSM uses version 7.x-1.3 of the [Google Analytics Reports](https://www.drupal.org/project/google_analytics_reports) module, which is now unsupported.

This module should be updated to the latest recommended release.

**Comment by fiasco** [comment]
The 3.x branch is still in development according to the project page and there is no upgrade path available which means we'd need to do deeper analysis.
- What are we loosing by upgrading?
- What features are we gaining by upgrading?
- How will upgrading affect existing govCMS users?
- What work is involved to retain functions in the upgrade?

**Comment by pandaskii** [comment]
Google OAuth 1.0 (used in current 7.x-1.3 release) has been replaced by OAuth 2.0 as of April 20, 2015 https://support.google.com/a/answer/61017?p=oauth&rd=2

Update: local test confirmed this behaviour
- cannot setup authorization on the summary page /admin/reports/google-analytics 
- was redirected to Google*

*The OAuth 1.0 request is being redirected to this page https://support.google.com/a/answer/61017?p=oauth&rd=2 I am assuming this means that the current version of this module cannot be used at all.

**Comment by fiasco** [comment]
Thanks for the analysis @jozhao! that seems like pretty compelling evidence that we should be moving on to 7.x-1.3. And the fact that @rooby raised this issue suggests there is still demand for this capability in govCMS?

IMO, a pull request to upgrade google analytics reports module will likely be accepted.

**Comment by pandaskii** [comment]
Agree, good to know if there is still demand for this capability in govCMS? Otherwise a good time to reduce 1-2 modules :)

**Comment by rooby** [comment]
I don't actually have a need for this module, I think it's generally preferable to keep all management of Google Analytics in Google Analytics.

The only reason I noticed it is because it is installed by default and it comes up as a version not supported error in the available updates report.

Really I would say the problem is with that module removing support for the current version when the new version is still not ready.

I would be happy with cutting the modules.

**Comment by aleayr** [comment]
I know of a few agencies that make use of this module from a PaaS side of things for basic analytics, so it's probably something we should update rather than remove.

Does someone want to do a PR and we'll merge it in.
