### ISSUE TITLE
GovCMS PHP 5.6 Support

### ISSUE THREAD

**Issue by fiasco** [govCMS/GovCMS7#155]
As PHP 5.5 is end of life, we need to ensure that govCMS can run safely on PHP 5.6. [Acquia has put together some documentation](https://docs.acquia.com/articles/common-issues-when-upgrading-drupal-6x-and-7x-websites-php-56) on upgrading Drupal 7.x sites to PHP 5.6. We need to review that documentation and identify what issues there are for govCMS to be ready for PHP 5.6.

**Comment by WebProject2015** [comment]
As per Acquia's advice, can we suggest spinnning up temporary test environments running 5.6 for each site, so agencies can see if there are any errors being generated by their site?   It would provide an overview of the error logs from different module combinations and enable agencies to do a rudimentary check of any custom code previously developed inhouse or by vendors. It is obviously not as exhaustive as full code audits, but it will at least let agencies check their site functions without requiring dedicated PHP gurus.

**Comment by fiasco** [comment]
@aleayr how are you tracking with this one? I believe we are going to provide PHP 5.6 test environments to SaaS customers right?

**Comment by aleayr** [comment]
Has been done, and emails were sent at the end of last week to all customers for testing :+1:

**Comment by fiasco** [comment]
This is now fixed.
