### ISSUE TITLE
Some govCMS sites on Acquia site factory are hitting the memory limit

### ISSUE THREAD

**Issue by invisigoth** [govCMS/GovCMS7#156]
It has been reported that an increasing number of sites are hitting the ASF memory limit when executing some content/site admin functions such as loading the list of available tokens.

Acquia's support engineer has advised that altering the memory limit in php.ini is not desirable as this will affect all sites in the same environment. A solution to use the site factory hooks is therefore recommended by Acquia, however this hook needs to be implemented at the distribution level and will also affect all sites on the govCMS platform. This makes the ASF hook solution not too different from the php.ini solution as far as govCMS tenants are concerned.

An alternative solution is to look at only giving logged-in users such as content editors and site builders increased memory limit to minimise risks. Hooks such as hook_init() and hook_boot() seem to provide a way for us to conditionally alter memory limit. Modules such as Role Memory Limit (https://www.drupal.org/project/role_memory_limit) could also be a quick solution and can be enabled for only sites that hit the limit and require more memory and the settings can be locked to only uid=1.

**Comment by invisigoth** [comment]
Recent pull request #140 could potentially be benefited from a higher memory limit. See Acquia's doco on indexing large attachments: https://docs.acquia.com/articles/issues-large-attachments-and-solr-search

**Comment by invisigoth** [comment]
This issue is now tracked in Acquia's ticketing system. The goal is to increase GovCMS memory limit to the same level as Acquia Dev Cloud. Close on Github.

**Comment by fiasco** [comment]
@invisigoth the default memory limit on Acquia Dev Cloud is 128M - https://docs.acquia.com/cloud/configure/environments/php
