### ISSUE TITLE
Process for upgrading Metatag module

### ISSUE THREAD

**Issue by dylan-oxide** [govCMS/GovCMS7#158]
What is the process for getting a contrib module upgraded to a newer version?

Metatag is up to v7.11 as opposed to v7.4 in GovCMS.

There is a bugfix for this issue that I believe is in the latest stable release that is affecting our sites currently.
https://www.drupal.org/node/2467587

Is that something that can be upgraded?

Thanks

**Comment by mstrelan** [comment]
I had this same question. See #52

**Comment by aleayr** [comment]
More specifically as well (for this module), see #166 (noting it was created after this ticket) :)

We're trying to get much quicker on actioning these PRs, so I do apologise for the delay that has been occurring currently.
