### ISSUE TITLE
Do we need AGLS and why?

### ISSUE THREAD

**Issue by MadeByMike** [govCMS/GovCMS7#165]
For a long time AGLS metadata has been stated as a 'mandatory requirement' for government websites.

To the best of my knowledge this requirement originated in the [AGIMO Web Guide](http://webguide.gov.au/) but this has been superseded by the [Digital Service Standard](https://www.dto.gov.au/standard/). The Digital Service Standard supports the direction of the National archives, yet the [National Archives website](http://www.agls.gov.au/documents/obligation/) information has not updated this page since 2013.

From a compliance perspective it is more confusing, despite its stated 'mandatory' status none of the documentation seems to reference a legislative requirement or other sufficient directive. 

From a practical perspective the title and the description metatag are important for search, but beyond this microformats and other structured data only serve a purpose when trying to achieve specific outcomes. Where it serves a practical purpose I completely support it and encourage people to mark-up data as semantically as possible but without any harvesting applications it is unclear what purpose Dublin Core and AGLS metadata tags serve.

I'd like to know what other agencies and individuals attitudes towards AGLS are and perhaps start a discussion about whether the AGLS module should be enabled by default in govCMS. If it is a requirement and direction that govCMS intends to support can someone describe the need and the benefit? And is AGLS still the best way to meet this need?

**Comment by WebProject2015** [comment]
The benefits of open data have not yet been fully realised, but the excercise is still valuable. The semantic structure of data is an important pre-condition to a range of applications which are still evolving. Automated archival scrapes make use of metadata for structuring, as do content scrapes for other purposes such as third party tools. 

Some people say that search engines do not use metadata, but that is not actually completely true. Google disregards most metatags but they do have a list of supported metadata tags which includes the Title, Description and Content Type mentioned in AGLS.   https://support.google.com/webmasters/answer/79812?hl=en

As a more govCMS specific example, indexing and pushing content between sites using Content Hub and Government as an API, the metadata could well prove valuable for presenting the originator of a set of information.  Following that line of thinking, If the vision of a single whole of government website ever comes true then metadata will prove invaluable in organising all these hundreds of thousands of pages we're creating,

 The internet of things may well make use of metadata too, perhaps smart fridges will want to look for product recalls or smart luggage will want to check for travel advice. Deep learning algorithms are   making use of semantic metadata in training and recall, and virtual reality versions of our sites don't nessecarily look like webpages, they may not use our styling but still use our metadata.  The reality is that we just do not know what specific applications will arise, but we can be sure that semantic structuring of information is key to enabling future improvements to the web..  Tim Berners-Lee's touches on this in a ted talk he gave on the future of open data on the web. http://www.ted.com/talks/tim_berners_lee_on_the_next_web

**Comment by mgdhs** [comment]
@WebProject2015 I agree, metadata is value and a good way to describe semantic relationships. The problem is AGLS is likely not the solution to that any more.

Something like [schema.org](http://schema.org/) may be a better solution, which comes from the industry. There is even a number of [government schemas](http://schema.org/docs/search_results.html#q=government) which we could easily fit into or enhance. The advantage these have is that they are standards (?), international and are [used by search engines right now](https://developers.google.com/structured-data/rich-snippets/).

**Comment by MadeByMike** [comment]
@WebProject2015 I'm a huge supporter of web standards and in principal I don't disagree with any of your stated goals. But I am not sure AGLS is still the best way to meet these goals in 2016. 

Do you know of specific archival scrapers or third party tools that make use of AGLS metadata for structuring? I don't know of any, at least none that use AGLS but I am very happy to be wrong about this.

I'd love to hear more about how Content Hub uses AGLS but I would also ask if AGLS is the best way to support Content Hub or a future move towards a single whole of government website. I think there could be much better ways to do this.

You also mentioned the Internet of Things and Deep learning, and yes, I'm sure these things will make use of structured data in some way but the truth is we don't how yet. However it happens I'm confident it won't make use of an Australian Government standard from 2008. 

Sometimes I feel that we are not very good in government at having these discussions. We can at times be more focused on supporting the standards than the outcomes they aimed to achieve. The W3C for example is constantly changing or depreciating standards to meet real world implementations or because the original problem has been made redundant by new technology. In the last few days aria roles were depreciated on some HTML elements where they had become redundant in HTML5. This matches current industry practice around their usage.

That is the discussion I want to have. Not to criticise the intentions.

**Comment by invisigoth** [comment]
@MadeByMike, as far as I know Funnelback is one of the search engines that can make use of AGLS. I myself a few years ago contributed an AGLS plugin to Apache Nutch. The AGLS metadata is used to provide faceted search in both cases. I however am not advocating AGLS but think this needs a review at the policy level.

My biggest concerns around AGLS are: (1) W3C validators will report errors on pages where AGLS metadata is implemented. There have been efforts to get AGLS schema included in the international standard but that didn't happen. (2) it may expose Drupal user name in the metadata, which could be a security concern.

Also I think it's unlikely that Acquia Content Hub has specifically implemented AGLS. https://github.com/acquia/content-hub-php

**Comment by fiasco** [comment]
Content Hub isn't a content renderer, its a content syndicator. It won't syndicate configuration, just content.

**Comment by Podgkin** [comment]
@fiasco  Is it not possible to add metadata as a string attribute to a Plexus entity? Wouldn't we want to retain the provenance of syndicated content?

**Comment by fiasco** [comment]
@Podgkin you're right, metadata can be added. Specifically, Metatag module metadata is supported.

**Comment by Podgkin** [comment]
@MadeByMike  I contacted the National Archives of Australia, as the agency responsible for maintaining AGLS. They advised that AGLS is part of the Digital Service Standard

https://www.dto.gov.au/standard/design-guides/common-website-elements/metadata/

 I have now provided them with some context on govCMS, Content Hub and schema.org.  I gave them a link to this discussion and asked the following four questions:
1.  What is AGLS currently being used for?  
2.  What would break if we shifted to a different standard? 
3.  Is AGLS still the most appropriate Australian government metadata solution?  
4.  Has the NAA considered switching to schema.org?

**Comment by Podgkin** [comment]
Another update, the NAA have replied. Though they did not answer my questions, they have informed me that the AGLS is currently undergoing a 5 year standards review by the AGLS sub-comittee, and they are currently reviewing schema.org and other relevant inputs. 

I would posit that given DoF were involved in the original recomendation of AGLS as a standard, and DTO are currently recomending it, they are likely both already involved in the review process at some level.  

I will be attending their next sub-comittee meeting in May, and suggested they should specifically invite a representative from the govCMS team to discuss Australian government metadata standards.

**Comment by MadeByMike** [comment]
Thanks so much for this! This is exactly the type questions that need to be
asked and the right way to do it, it seems.

Thanks!

**Comment by aleayr** [comment]
@Podgkin, how was the sub-committee meeting in May? I don't believe a govCMS member ended up getting invited (unless I'm mistaken).

**Comment by Podgkin** [comment]
I had told them the govCMS team were the best contacts on Content Hub, and I then never heard from them again. I never received an invite for the May meeting so I had presumed they had reached out to you guys instead.
