### ISSUE TITLE
As a site editor I want to embed other site content via the WYSIWYG editor

### ISSUE THREAD

**Issue by stooit** [govCMS/GovCMS7#167]
We are currently building a large department site where the ability to embed nodes within other content (via WYSIWYG) has come up a few times.

The real use case is here is to allow structured content to be embedded within non-structured content so it may be reused across the site.

This is also related to the work underway for #146 where we have a structured entity (data.gov.au visualisation) which we need to embed via a WYSIWYG plugin. Instead developing a plugin that only caters to this graph type we could widen the net and allow any entity/node to be embedded in the same way.

Modules for consideration:
- [entity_embed](https://www.drupal.org/project/entity_embed)
- [node_embed](https://www.drupal.org/project/node_embed)
- [token_insert_entity](https://www.drupal.org/project/token_insert_entity)
- [attach](https://www.drupal.org/project/attach)

**Comment by DJMyles** [comment]
Our site would greatly benefit from this as well as we have common content snippets that are reused across multiple pages of various content types.

**Comment by fiasco** [comment]
As much as I'm not a fan of Paragraphs, could Paragraphs be the solution here? Allowing a paragraph type to embed referenced content? In this way, data continues to be structured rather than tokenized which may not play so nicely with an all of government API.

**Comment by stooit** [comment]
@fiasco I had considered Paragraphs, but got a little hung up on the need for very 'inline' pieces of structured content (for example an embedded person profile that's floated right somewhere within a body of text).

I don't hate the idea of using Paragraphs that way though (actually, as it's intended!). I might go back and see if we can bend things slightly to make that possible.

**Comment by fiasco** [comment]
I recall there is a module called Classy that lets you add classes to paragraphs through the UI to be able to do exactly that sort of thing.

**Comment by Pixie74943** [comment]
This would also be useful for DECD.

Although our information is split across a couple of CMSs (specifically Squiz Matrix, which runs sa.gov.au), so our ideal solution would allow us to embed content from any site (grabbed from the front end).

**Comment by Wongad** [comment]
This will also be useful for AFSA as referenced from one of our issue #157

**Comment by fiasco** [comment]
I can see that this approach will be a better UX for content editors but using Paragraphs is going to be a more structured approach that will allow us to manage that embedded content in a better way.

Unless there is some hard reason why Paragraphs is not tangible, I'm inclined to go with that approach for now.

**Comment by fiasco** [comment]
If Paragraphs doesn't fit, please file a new ticket. Thanks.
