### ISSUE TITLE
Remove Pathauto Persistant State module and update Pathauto to 7.x-1.3

### ISSUE THREAD

**Issue by invisigoth** [govCMS/GovCMS7#174]
The Pathauto Persistant State module is now obsolete and has been rolled into Pathauto 7.x-1.3. 

Also, it has been reported that the Pathauto Persistant State module has prevented URL alias in GovCMS from being bulk generated after deletion.

Acquia ticket Ref# 259351

**Comment by pandaskii** [comment]
For a smooth process
1. Update Pathauto module [7.x-1.3 Release notes](https://www.drupal.org/node/2582001)
2. Disable and remove Pathauto Persist module

Pathauto will migrate "Pathauto Persist" database tables/settings to new implementation during module update process. After migration process, Pathauto Persist module can be safely disabled and removed.

> Pathauto Persist is installed and enabled. As Pathauto Persist has been merged into Pathauto, the Pathauto Persist module can be safely disabled and removed. All Pathauto Persist settings have been migrated to the Pathauto implementation. (Pathauto module 7.x-1.3 install file)

Refs: 

[How does Pathauto determine if the 'Automatic URL alias' checkbox should be checked or not?](https://www.drupal.org/node/1167612)

[Merge in pathauto_persist module functionality to prevent losing manual aliases with node_save() calls](https://www.drupal.org/node/936222)

[node_save() obliterates any custom path with an auto-generated version](https://www.drupal.org/node/2617716)

**Comment by aleayr** [comment]
This looks fine, given the functionality is replicated, and we get to remove a module.

@jozhao, is your proposed approach is in a release, update the Pathauto module, and then in the release after, disable and remove Pathauto Persist?

Will we have any additional additional conflicts during those two release windows, having both modules active? When we remove Pathauto Persist, do we need to do anything for our existing sites to use the functionality of the base Pathauto module instead?

**Comment by pandaskii** [comment]
@aleayr add #69 [Pathauto Persist is now obselete](https://github.com/govCMS/govCMS/issues/69) here as it is same issue, and we can keep either of them

BTW, noticed that recently we are having at least three issues which require a similar release cycle process. Do you think if we can put them in one basket?
- Pathauto Persist is now obselete #69
- Escape Admin module breaks back to site navbar functionality #148 
- Google Analytics Reports module 1.x branch unsupported #154
-  First pass to replace iconomist and favicon with responsive_favicons #50

**Comment by aleayr** [comment]
Should be able to.

**Comment by nathan-w** [comment]
Let's run a test of the proposed release cycle for these 4 changes and if it goes smoothly get these scheduled on a milestone.

**Comment by aleayr** [comment]
Merged #355. Closing.
