### ISSUE TITLE
Vimeo videos not embedding through WYSIWYG

### ISSUE THREAD

**Issue by Pixie74943** [govCMS/GovCMS7#175]
Hey Team,

Using the WYSIWYG editor and attempting to embed a vimeo video is not working in our live site (though it was in our test site). I've tested with a wide variety of videos, and nothing from Vimeo is working. The same plugin works fine for Youtube.

Not an urgent issue as we only have a couple of videos and I'm embedding them manually via iFrames, but something to look in to if you ever have a free moment. I'm assuming the issue is with govCMS and not the module itself, as it's working on my test site.

**Comment by aleayr** [comment]
Hi @Pixie74943, when you say not working, do you mean the WYSIWYG editor is getting rid of the video when you save it, or it's displaying a broken video player (like it can't load from Vimeo)?

Where is your test environment? Is it on a local network/machine, on the govCMS managed hosting environment or elsewhere?

**Comment by Pixie74943** [comment]
Hi Adam,

The test environment is on my desktop. I've pushed this site up to Acquia Cloud and the videos still work nicely.

On our govCMS environment (decd-sa.govcms) we don't get any result. The iframe embeds, and takes up space on the page, but nothing loads inside of that space.

The HTML output is:
`<p><iframe src="http://player.vimeo.com/video/108854850?autoplay=1" width="400" height="225" class="video-filter video-vimeo vf-108854850" frameborder="0"></iframe></p>`

Looking at the section using the google chrome developer toolbar, nothing has been loaded inside the iframe.

Sorry my original post wasnt clear, hopefully this helps.

**Comment by aleayr** [comment]
All good, I was just making sure I fully understood it.

Do you have an example URL you should give me on the decd-sa.govcms site that isn't working, so we can investigate? (and maybe an example on the Acquia Cloud that is working?)

**Comment by pandaskii** [comment]
One possible reason https://developer.mozilla.org/en-US/docs/Security/Mixed_content/How_to_fix_website_with_mixed_content

Also check Google blog: https://googleonlinesecurity.blogspot.com.au/2011/06/trying-to-end-mixed-scripting.html?m=1

**Comment by Pixie74943** [comment]
Hey @jozhao that looks like the issue.

Using google chromes dev toolbar, I can change the iframe source from a http:// to a https:// and it loads cleanly.

The problem then following is that I am using a https:// in the WYSIWYG editor but then when that is rendered by the rich text editor it changed it out to a http:// 

**written into the WYSIWYG**
`[video:https://vimeo.com/87523337]`

**rendered result:** 
`<iframe src="http://player.vimeo.com/video/87523337?autoplay=1" width="400" height="225" class="video-filter video-vimeo vf-87523337" frameborder="0"></iframe>` )

Looks like this isn't a govCMS issue, but an issue with the Media plugin in the WYSIWYG (I think, correct me if I'm wrong)

**Comment by pandaskii** [comment]
Confirmed it is a protocol bug with [Video Filter](https://www.drupal.org/project/video_filter)

There is a patch in official dev branch https://www.drupal.org/files/issues/video_filter-https_support-786774-7.x-3.1.patch we will need a manual review to see if we can replace [current patch in govCMS which only fix YouTube](https://www.drupal.org/files/issues/2438439-video-filter-protocol-fix.patch) with this one

**Comment by Podgkin** [comment]
@jozhao Just taking a look at that code, they are doing pretty similar things, but one list of sites is longer than the other.  This raises two points: 
1. Do we really need explicit support for all of those sites, college humour and gametrailers for example seem like strange things for us to patch in explicit support for.  To use this solution, do we need to come up with our own curated list of whitelisted sites that each have their own function declaration?
2. Should we even have a whitelist enforced at the platform level? The solution in these patches could be generalised, it seems a bit redudant to have a specific function for every seperate video site on the net. If any agency wanted to link to a different video source we'd need to alter the patch for the entire distribution.

**Comment by fiasco** [comment]
I'm open to maintaining a whitelist for the platform however if its not in the source code, then it needs to be documented (which is an aspect we're still growing a capability in).

**Comment by pandaskii** [comment]
＠Podgkin govCMS is using a community module "Video Filter" - https://www.drupal.org/project/video_filter

Since it is a community module, it has to support many service providers. Most of them, never heard :)  It is a quite common question on Drupal community modules, basically we may use 5% of whole functions but have to accept other 95% 

Included codecs - copied from https://www.drupal.org/project/video_filter
- Archive.org
- Blip.tv
- Capped.tv
- College
- Humor
- DailyMotion
- Flickr
- Slideshows
- Flickr
- Video
- Gametrailers
- Gamevideos
- Godtube
- Google
- Video
- Metacafe
- Myspace
- Picasa
- Slideshare
- Streamhoster
- Teachertube
- Vimeo
- Wistia
- YouTube

@fiasco We are using 7.x-3.1(2012-Nov-14) with a patch for youtube, the new patch https://www.drupal.org/files/issues/video_filter-https_support-786774-7.x-3.1.patch is in this module's development branch 7.x-3.x-dev(2015-Sep-24)

**Comment by fiasco** [comment]
Surprising that youtube support isn't in a stable release. We'll have to continue to use a patch for now as running a dev release will update modules when we run builds without our explicit knowledge that its happening.

**Comment by pandaskii** [comment]
Hi guys,

This pull request https://github.com/govCMS/govCMS/pull/207 can fix this issue.

Cheers

**Comment by pandaskii** [comment]
Is this still a bug in 2.0? or we can close this issue :)

**Comment by Pixie74943** [comment]
I've just tested this on my site using 3 separate videos and they all loaded correctly.

There is an extremely minor issue that if autoplay is not checked, the video still auto plays, but that is pretty easy to work around.

Thanks for the fix guys :+1:

**Comment by pandaskii** [comment]
@Pixie74943 I will have a look the autoplay issue (I can re-produce same issue)

**Comment by pandaskii** [comment]
Such behaviours can be edited in text format filter settings

Find **Video Filter** tab

![screen shot 2016-05-19 at 11 01 43 am](https://cloud.githubusercontent.com/assets/1326673/15379482/22135f82-1db1-11e6-875f-3d7afa5b7462.png)

Or if user cannot access to above settings for permissions, can add "autoplay:0" manually

for example:

`[video:https://vimeo.com/161138986 autoplay:0]`

**Comment by Pixie74943** [comment]
Excellent, I wouldn't have thought of looking over there [😊] Cheers

**Comment by Chris820** [comment]
Don't forget that the rendered iframe will need a suitable title attrib in order to pass the Single-A 4.1.2
ref: http://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20160317/H64

**Comment by Pixie74943** [comment]
Thanks for pointing this out Chris.

I've had a quick read over the documentation for this module, and there doesn't seem to be a way to add a title. We may to have to stop using this until it can be resolved.

**Comment by pandaskii** [comment]
Yes, H64 suggests iframe should be with a "title" attribute.

Two options here (example only, needs more work on prod) :

**\-  Implements hook_video_filter_video_alter()**

Only works under PaaS since theme is too late,  for example

```
/**
 *  Implements hook_video_filter_video_alter().
 */
function custom_module_video_filter_video_alter(&$video) {
  $video['attributes']['title'] = 'this is a video';
}
```

**\- Implements theme_video_filter_iframe()**

Works under SaaS, for example

```
/**
 *  Implements theme_video_filter_iframe().
 */
function custom_theme_video_filter_iframe($variables) {
  // Copy codes from theme_video_filter_iframe().
  // Add title attribute.
}
```

**Comment by Chris820** [comment]
There may also be an option to fix using JavaScript.
But honestly, I prefer @Pixie74943 's suggestion of avoiding the use of the module and manually adding in the iframe. Editors can enter an accurate title attrib during authoring.

**Comment by aleayr** [comment]
I think there are enough workarounds discussed here to mark this resolved as per the original issue. If you would like a separate issue raised for the title attribute feel free, otherwise, we also have the oEmbed module available now which supports Vimeo which may also assist in embedding content.
