### ISSUE TITLE
New govCMS default theme built on Bootstrap

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#176]
As far as I'm aware, there is a new/replacement default theme being considered, so this is a holding issue for tracking that.

@teamglenny I think you knew something about this?

**Comment by aleayr** [comment]
Noting the above PR, can we review the HTML output for the new theme with a view to removing or substantially reducing the conditional statements?

**Comment by pandaskii** [comment]
A quick question - are we aiming to Bootstrap 4 or 3?

Bootstrap 4 is still under alpha release and here are some highlights
- Moved from Less to Sass
- Improved grid system
- Opt-in flexbox support
- Dropped wells, thumbnails, and panels for cards
- Consolidated all our HTML resets into a new module, Reboot
- Dropped IE8 support and moved to rem and em units

REF: [Migrating to v4](http://v4-alpha.getbootstrap.com/migration/)

When Bootstrap 3 was shipped, Bootstrap immediately discontinued all support for v2.x. Although this time Bootstrap may have different supporting plan for v3, keep our fingers crossed :)

**Comment by gavintapp** [comment]
I don't think a final decision has been made on v3 or v4 - but it would be good to her more views on this. Typically, govCMS leans toward stable versions - but if the release schedule for v4 aligns with the plan for a new default theme, it would seem a good move to use v4.

**Comment by fiasco** [comment]
I think we should port to v3 and then look to upgrade to v4 at a later date when its more stable. The larger challenge will be providing a reasonable out-of-the-box experience of a bootstrap theme for govCMS.

**Comment by seanhamlin** [comment]
Also of note, there is no current release of the base theme bootstrap for alpha 4, it has essentially been postponed until it is stable by the looks - https://www.drupal.org/node/2554199

I agree with @fiasco, v3 makes the most sense for now, v4 can be evaluated later when the upgrade path is better known (and actually exists).

**Comment by gavintapp** [comment]
More broadly, is there consensus to use Bootstrap over other frameworks?

**Comment by fiasco** [comment]
yes - Bootstrap has a market dominance which presents a lower barrier to entry to govCMS as well as a better support system.

**Comment by paulkilla** [comment]
Are we putting any thought (If we are supporting a base bootstrap theme) into modules which enhance its usability in drupal. (see https://www.drupal.org/node/2011034).

I think the main ones would include, bootstrap integration with display suite, panels, and views. (Makes it a lot easier than all sites using bootstrap constantly modifying template files)

**Comment by barbun** [comment]
Potential issue might be that govCMS currently uses jQuery version 1.4.4 and Bootstrap requires greater than 1.9. Upgrading of the jQuery can break some existing functionality.

Also, how critical is the support of IE? There might be an issue with Bootstrap supporting older versions. I know some agencies are still using IE8 :8ball: 

I suspect some tests will need to be re-written too.

In addition, what is an impact for the existing customers who use govcms_zen as their base?

**Comment by paulkilla** [comment]
I don't think we will be removing govcms_zen as a theme.  In terms of the jQuery version we could add a preprocess function in the template.. e.g. (Have used this on a number of themes which we use with bootstrap as the base theme, see blog.data.gov.au (on govCMS))

``` php
function theme_js_alter(&$javascript) {
  $node_admin_paths = array(
    'node/*/edit',
    'node/add',
    'node/add/*',
  );
  $replace_jquery = TRUE;
  if (path_is_admin(current_path())) {
    $replace_jquery = FALSE;
  }
  else {
    foreach ($node_admin_paths as $node_admin_path) {
      if (drupal_match_path(current_path(), $node_admin_path)) {
        $replace_jquery = FALSE;
      }
    }
  }
  // Swap out jQuery to use an updated version of the library.
  if ($replace_jquery) {
    $javascript['misc/jquery.js']['data'] = '//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js';
  }
}
```

**Comment by rooby** [comment]
Does anyone know if this bootstrap theme is going ahead?

If so, is there a rationale for why that is happening instead of improving what we already have and instead using leftover resources for bug fixes and other improvements?

**Comment by aleayr** [comment]
@rooby The base theme will be updated to reflect/showcase govCMS, rather than the older aGov fork (the current default theme is still the default from aGov), but we have prioritised other work, which is why it isn't completed.

The actual govCMS technical team is very small, and we rely on contributions from the govCMS community to augment our own efforts in advancing the platform.

**Comment by TobyWild** [comment]
Thanks for the Code snippet Paul.  OPC is building a site with Bootstrap and it needed updated jQuery.
Wouldn't it be easier with the jQuery Update module that allows you to set jQuery versions per theme, including Admin sections.

**Comment by invisigoth** [comment]
Hi @TobyWild if you use the public theme for content authoring, features such as auto-complete will be broken as the jQuery version injected by jQuery Update is newer. hook_js_alter is your best friend.
