### ISSUE TITLE
As a govCMS contributor I want Travis to allow longer than 10m for Behat tests to complete so that I don't get false failures.

### ISSUE THREAD

**Issue by stooit** [govCMS/GovCMS7#178]
Currently Travis has a 10m timeout on operating tasks. Since these tests run on shared environments and build testing times differ depending on load at any given time it's not possible to be confident that tests will complete during that time.

I'd propose we bump this timeout and re-evaluate if the issue pops up again.

**Comment by aleayr** [comment]
Thanks @srowlands, good to know.

**Comment by fiasco** [comment]
We dropped Travis support so this is no longer an issue.
