### ISSUE TITLE
Why are we handling issues in Github?

### ISSUE THREAD

**Issue by typhonius** [govCMS/GovCMS7#18]
Posted by kyuubi on July 17, 2015 at 10:34am

Hey guys,

Just trying to understand why we are handling the project issues in github.

This is a Drupal distro and people will typically search for issues here not in github.

Can you clarify?

Thanks

**Comment by typhonius** [comment]
Great question and thanks for asking. We have a lot of tie-ins with the govCMS codebase to ensure we are able to deliver a high quality, well tested distribution with a desire to test new features and functionality. By utilising github and all of its integration points, users are able to submit pull requests, see them automatically tested and iterate upon them. In doing so, we're continuing to encourage active participation to developers who may not be drupalists but have a stake in govCMS.

The integrations also provide better exposure to our team chat so we can answer support requests, bugs, feature requests promptly.

Plus, we love `markdown` and emojis :princess:

**Comment by dalebaldwin** [comment]
Just be aware that in doing this you are potentially isolating the existing Drupal community from having input and contributing a wealth of experience to this project. The way you guys are currently running this is considerably abrupt and not particularly well communicated.

I would also keep in mind the modularity of Drupal and that there are likely to be issues with core modules being picked by GovCMS users that need to be dealt with over at drupal.org as part of their module issue trackers not over on Github. This has potential to create a huge mess and you guys need to be uber careful with how you are managing this.

One of the major benefits of using Drupal has been the ability to deal with issues that occur across modules and distributions in one place, moving over to Github strips that out and really does separate any GovCMS community from the Drupal Community at large and I don't think that's a good idea.

**Comment by stooit** [comment]
Hi @quantumninja,

Thanks for the feedback.

There are pros and cons to each approach. In this case we have several requirements that mean running purely from d.o is not possible, and it makes more sense for our development workflow to manage issues and codebase changes in GitHub.

We don't believe running from GitHub is a detriment to community involvement and contribution, but agree tying local issues to relevant d.o issues will need to happen diligently. We'll see what can be done to make this integration as pain free as possible.

**Comment by teamglenny** [comment]
No further input to this "issue" for a while.  We'll be listening and monitoring the community on this topic.
