### ISSUE TITLE
SA-CORE-2016-001

### ISSUE THREAD

**Issue by Feng-Shui** [govCMS/GovCMS7#182]
Morning all,

What's the process by which security issues affecting core or contrib modules in govCMS are updated? And what are the timeframes in which updates are rolled out, and is it relevant to the issue's severity?

Cheers

**Comment by fiasco** [comment]
on it.

**Comment by fiasco** [comment]
@Feng-Shui I check for sec updates each Thursday and roll PRs if required (such as now).

**Comment by aleayr** [comment]
Thanks @Feng-Shui and @fiasco :+1:

**Comment by Feng-Shui** [comment]
@fiasco Ok, cool, so sounds we just sit tight and wait for that process to complete then following our own processes for pulling from the repo.  If you're not around, are we generally happy for anyone to file a pull request for these?

**Comment by fiasco** [comment]
Yup, there is not special reason why the task is exclusively mine - if someone else gets to it before me - thats fine too.

**Comment by Feng-Shui** [comment]
Ok cool, I'm usually online - well, reading the news bleary eye'd in bed - when these come in, so happy to chip in too.

**Comment by Feng-Shui** [comment]
@fiasco thanks for getting this one into the repo so quickly.
