### ISSUE TITLE
7.x-2.x-beta9 build blockers

### ISSUE THREAD

**Issue by fiasco** [govCMS/GovCMS7#184]
7.x-2.x-beta9 contains a Drupal core security update but won't currently build on Drupal.org because of this issue:

```
 >> Project google_chart_tools (7.x-1.4) could not be downloaded to /tmp/make_tmp_1456354305_56ce34015c5fc/__build__/modules/contrib/google_chart_tools.
 >> Unable to patch google_chart_tools with google-chart-tools-ajax-1613258-11-7.x-1.4.patch.
```

**Comment by fiasco** [comment]
This is weird since our CI bots didn't pick this up.

**Comment by Feng-Shui** [comment]
I just rebuilt the project and didn't have any issues with that patch.

**Comment by stooit** [comment]
@fiasco the error `could not be downloaded to` would indicate it's a file permission if you're testing this build locally.. Try sudo? beta9 seems to build ok for me.

**Comment by fiasco** [comment]
This error occured on Drupal.org - its out of my control. But I haven't seen this issue occur on any other builds.

**Comment by aleayr** [comment]
Successfully been deployed to staging/test environment now, can this be closed @fiasco? Or is the issue still at d.o?

**Comment by fiasco** [comment]
this is still an issue with d.o that I'll have to follow up with.

**Comment by fiasco** [comment]
This issue is now resolved and beta9 is available on drupal.org.

**Comment by pandaskii** [comment]
"Development release" is older than "Recommended release" on drupal.org

How about keep only "Recommended release" on drupal.org?

**Comment by fiasco** [comment]
yeah, for dev release they should really come to github. I'll remote it.
