### ISSUE TITLE
Remove Travis CI integration

### ISSUE THREAD

**Issue by fiasco** [govCMS/GovCMS7#189]
@typhonius added travis CI to this project in the beginning which was great. But recently its stopped passing tests. It can no longer build govCMS in a timely manor and its breaking travis support to a point where its no longer useful to the project.

@srowlands has a build bot instead which seems to be working well that does what travis CI does already (though, it doesn't support PHP 5.5 but we won't need to shortly either).

So I put it out to the community whether we should keep Travis CI or not. If we don't have any good reasons, or a working Travis in the next couple of weeks, I'll remove it.

**Comment by stooit** [comment]
Agreed the current PR environments appear to be a more stable place to do the testing, and we're currently duplicating the test effort. The amount of false negatives in Travis recently have meant it's not really offering much benefit as-is.

The only thing I'd raise is non-magnum Travis is free, whereas the govCMS-bot environment requires ongoing maintenance and has a hosting cost associated.

**Comment by fiasco** [comment]
govCMS-bot does need a bit more love and care to keep it running (and money). Should it ever leave us, we can bring travis back.

I'm going to remove Travis CI.

**Comment by typhonius** [comment]
:skull: RIP Travis. :rose:
