### ISSUE TITLE
Feature request: flood_unblock module

### ISSUE THREAD

**Issue by cjoneill** [govCMS/GovCMS7#193]
Prompted by some support tickets received by Acquia, we think there could be merit in including the [Flood Unblock](http://dgo.to/flood_unblock) module to provide a UI that could allow self-rescue by agencies when staff run afoul of the flood table.

Would such a module be compatible with mandated security controls?

Relevant ticket reference: 265109

**Comment by fiasco** [comment]
I like this idea. Integration into govCMS should also include preconfiguring the module to work for specific roles. @aleayr to advise which roles that should be.

**Comment by invisigoth** [comment]
Please note this issue has been discussed in our CAB meeting and a solution is already in place. It will be released pending approval of the govCMS security team.
