### ISSUE TITLE
As a site administrator, I would like to implement an online exit survey so I can track user satisfaction

### ISSUE THREAD

**Issue by mpigott** [govCMS/GovCMS7#196]
Does anyone have any ideas about what tool would play nicely with GovCMS to create an online exit survey? I mean the kind of survey that asks for someone's permission to provide feedback when they visit the website but doesn't engage the user until they exit. 

Some of the requirements would include:
- the survey meets the Privacy Act requirements 
- the admin can set how frequently the survey appears to users. 

I can see there are options such as [iPerceptions 4Q](https://www.iperceptions.com/en/4q) and [Qualaroo](https://qualaroo.com/product/) but I am wondering if a module could help with this. It might also help agencies measure user satisfaction as per the Digital Service Standard requirements.

**Comment by fiasco** [comment]
IMO, I'd advocate to handle this outside of govCMS. Perhaps a javascript implementation added to a site theme? This kind of functionality is no doubt a SaaS product these days and makes sense to use them over maintaining a community feature they may only benifit a niche of the community.

**Comment by aleayr** [comment]
@mpigott I might close this one off, since as @fiasco mentioned, it's probably more suited to a SaaS product implemented in JavaScript on the theme level.

If you think this still has merit inside govCMS, happy for you to reopen this and give some more info :+1:

**Comment by mpigott** [comment]
No worries @aleayr. I think this is a good suggestion from @fiasco. Cheers.
