### ISSUE TITLE
As a Site Builder (or Site Editor) I want an easy way to add menu items so that I can maintain the menu structure of my site.

### ISSUE THREAD

**Issue by kurtfoster** [govCMS/GovCMS7#199]
I'm getting quite a few "that's weird" looks during govCMS training when I try and explain how to manage menus in Drupal. The standard drupal menu system doesn't provide an auto complete on the "Path" field on menu items. Users either need to remember the path (not easy) or manage the link in the node, then go back to the menu to manage position (two locations for one task). 

The [Multi-path autocomplete](Multi-path autocomplete) does provide the ability to autocomplete in the path. I think this would be a good usability improvement for govCMS.

**Comment by fiasco** [comment]
I like the idea. The module architecture looks fine too, although, not actively maintained. From a technical standpoint I don't have a problem with it, although, I suggest we add it to the profie installation and provide an update hook to turn it on for all govCMS sites.

**Comment by aleayr** [comment]
Yeah, this is a good suggestion. I tend to use the node, knowing the weight that I need to set things to, but that's clunky, especially if someone else has just set arbitrary weights to the menu.

Would support this.

**Comment by mstrelan** [comment]
[Content menu](https://www.drupal.org/project/content_menu) is another solution which also allows the author to choose the menu item location before creating the content, or select existing content for a new menu item by searching on the node title. This would be a more significant UI change though.

**Comment by fiasco** [comment]
We need to get this tested to verify its fixed, otherwise, we'll have to push back to 2.2 release.

**Comment by fiasco** [comment]
Pushing back to 2.2 as this needs testing.

**Comment by aleayr** [comment]
@Venkata-modgu Are you able to take a look at this and test for inclusion?

**Comment by aleayr** [comment]
As per #276, pushing to next release.

**Comment by Venkata-modgu** [comment]
The "Path" field is auto compleate on menu items. Tested with Site Builder and Site Editor roles.
Test passed.
