### ISSUE TITLE
Install fails on MAMP

### ISSUE THREAD

**Issue by typhonius** [govCMS/GovCMS7#20]
Posted by Dale Baldwin on July 15, 2015 at 10:56am https://www.drupal.org/node/2533330
Trying to install on latest version of MAMP for testing. I'm getting this error when it gets to the last module to install.

```
An AJAX HTTP error occurred. HTTP Result Code: 500 Debugging information follows. Path: http://localhost:8888/govcms/install.php?profile=govcms&locale=en&id=1&op=do StatusText: Internal Server Error ResponseText: Uncaught exception thrown in shutdown function.PDOException: SQLSTATE[HY000]: General error in _menu_set_expanded_menus() (line 3365 of /Applications/MAMP/htdocs/govcms/includes/menu.inc).
```

It seems to install but am not getting to the user setup page afterwards to setup admin etc.

**Comment by typhonius** [comment]
Is this a repeatable error? I'm not seeing this on either my native OSX build, a Debian container build (from https://github.com/typhonius/govcms-docker) or our travis test framework.

My instincts here say that MySQL on the MAMP server needs to have either the variable for wait_timeout or max_allowed_packet raised.

**Comment by jamesastaylor** [comment]
I have had similar issues with MAMP with the developer release we received awhille back. It looked like a issue with the install profile. We have since moved to a DAMP stack which has to seemed to resolve the issue.

**Comment by pandaskii** [comment]
By default my.cnf in MAMP is for a system with small memory

For development or test purpose, I would like to suggest 

```
# The MySQL server
[mysqld]
max_allowed_packet = 100M
```

And since Drupal is with InnoDB tables, you may uncomment few lines in MAMP my.cnf template

```
# Uncomment the following if you are using InnoDB tables
innodb_data_home_dir = /Applications/MAMP/db/mysql/
innodb_data_file_path = ibdata1:100M:autoextend
innodb_log_group_home_dir = /Applications/MAMP/db/mysql/
# You can set .._buffer_pool_size up to 50 - 80 %
# of RAM but beware of setting memory usage too high
innodb_buffer_pool_size = 1G
innodb_additional_mem_pool_size = 128M
# Set .._log_file_size to 25 % of buffer pool size
innodb_log_file_size = 256M
innodb_log_buffer_size = 32M
#nnodb_flush_log_at_trx_commit = 1
innodb_lock_wait_timeout = 60
```

**Comment by invisigoth** [comment]
I'm running govCMS on MAMP 3.1 and set max_allowed_packet to 16MB without any issue with installation. As suggested by jozhao, in MAMP Go to File > Edit Template and change max_allowed_packet in MYSQL my.cnf

**Comment by aleayr** [comment]
With the suggested work around here, are we happy to close this off?

**Comment by teamglenny** [comment]
We'll be closing this one out soon if there is no further input

**Comment by pandaskii** [comment]
@aleayr @teamglenny  Happy to write a MAMP and govCMS Development page in govCMS wiki page if needed

**Comment by typhonius** [comment]
If you can write wiki pages with your permissions and want to contribute that'd be a great idea to point users experiencing difficulties to. 

We also have a govCMS on dev desktop video we can point users to

—
Adam Malone

On Friday, 30 Oct 2015 at 19:51, Joseph Z notifications@github.com, wrote:

@aleayr @teamglenny  Happy to write a MAMP and govCMS Development page in govCMS wiki page if needed

**Comment by fiasco** [comment]
We should definitely get some references to the govcms dev desktop into our documentation. I'd prefer we not document setups we're not willing to help support or maintain.

**Comment by teamglenny** [comment]
Due to (pickyourflavour)AMP configs being out of the control for the govCMS service, and the original issue not able to be replicated, will close this ticket.

**Comment by jamesastaylor** [comment]
I had no problems with the build and setup of govCMS on Acquia Cloud / Dev desktop. We moved to this after initially having issues with MAMP.  I would just recommend staying that you don't support MAMP in your documentation, only a DAMP or LAMP stack.
