### ISSUE TITLE
Token Tweaks module (As a content author, I'd like my site to not show out of memory errors when editing pages that generate large token trees)

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#201]
Some sites running on the distribution are running into issues when they accumulate large amounts of tokens. This often manifests as an out-of-memory error, which generates when the token tree being built is excessively large.

The token tweaks module modifies the behaviour of the base level token module, only showing a specific depth at any one time, limiting the memory consumed by generating large token trees.

Would be good to get this into the distro ASAP if people don't have a specific issue against including it.

**Comment by fiasco** [comment]
I'm all for it, are you looking for someone to produce a PR?

**Comment by aleayr** [comment]
If someone would like to, that would be great. I just don't have a machine to do that with today.

**Comment by fiasco** [comment]
#202 was merged which addresses this issue.
