### ISSUE TITLE
Ability to create wildcard redirects to support legacy content

### ISSUE THREAD

**Issue by Pixie74943** [govCMS/GovCMS7#203]
Our agency has a large number of documents containing links to webpages/other documents that have been migrated to our new site. This will cause many broken links. Many of these could be captured with the use of a wildcard redirect (e.g. .../docs/1/\* redirects to /documents/*)

I'm unsure if there are any modules that meet this functionality, but the existing redirect module only accepts single arguments (tested, and read [project page](https://www.drupal.org/project/redirect))

**Comment by fiasco** [comment]
Assuming the broken links reach govCMS, you can use the redirect module to manage these which is already in govCMS.

**Comment by Pixie74943** [comment]
We have over 1500 documents to bring over. Most were previously hosted under /docs/1/_some-file-name_

Our new file path is /doc/_some-file-name_

If it was this simple I would set our new file paths to also be docs/1/_some-file-name_ and call it a day.

However our old system also had documents sorted under /_name-of-subweb_/pages/_some-file-name_ and /_name-of-subweb_/files/_some-file-name_ . There are over 50 of these subwebs.

I don't consider it practical to create an individual redirect for each of those 1,500 documents. It would take roughly 250 man hours. 

The existing module in govCMS does not accept a wildcard, which would allow me to set up  redirects from each subweb to the new document path (assuming the file name remained the same).

**Comment by fiasco** [comment]
@Pixie74943 sounds like a valid requirement but it doesn't look like there is a good solution available from the Drupal community at the moment.

### Options
- Do nothing. Usually not the prefered approach but still an options.
- Commission work to add wildcard redirecting to the Drupal community that can be used by govCMS
- Engage with a vendor to script adding 1.5k of redirects into the redirect module. We could run this script for you on the SaaS platform

**Comment by Pixie74943** [comment]
I was hoping for a module similar to this one (this allows wildcards in the source, but not the final page)

https://www.drupal.org/project/match_redirect

This would solve at least part of the problem by allowing us to point the subweb link to the new location e.g. previously we had /hr, /hrprofessionaldevelopment and /hrhealthandsafety. All these are now encompassed under /working-decd

I'll have to chat to the team about another solution for documents

**Comment by invisigoth** [comment]
We have done this for a high profile website to redirect about 200,000 urls when they migrated from another technology to Drupal. Module redirect provides an API to bulk created redirects and if this is simply a one-off task, the easiest way is to use this API to create redirects programmatically.

The example below reads redirects from a temporary url_alias_migrate table, where the old and new urls are stored. Records in the url_alias_migrate table can be populated using Excel and a simple macro that outputs MySQL queries.

```
/**
 * Form submit handler; insert or update an URL redirect.
 *
 * @see redirect_edit_form()
 */
function redirect_edit_form_submit($form, &$form_state) {
  form_state_values_clean($form_state);
  $redirect = (object) $form_state['values'];
  $url_alias_migrate = db_query('SELECT * FROM {url_alias_migrate} WHERE dst LIKE :alias', array(':alias' => 'pattern/%/more%'))->fetchAll();

  foreach ($url_alias_migrate as $alias) {
    $redirect = new stdClass();
    redirect_object_prepare($redirect);
    $redirect->source = $alias->dst;
    $redirect->redirect = 'http://newdomain.gov.au/'.$alias->src;
    $redirect->language = 'und';
    // Check if the redirect exists before saving.
    $hash = redirect_hash($redirect);
    if (!redirect_load_by_hash($hash)) {
      redirect_save($redirect);
    }
    $redirect = new stdClass();
    redirect_object_prepare($redirect);
    $redirect->source = $alias->src;
    $redirect->redirect = 'http://newdomain.gov.au/'.$alias->src;
    $redirect->language = 'und';
    // Check if the redirect exists before saving.
    $hash = redirect_hash($redirect);
    if (!redirect_load_by_hash($hash)) {
      redirect_save($redirect);
    }
  }
  return;
  redirect_save($redirect);
  drupal_set_message(t('The redirect has been saved.'));
  $form_state['redirect'] = 'admin/config/search/redirect';
}
```

**Comment by aleayr** [comment]
Given @invisigoth's update with the code to make this bulk loading happen, I'll close this off. If you need more clarification, please open a new new issue.
