### ISSUE TITLE
Feature request: solr_devel module

### ISSUE THREAD

**Issue by paulwhenry** [govCMS/GovCMS7#204]
Prompted by some support tickets received by Acquia, we think that it would be worthwhile including the [Solr Devel](https://www.drupal.org/project/solr_devel) module to provide the ability for Acquia Support and customers to gain a granular view of the search index and queue status of nodes, as well as debugging tools for troubleshooting search issues.

Relevant recent support ticket reference: 267858

**Comment by fiasco** [comment]
Thanks @paulwhenry - we probably wouldn't add it to the public distro but we could certainly look at providing it for the SaaS platform if @aleayr is happy to do so.

**Comment by fiasco** [comment]
After a bit of discussion with @aleayr, this doesn't make sense for the distro. But it does make sense for the SaaS platform. So we'll close this off and take it up in the SaaS issue queue.

Thanks!
