### ISSUE TITLE
Add media support for oembed media sources

### ISSUE THREAD

**Issue by gollyg** [govCMS/GovCMS7#205]
_As a site editor I want to manage external media within the media module so that I can better manage site assets_

Specific use cases:
- Manage a library of Vimeo videos
- Manage site specfic metadata on Vimeo videos in a re-usable way (eg tagging)
- Build lists of videos using views
- Attach Vimeo videos to content types
- Define view modes that display the video

The media module is currently part of govCMS. The [Media oEmbed module](http://drupal.org/project/media_oembed) provides support for the [oEmbed format](https://en.wikipedia.org/wiki/OEmbed), meaning that any media provider supporting oEmbed can be integrated into a govCMS site.

So whilst the above use cases refer to Vimeo specifically, any oEmbed provider could be supported.

https://github.com/govCMS/govCMS/issues/175 relates to the video filter, which is currently in govCMS. This module does not provide the rich data model around videos, reducing them to a tag in the markup that is not easily extracted.

**Comment by aleayr** [comment]
I'm not opposed to this per se, I see oEmbed has a number of providers it supports by default which is good, how is this exposed in the interface from a UX perspective?

**Comment by aleayr** [comment]
Following on from this, I've had a number of enthusiastic responses to 'hallway' conversations I've had concerning this, so there is a lot of support for this approach.

**Comment by fiasco** [comment]
@gollyg are you happy to get a PR under way? Seems like the sort of thing we may want to have available be default too right?

**Comment by gollyg** [comment]
Yep, will add that in. There was a mention of disabling the video_filter module by default. Do you want that included @fiasco ?

**Comment by fiasco** [comment]
Its definately worth discussing but perhaps its a different issue.
