### ISSUE TITLE
DB exception when Superfish is disabled

### ISSUE THREAD

**Issue by Feng-Shui** [govCMS/GovCMS7#206]
When the Superfish module is disabled, and `_block_rehash();` is called (clear cache, block listing page etc.), `govcms_block_info_alter();` is invoked and does the following:

`$blocks['superfish'][1]['title'] = '<none>';`

As this block doesn't exist, the above actually creates a block definition but the module, delta etc are all NULL, resulting in a PDO exception.

`govcms_block_info_alter();` should use an `isset();` on all blocks that it alters that are not it's own like it does in `govcms_system_info_alter();`

I'll roll a patch for this issue this week.

**Comment by pandaskii** [comment]
Just a quick thought,[ hook_block_view_MODULE_DELTA_alter ](https://api.drupal.org/api/drupal/modules%21block%21block.api.php/function/hook_block_view_MODULE_DELTA_alter/7) is safer

**Comment by Feng-Shui** [comment]
@jozhao If we go that way, and we want to check for each of the three blocks before altering them, then we'd be replacing the current function with three new ones.

Having said that, the other two blocks are the help and user-menu from the system module, so we prob don't need to check for those before we alter.  At the moment, I'm just going to check for the superfish block, so will prod just use an isset() check.

Thoughts?

**Comment by pandaskii** [comment]
@Feng-Shui I was thinking a hook_block_view_superfish_1_alter last night and maybe move this to theme since it is not a good practise to keep it in disto profile page. Not have a solid time to dig deep why this line here, but found a feature module govcms_superfish_configuration (just few variables there and it can be disabled safely after superfish is disabled)

Anyway, no problem on isset but question why this line is here :)

**Comment by Feng-Shui** [comment]
@jozhao went with a quick isset() for now, I think your point is valid through, this is a presentation level change, prob best placed to move it into the theme at some point.

**Comment by fiasco** [comment]
We'll accept this one into the 2.1 release.

**Comment by fiasco** [comment]
@Feng-Shui can we get the pull request resubmitted against the 7.x-2.x branch?

**Comment by Feng-Shui** [comment]
@fiasco https://github.com/govCMS/govCMS/pull/232

**Comment by fiasco** [comment]
Fixed in #232
