### ISSUE TITLE
Events view should show events that are currently in progress

### ISSUE THREAD

**Issue by mstrelan** [govCMS/GovCMS7#209]
The default criteria for the events view is to show any events with a start date greater than now. It should show events where the end date is greater than now, otherwise week-long events (for example) wouldn't appear in the list after it has started. The finish date on events, however, is not mandatory, so instead the filters from the Date Views module need to be used to search if either the start or finish date is greater than now. In fact, I usually set it to greater than ~~"midnight tonight"~~ "12AM today" instead of "now".

**Comment by fiasco** [comment]
Makes sense to me.
- Do all events have end dates? And if they didn't what would happen? Perhaps more complex Views filters could be used to filter on start date for events without end dates?
- Greater than 12AM today is a good suggestion and better than `now` which isn't a cacheable value.

**Comment by mstrelan** [comment]
I've just submitted a pull request. The date filter adds an OR condition for the start and finish date, so finish date can be NULL. The new query is below.

```
SELECT node.sticky AS node_sticky, field_data_field_event_date.field_event_date_value AS field_data_field_event_date_field_event_date_value, node.nid AS nid
FROM 
{node} node
LEFT JOIN {field_data_field_event_date} field_data_field_event_date ON node.nid = field_data_field_event_date.entity_id AND (field_data_field_event_date.entity_type = 'node' AND field_data_field_event_date.deleted = '0')
WHERE (( (node.status = '1') AND (node.type IN  ('event')) AND (DATE_FORMAT(ADDTIME(field_data_field_event_date.field_event_date_value, SEC_TO_TIME(36000)), '%Y-%m-%d') >= '2016-04-04' OR DATE_FORMAT(ADDTIME(field_data_field_event_date.field_event_date_value2, SEC_TO_TIME(36000)), '%Y-%m-%d') >= '2016-04-04') ))
ORDER BY node_sticky DESC, field_data_field_event_date_field_event_date_value ASC
LIMIT 10 OFFSET 0
```

And the old query:

```
SELECT node.sticky AS node_sticky, field_data_field_event_date.field_event_date_value AS field_data_field_event_date_field_event_date_value, node.nid AS nid
FROM 
{node} node
LEFT JOIN {field_data_field_event_date} field_data_field_event_date ON node.nid = field_data_field_event_date.entity_id AND (field_data_field_event_date.entity_type = 'node' AND field_data_field_event_date.deleted = '0')
WHERE (( (node.status = '1') AND (node.type IN  ('event')) AND (DATE_FORMAT(ADDTIME(field_data_field_event_date.field_event_date_value, SEC_TO_TIME(36000)), '%Y-%m-%d\T%H:%i') >= '2016-04-04T09:26') ))
ORDER BY node_sticky DESC, field_data_field_event_date_field_event_date_value ASC
LIMIT 10 OFFSET 0
```

**Comment by mstrelan** [comment]
I suspect that the DATE_FORMAT(ADDTIME(... )) part of the query is not terribly efficient, and I also suspect that Views would improve the query if the date field storage was a Unix timestamp. Difficult to update existing databases though, and have not benchmarked this at all. Definitely out-of-scope for this issue.

**Comment by aleayr** [comment]
@jozhao @invisigoth Any chance of having a look over this and providing feedback on the approach before it gets merged?

**Comment by pandaskii** [comment]
@aleayr happy to merge it, nice work

**Comment by fiasco** [comment]
Merged, Thank you for your contribution!
