### ISSUE TITLE
Webform profanity filter

### ISSUE THREAD

**Issue by mpigott** [govCMS/GovCMS7#220]
Is there a way to prevent users from entering swear words into a webform? Obviously my work's security won't let the email get through but the webform submissions are still stored on GovCMS. 

It would be good if we could maintain a blacklist of words and the webform prevents users from submitting if a word from the blacklist has been entered into any of the webform fields.

**Comment by aleayr** [comment]
Is the use-case because since the email will be blocked at the network level, the user has the expectation that the message has been delivered, when it probably hasn't been seen by anyone (notwithstanding it has been stored on govCMS)?

**Comment by mpigott** [comment]
No, I think the main use-case is protecting employees from abusive language. However, I think it is concerning that feedback could get lost in the database without us knowing about it.

**Comment by Wongad** [comment]
Will the following module (**Webform Validation**) be possible to add to the current functionality of the Webform module?
https://www.drupal.org/project/webform_validation

At least two of the validation rules should be able to maintain the blacklist from the text area.
- Must be empty (anti-spam: Hide with CSS)
- Words blacklist

Other rules which we'll need that is not available on the current Webform module is to set character/text limit on the text area fields.
- Minimum length
- Maximum length

**Comment by aleayr** [comment]
Agreed, do you have a suggestion as to the best way to approach this in your experience @mpigott?

**Comment by pandaskii** [comment]
We had a project years ago using Field validation (original code of the Field validation 1.x module was copied from Webform Validation but extend it for fields) https://www.drupal.org/project/field_validation

Worth to give it a try

**Comment by typhonius** [comment]
Webforms submissions actually aren't stored on govCMS due to the Webform Clear module (added due to PII data policies) ensuring the webform submission gets sent via email and not stored on the system.

**Comment by Wongad** [comment]
Thanks @typhonius , the Webform Clear module allows the selection of Webform submission storage period, which submissions will still be stored if the other options other than "Delete submissions immediately" is selected.
This will actually ensures that we could check back on the submissions if for any reasons that the submission did not get to our email inbox.

**Comment by typhonius** [comment]
I feel like this is more of an edge case issue that is best managed outside of govCMS. If a profanity filter is added, it would need to be highly customised to ensure there's no matching of perfectly valid words i.e. [Scunthorpe](https://en.wikipedia.org/wiki/Scunthorpe_problem) and continuously extended as users use creative methods to circumvent it (adding periods, numbers instead of letters etc).

**Comment by Wongad** [comment]
That's true, but at least a certain control can be implemented on use case basis.
As mentioned above, other than the Words blacklist, other functions such as the Minimum and Maximum character limit can really add value to the current Webform module.

**Comment by Podgkin** [comment]
How about using our new html email functionality and just styling potentially offensive words differently?  If you set background-color to the same colour as the text, then the word is blacked out, but the data is preserved. If you want to check what a blacked out word says you can just select the text with your mouse. 

It won't stop the ingeniously and creatively foul mouthed among us, but it would demonstrate at least some effort was expended on dulling the wicked edge from the most common expletives. This would ensure our sensitive darlings are protected while our stalwart inquisitors can still be horrified.

**Comment by aleayr** [comment]
I think the consensus is this is difficult to get right and not create false positives and potentially miss/block messages.

For this time, I'm going to close this off, however, if people have a new suggestion or idea, I'd be open to hearing it.
