### ISSUE TITLE
As a website user I need to be able to interact with dynamic content on a map so that I can find information based on location

### ISSUE THREAD

**Issue by kurtfoster** [govCMS/GovCMS7#223]
We currently have two upcoming sites that have interactive maps. One will be rendered with a shapefile in Leaflet / Open Layers. The other with TerraJS and WMS. 

Both maps require the ability to render polygons with pins at specific points within the polygons. Clicking on the polygons and or points will either render content based on the area that was clicked, or reload new areas on the map. The requirement on one is for a single page website, the obvious solution is to load content via ajax. The other has the majority of content on the map based page, the same solution makes the most sense for UX. 

Services and Services views will allow us to generate the content we require as json, which we can then easily manage in the theme via js to render what we need. I currently don't have another solution to implement these requirements.

**Comment by typhonius** [comment]
Services module is a requirement for one cultural institution and one state level agency looking to onboard to govCMS in the near future. Adding this comment as a means of registering their needs.

**Comment by fiasco** [comment]
Moving to 2.3 as the review process is likely to hold this back till then.

**Comment by fiasco** [comment]
Closing out as we've merged services into govCMS.
