### ISSUE TITLE
SA-CONTRIB-2016-020 - Features (Less Critical)

### ISSUE THREAD

**Issue by Feng-Shui** [govCMS/GovCMS7#224]
Morning all,

The following was released earlier this morning, we're running 2.5 (an affected version.  It's a pretty low risk.  Anyone see any issues with upgrading to the current release?

---

View online: https://www.drupal.org/node/2705637
- Advisory ID: DRUPAL-SA-CONTRIB-2016-020
- Project: Features [1](third-party module)
- Version: 7.x
- Date: 2016-April-13
- Security risk: 7/25 ( Less Critical)
   AC:Basic/A:Admin/CI:None/II:None/E:Theoretical/TD:All [2]
- Vulnerability: Cross Site Request Forgery, Denial of Service
## -------- DESCRIPTION

This module enables you to organize and export configuration data.

The module doesn't sufficiently protect the admin/structure/features/cleanup
path with a token. If an attacker can trick an admin with the "manage
features" permission to request a special URL, it could lead to clearing the
cache repeatedly and a Denial of Service (DoS) attack.

This vulnerability is mitigated by the fact that the admin with the "manage
features" permissions must be logged in when they request the special URL.

**Comment by fiasco** [comment]
Created #225 to address this.

**Comment by Feng-Shui** [comment]
Thanks @fiasco

**Comment by fiasco** [comment]
I just pushed a tag `7.x-2.0-rc2` which you can build from with this PR merged in. Otherwise you can build from `7.x-2.x` (the new `master` branch, see #226).
