### ISSUE TITLE
14 April, 2016 - Default Branch Change

### ISSUE THREAD

**Issue by fiasco** [govCMS/GovCMS7#226]
## 7.x-2.x

Today I changed the default git branch from **master** to **7.x-2.x** which reflects the Drupal.org branch naming convention and provides better clarification around govCMS's compatibility with Drupal.

As govCMS is currently in an RC (release candidate) state for 2.0, new PRs will be merged into the 7.x-2.x branch and released under 7.x-2.1 while the stability of the 7.x-2.0 release will be managed in the `release/7.x-2.0` branch.

Security updates will be cross merged into `release/7.x-2.0` on an as needed basis.
### New Clones

New clones will now default to the branch 7.x-2.x
### Existing Clones

Existing clones will need to clean up their local master branch. You can use the following commands:

``` bash
git fetch origin
git checkout -b 7.x-2.x origin/7.x-2.x
git branch -D master
git prune
```
### Questions?

Please ask in this thread. We're here to help!

**Comment by mstrelan** [comment]
What is the status of releases on Drupal.org? The latest published release is beta9, but I can see beta10 and 4 RCs on Github. The available updates page within Drupal instructs to "See the govCMS project page on drupal.org for further information about releases."

**Comment by fiasco** [comment]
A new policy on Drupal.org has prohbited us from packaging certain libraries we support and as such we currently aren't able to release to Drupal.org. 

There is however the https://github.com/fiasco/govcms-updater project which can update govCMS for you from github.
