### ISSUE TITLE
Automatically push successful TravisCI builds to Drupal.org

### ISSUE THREAD

**Issue by seanhamlin** [govCMS/GovCMS7#23]
Travis needs to be able to do this so things like simplytest.me continue to work with the latest code.

**Comment by aleayr** [comment]
What needs to be done to achieve this, or is this something we still need to do? Noting the two referenced issues are closed and merged already.

**Comment by teamglenny** [comment]
Is this good to be closed, @seanhamlin ?

**Comment by seanhamlin** [comment]
I think so, @fiasco can you confirm?

**Comment by fiasco** [comment]
Yup
