### ISSUE TITLE
Search API - Moderately Critical - Multiple Vulnerabilities - SA-CONTRIB-2016-022

### ISSUE THREAD

**Issue by fiasco** [govCMS/GovCMS7#234]
Advisory ID: DRUPAL-SA-CONTRIB-2016-022
Project: Search API (third-party module)
Version: 7.x
Date: 2016-April-20
Security risk: 11/25 ( Moderately Critical) AC:None/A:User/CI:Some/II:None/E:Theoretical/TD:Uncommon
Vulnerability: Information Disclosure, Cross Site Scripting, Access bypass

https://www.drupal.org/node/2710063 for more details.

**Comment by Feng-Shui** [comment]
Just about to create a pull request for this one, thanks for jumping on it.

**Comment by fiasco** [comment]
@Feng-Shui I also took the opportunity to bump the accompanying modules.

**Comment by Feng-Shui** [comment]
Yea, cool.
