### ISSUE TITLE
As an administrator I would like to use Google Site Search for govCMS

### ISSUE THREAD

**Issue by garthpowell** [govCMS/GovCMS7#236]
We have a requirement to integrate Google Site Search (GSS) into our govCMS website. This will replace the current Solr search. 

The issue we have with Solr is the lack of configuration. We were using a Google Search Appliance on our previous site and need to be able have similar functionality to that such as recommended results, crawl status and errors etc.

We do have the option to simply add the javascript and div container to make the call to the search index however a cleaner solution would be to add the following module to the distribution - https://www.drupal.org/project/gss 

Please advise as to how we can implement this.

**Comment by fiasco** [comment]
Hi @garthpowell, can you please provide some more detail around what Solr doesn't do that GSA will? ~~My initial thoughts are that we'd not want to support GSA purely given we already have a search preference for Solr.~~

govCMS has indicated it would be happy to support Google Search. Given govCMS uses Search API - perhaps this module would be a better fit? https://www.drupal.org/project/google_cse

**Comment by paulkilla** [comment]
I think broadening the sort of search implementations customers can choose from is in a good idea.

We always wanted to include funnelback and google as a minimum for our search requirements within govCMS.

Adding the label of good idea, we just need to look at the actual module and it's impact if any.

**Comment by garthpowell** [comment]
Thanks for this Paul.
As I am unfamiliar with the process for adding new modules, could you please clarify what next steps are?
Thanks
Garth

**Comment by invisigoth** [comment]
Hi @garthpowell just in case you'd like to consider the Solr option in the future, Solr comes with a "more like this" handler allowing you to build recommended results easily. Due to the way Solr is integrated into Drupal/GovCMS, if configured properly it will in most cases outperform GSS/GSA/Funnelback.

**Comment by paulkilla** [comment]
Hi @garthpowell to answer your question, we usually have an internal CAB meeting once a week. During this CAB we attempt to go over as many tickets as we can, which are then followed by a review of the functionality / modules to see how we go about implementing them.  This ticket will be updated as we go along.

What generally has a weigh in on these sort of requests is the interest in it... but at the same time we have always wanted to support a few major search providers that government uses (google, funnelback).  But at the same time we also support solr, search api etc.

**Comment by fiasco** [comment]
Its worth reading through the contribution documentation: https://github.com/govCMS/govCMS/wiki/Contributing-to-govCMS as well as our road map and release schedule: https://github.com/govCMS/govCMS/wiki/govCMS-Release-Schedule-and-Roadmap

**Comment by fiasco** [comment]
This feature is inline with the roadmap for govCMS - the next steps are to contribute a pull request for review.

**Comment by aleayr** [comment]
Pushed out to 2.4 at this stage, seeking a PR to move this forward.

**Comment by fiasco** [comment]
Still no PR, so will push out to 2.5

**Comment by Venkata-modgu** [comment]
Tested in PR - 341
Site admin able to enable the module and able to use google site search for the site.
Test passed.

**Comment by garthpowell** [comment]
Hi
This is great, can you advise as to when this module will be implemented into production?
Thanks
Garth

**Comment by aleayr** [comment]
Hi Garth,

Most likely around the 6th of October, but may be earlier depending on how testing goes.
