### ISSUE TITLE
As a content editor i would like to be able to use the "Source" WYSIWYG button so that I can alter the HTML source directly

### ISSUE THREAD

**Issue by kurtfoster** [govCMS/GovCMS7#238]
When you click on the Source button in the WYSIWYG, the source appears all on one line, rather than wrapping properly within the textarea.

**Comment by Feng-Shui** [comment]
We've recently added [CodeMirror](https://codemirror.net/) to our WYSIWYG and it's been a massive help for our content editors.  It replaces the default Source view, provides line numbers, syntax highlighting etc.

Happy to provide that code as a pull request if anyone's interested.

**Comment by Podgkin** [comment]
Codemirror is excelent, and it is the library behind mergely, which i previously suggested for content merging in #144

**Comment by garthpowell** [comment]
Hi
We are interested in this as well.

**Comment by fiasco** [comment]
We wouldn't want to support CodeMirror as a Drupal text format - would be too complex. But we could look at adding it as a formatter for the Source button in CKEditor: http://ckeditor.com/addon/codemirror

### Questions
- Should the source button be available for Filtered HTML?
- Should the source button be available for Full HTML?
- Show the source button be hidden/not available for certain types of users (content editors)?

**Comment by Feng-Shui** [comment]
Re the implementation, we've got it loaded as a CKEditor plugin, the Codemirror plugin is in our libraries folder.  You can then enable it per WYSIWYG profile.

```
/**
 * Implements hook_wysiwyg_plugin().
 */
function hook_wysiwyg_plugin($editor, $version) {

  $plugins = array();

  if ($editor == 'ckeditor') {

    $plugins['codemirror'] = array(
      'extensions' => array('codemirror' => t('CodeMirror')),
      'path'       => wysiwyg_get_path('ckeditor_plugins') . '/codemirror',
      'internal'   => FALSE,
      'load'       => TRUE,
    );

  }

  return $plugins;

}
```

**Comment by kurtfoster** [comment]
Re your questions:
I think only the Rich text Text Format should have the Source button by default.
Personally I think the text format perms are enough to control the available buttons, but some users may find this feature nice.

**Comment by Feng-Shui** [comment]
I think the source button should be available on any WYSIWYG HTML field (by default), reason being that you can get to the source by disabling the editor.  If someone wants access to the source, you really can't stop them, at that point, better to give them an editor that has some decent formatting in which case they're less likely to make errors.  The text formats will still give you protection against them throwing garbage in.

From what I've seen, editors that don't have the technical proficiency to edit HTML directly typically don't try, although happy to hear tales of woe on this one :)

As an aside, the Source plugin has to be enabled for the Codemirror plugin to have any effect. So it's not a replacement for the Source plugin.

**Comment by aleayr** [comment]
I tend to agree with @Feng-Shui, once they disable the editor, source is available for all. We have revisioning built in, so if people do make a mistake, it  can be rolled back easily.

**Comment by mgdhs** [comment]
This continues to be an issue for us.

**Comment by Chris820** [comment]
Regarding the original issue (Source code all appears on one line). We've gotten around it as follows:

Head into your WYSIWYG profiles. /admin/config/content/wysiwyg
Edit the relevant profile.
At the bottom of the page, within the Cleanup and output tab, ensure that **Apply simple source formatting** checkbox is checked.

![screenshot](https://cloud.githubusercontent.com/assets/4385022/22915661/e74991a4-f2cc-11e6-9237-a7e7937a9ab2.png)

This should make the source code view a little nicer, block tags get added onto new lines. .

I'm not sure if this is dependant on the version of the CKEditor Library being installed tho. Because we're on PaaS and are running a version that may be different to what comes within the govCMS distro (CKEditor 4.4.7.3a35b3d).
Hope it helps anyway.

**Comment by mgdhs** [comment]
Unfortunately that option is not available in Factory. But it is a great suggestion that gets us a good way there.

@aleayr what are our options for getting it turned on? Turned on in code via a PR or can someone do it in the UI for all or some sites?

**Comment by mgdhs** [comment]
For anyone else on D7 SaaS discovering this, you can submit a support ticket to get the option that @Chris820 mentions enabled. It is definitely an improvement.
