### ISSUE TITLE
As a site builder I want to use ajax components so that my website is more usable

### ISSUE THREAD

**Issue by gollyg** [govCMS/GovCMS7#242]
I am working with an agency at the moment that require a number of ajax features built into their site. 

The main use cases include:
- updating a filterable component containing supplementary material without reloading the entire page
- loading additional information about a specific node from a listing page to display in a modal
- creating configurable infinite scrolling pages

All of these use cases would be supported by the addition of:
- [services](http://drupal.org/project/services)
- [services_views](http://drupal.org/project/services_views)

to the codebase. This addition would also address #130 #223

**Comment by fiasco** [comment]
Service module is now in! This allows front ends to interact with govCMS using ajax components
