### ISSUE TITLE
Community Discussion Welcome

### ISSUE THREAD

**Issue by fiasco** [govCMS/GovCMS7#246]
As apart of our [release schedule and roadmap](https://github.com/govCMS/govCMS/wiki/govCMS-Release-Schedule-and-Roadmap) initiative, @aleayr and I are conducting regular triages of the govCMS issue queue. You may have seen the **[in-triage](https://github.com/govCMS/govCMS/labels/in-triage)** label on tickets - these are tickets we looking through and putting in the roadmap and release schedule where it makes sense.

When it makes sense, we allocate an issue to a milestone (release) we think is a reasonable timeframe for the issue to be completed in, if the community and maintainers can work together to get it done. We also put a [in-roadmap](https://github.com/govCMS/govCMS/issues?utf8=%E2%9C%93&q=+label%3Ain-roadmap) label on it. You can read more about the process on the [wiki](https://github.com/govCMS/govCMS/wiki/govCMS-Release-Schedule-and-Roadmap)

But what about issues that need more discussion? That haven't reached a point where it makes sense to add it to the roadmap nor exclude the issue from the roadmap? #220 is in this place right now.

How do we let the community know that we want more discussion before we can put it in the roadmap? What label should we use? Or should we just remain silent (as maintainers, i.e. don't label it) and continue to monitor the engagement?

Rather than figure this out ourselves, we welcome feedback and thoughts into how we could encourage and nurture the community to discuss and contribute great subject matter expertise (and code) to the govCMS project.

**Comment by gollyg** [comment]
I wonder if there is a role for the new https://govcmscommunity.discoursehosting.net/ forum in this area?

It has only been setup recently, but it seems to encourage more general discussion, and possibly would allow us to promote issues that are in this state.

**Comment by fiasco** [comment]
To me at least, it makes sense to deal with github governance where the github community is - in github. But it is a valid point that these types of conversations or perhaps more broader programme discussions will be hosted there.

**Comment by vanessaroarty** [comment]
A label for "being discussed" would be great and may prompt people to jump in. I would also encourage you to raise any issues that would benefit from broader discussion in the govCMS Community: https://govcmscommunity.discoursehosting.net/ - we had hoped that as it grows this community becomes a place where people from all disciplines (tech, project managers, analysts, designers, comms etc) can put their heads together on things. Happy to help with some of the cross-referring where appropriate.

**Comment by gavintapp** [comment]
I like the idea. "being discussed" is good, but I wonder if a label that invites the reader to add their own comment might be better? Something that avoids the suggestion that the discussion is happening elsewhere. Are there labels like this in use on other popular github projects - can we use one of them?

**Comment by fiasco** [comment]
Its a good point @gavintapp. Issue queues are all about community participation and discussion so in some ways, using a label to state what should be by default has a superfluous feeling to it. We absolutely want to avoid labels that could communicate an "us and them" vibe too.

Github labels are arbitrary. So we can absolute copy another github project if it makes sense. The challenge would be to find a community that successfully engages technical and non-technical people that we might be able to copy from.

Cross-referring to https://govcmscommunity.discoursehosting.net/ makes a lot of sense IMO. Using it as a channel to bring across non-technical perspectives into github discussions would be great (so long as they're not overwhelmed with technical details that can come up on github issues).

**Comment by Podgkin** [comment]
"needs discussion"?
