### ISSUE TITLE
Search 404 issues incorrect response header

### ISSUE THREAD

**Issue by steveworley** [govCMS/GovCMS7#249]
govCMS currently uses version 7.x-1.3 of [search404](http://drupal.org/project/search404). This should be updated to 1.4 to provide some additional functionality around how the search404 is delivered.

The search 404 page module incorrectly provides a 302 Temporarily moved instead of a 404 response status. This confuses search bots (such as Google, Bing) and may impact the link checker capability within govCMS.

Version 1.4 of the module allows you to render the search form on any page that 404s rather than redirecting.

**Comment by fiasco** [comment]
This makes sense to me, and I'd personally think its a small enough change to squeeze into our next release. But that will depend on if others feel the same way. Marking for 2.1 for now but is subject to change.
