### ISSUE TITLE
The favicon module is outdated

### ISSUE THREAD

**Issue by geek-boy** [govCMS/GovCMS7#252]
The [Favicon Module](https://www.drupal.org/project/favicon) for govcms is 1.0-rc2 but the recommended version is 7.x-2.1.

This module should be updated to the latest recommended release.

**Comment by pandaskii** [comment]
This module is going to be replaced with [Responsive Favicons](https://www.drupal.org/project/responsive_favicons) #31

**Comment by fiasco** [comment]
We won't be continuing the Favicon module in place of Responsive Favicons in #31.
