### ISSUE TITLE
Tags vocabulary contains sample data when not requested

### ISSUE THREAD

**Issue by TobyWild** [govCMS/GovCMS7#258]
During the installation I selected that I did not want any example content included on the website, however the Tags vocabulary contains 7 Latin terms.

Had raised this on Drupal.org, told to raise it here.
https://www.drupal.org/node/2733931

**Comment by fiasco** [comment]
Those sneaky latin terms! We'll have to fix that one!  (PR's welcome!)

**Comment by fiasco** [comment]
@TobyWild Are you able to test the PR and confirm the changes meet your needs?

**Comment by TobyWild** [comment]
Unfortunately I am now on a different project and don't have the spare time
to spin up a new GovCMS instance.

**Comment by aleayr** [comment]
As per PR #273, this needs testing confirmation, pushing to 2.5.

**Comment by pandaskii** [comment]
Closed as this has been resolved.
