### ISSUE TITLE
Upgrade Drupal core - SA-CORE-2016-002

### ISSUE THREAD

**Issue by fiasco** [govCMS/GovCMS7#266]
## Saving user accounts can sometimes grant the user all roles (User module - Drupal 7 - Moderately Critical)

A vulnerability exists in the User module, where if some specific contributed or custom code triggers a rebuild of the user profile form, a registered user can be granted all user roles on the site. This would typically result in the user gaining administrative access.

This issue is mitigated by the fact that it requires contributed or custom code that performs a form rebuild during submission of the user profile form.

**Comment by Feng-Shui** [comment]
@fiasco do we know if the distro is vulnerable to this based on any of the contrib modules it ships with?

**Comment by fiasco** [comment]
We don't at this stage. If you are concerned, the best option is to apply the patch. We'll be confirming the release of 2.3 later today or you can build govCMS from the 7.x-2.x branch which we consider stable.
