### ISSUE TITLE
Drupal 7.43 regression: When an anonymous user submits a form with an un-uploaded file that leads to a validation error, the file is lost on the next correct submission

### ISSUE THREAD

**Issue by pandaskii** [govCMS/GovCMS7#271]
Drupal 7.43 [Release notes](https://www.drupal.org/project/drupal/releases/7.43)
When an anonymous user submits a form with an un-uploaded file that leads to a validation error, the file is lost on the next correct submission

To reproduce using the Standard installation profile:
1. Allow anonymous users to create article nodes.
2. As an anonymous user, go to the node creation page. Leave the article title blank. Select a file for the Image field, but do not click "Upload".
3. Click "Save". There will be a validation error because the title was not filled out. If you scroll down to the Image field, you'll see that the file was uploaded.
4. Fill out the title and click "Save" again. The node will be saved, but the file you uploaded before will no longer be attached to it.

This effects current govCMS sites which allow anonymous user submits a form with attachment. We have to apply a hot fix patch regarding this issue - it is in [Drupal offical 7.x line](http://cgit.drupalcode.org/drupal/commit/?h=7.x&id=6b6bc1b7fd69de28c490c976101d255b3f79d409) but labeled as [7.50](https://www.drupal.org/node/2678822) release

**Comment by Feng-Shui** [comment]
Thanks for getting onto this so quickly and after hours.

**Comment by invisigoth** [comment]
Just to clarify, the file may still be uploaded to the server but the webform may fail to associate the uploaded file with the corresponding submission. This issue can be reproduced by either attaching a file to a form using the "Upload" button next to the file field; or submit the form with invalid inputs directly, which triggers a form validation error. 

Symptoms of this issue have been reported to us by govCMS users.

**Comment by fiasco** [comment]
@Feng-Shui if you can confirm the patch fixes the problem, we'll commit to HEAD so users can apply fix from source.

Do we need to roll this out for SaaS sooner than the 7.x-2.4 milestone? If so, we'll need to hotfix.

**Comment by pandaskii** [comment]
A local test to reproduce the steps from @invisigoth also suggested the file will be deleted after 6 hours. 

As we are facing loss data, it is better to apply a hotfix after testing.

**Comment by fiasco** [comment]
@jozhao still awaiting a test to verify the fix - if you can do that, I'll get this into govCMS head.

**Comment by pandaskii** [comment]
@fiasco I've tested the followings in my local environment
1. Fresh install govCMS site - 7.x-2.2, 7.x-2.3, 7.x-2.x with this patch - passed
2. Two existing govCMS sites - 7.x-2.2, 7.x-2.3, 7.x-2.x with this patch - passed

**Comment by fiasco** [comment]
Great, commited - thanks for the contribution!
