### ISSUE TITLE
Status of LDAP in govcms

### ISSUE THREAD

**Issue by simesy** [govCMS/GovCMS7#278]
I often  discuss LDAP requirements with government clients, and I'm wondering if LDAP support would ever be part of SAAS govCMS.

**Comment by Feng-Shui** [comment]
I've seen this implemented once in Government (non-govCMS Drupal).  Challenge is less about the LDAP/Drupal integration and more around having a web-accessible AD server.  Are you seeing this come up much, and come up having cleared the desk of the CIO/CTO?

**Comment by simesy** [comment]
These discussions are always pre-sales and rarely that specific. As it stands I don't have an educated view on the matter.

**Comment by aleayr** [comment]
Like @Feng-Shui says, the issue for us on the govCMS side is two fold.

Firstly, we've been asked for different implementations of AD, such as some customers proposing their directory to be synced in a certain manner, users and groups in AD corresponding to particular roles in Drupal/govCMS, and others asking for other implementations. At this stage, there isn't a single implementation of AD/LDAP we've come across that suits a majority of people across government.

The second issue is security. We've spoken with agencies before about AD/LDAP requirements, but on further investigation, the suggestion of a web accessible directory to bind to has put the brakes on further discussion.

As such, as this point, while I do see this as something I'd like to see support for in future, and there is work happening to make configuration more flexible in the SaaS environment, at this stage, it's probably not something that is really high on our priority list.

**Comment by aleayr** [comment]
Thanks for raising this @simesy though, keeps it front of mind for me :)

**Comment by fiasco** [comment]
As @aleayr  and @Feng-Shui point out, LDAP would be exposed on the internet. No government agency has come to us yet with that capability (I doubt the ISM really lets agencies do it).

A far more likely SSO strategy would be to support SAML, of which Active Directory has a federated plugin for. As a secure HTTP service, SAML is better positioned as a SSO solution for cross government authentication, in fact it already is used in New Zealand government for [realMe](https://www.realme.govt.nz/) (@nathan-w might be able to add some colour to that).

mygov might be worth a look too.

**Comment by stooit** [comment]
Something I've always thought _may_ be achievable is a SaaS version of the simpleSAMLphp module+library.

Using a SAML IDP/SP approach means it doesn't matter what the underlying auth technology is, though it does depend on the agency running their own identity provider (if they don't have one already). Many agencies I've talked to already have a SAML capable IDP in one form or another.
It would also require work on the existing `simplesamlphp_auth` module to allow for administering the SP metadata, but it wouldn't be insurmountable.

The security issue is largely redundant then, the SAML protocol doesn't require a public facing directory or direct network connectivity to/from the SaaS environment, and if a user tries to auth when not behind an appropriate network they simply wouldn't be able to, as expected.

**Comment by aleayr** [comment]
I think the problem with mygov as a federated login is that it is aimed at the personal taxpayer user, rather than a work user. Still keen to explore some sort of AD/LDAP/SAML option if there is a genuine payoff in terms of an agency (or multiple) to champion the implementation.

**Comment by nathan-w** [comment]
@fiasco NZ's common web platform had issues with LDAP particularly where agencies wanted to use the platform for intranet use. Implementing RealMe was certainly possible, and from memory a couple of the sites using the CWP did, the challenge was implementation was always a point-solution. An enterprise-scale solution was in the backlog but wasn't funded at the time I left. I still have contacts there and can setup a conversation if its of any use.

@aleayr RealMe has exactly the same issue - it can easily authenticate a person, but struggles to provide a role-based solution that maps your representation of an organisation. Again, believe this is a work in progress for them, but it's incredibly complex for some organisations like IRD (tax office).

**Comment by simesy** [comment]
Awesome info. I think it's fair to say LDAP is not supported on SAAS.

**Comment by aleayr** [comment]
Not currently, no :) Although, in future, would love to!

**Comment by nathan-w** [comment]
@aleayr @fiasco @teamglenny - lets discuss this with a view to getting it on the roadmap - a stronger need for this type of AD integration is emerging
