### ISSUE TITLE
"You have not selected anything!" in media browser when a file has been selected

### ISSUE THREAD

**Issue by rooby** [govCMS/GovCMS7#280]
Sometimes when using the media browser to select a file from the media library you get this error even though you have selected a file:

"You have not selected anything!"

There is an issue open for this in the media module at https://www.drupal.org/node/1743040 which has been fixed and should be in the beta2 release, so an upgrade to 7.x-2.0-beta2 should hopefully resolve this.

**Comment by stooit** [comment]
Hey @rooby, this one is already being tracked in #132

**Comment by rooby** [comment]
Happy to close this as a duplicate if that pull request will fix this issue.
