### ISSUE TITLE
Module and Core versions

### ISSUE THREAD

**Issue by TobyWild** [govCMS/GovCMS7#282]
Say I installed a GovCMS distro on my local dev machine two weeks ago and started work on the site.

And I see now that the .make file was updated 7 days ago.

So there has been an update to the make files list of modules and versions.

How do I get my Distro up to date to match the latest module/version lists without having to run up a new instance?
Especially for Core updates.

**Comment by fiasco** [comment]
Hey @TobyWild, There are a couple of ways you can do this:
- You can run official releases from https://www.drupal.org/project/govcms which can update the site for you.
- You can use https://github.com/fiasco/govcms-updater which can update based on a committish such as tag, branch or commit.

**Comment by TobyWild** [comment]
In my case, the Updater isn't a possibility, as I'm using Windows on my companies network, so I don't have permission to install Composer or run bat files.

I'm not sure I understand what you mean by "run official releases".
Do I need to re-download the Distro and copy it over my existing file structure?

**Comment by fiasco** [comment]
> Do I need to re-download the Distro and copy it over my existing file structure?

I wouldn't recommend that as it doesn't remove files removed from the release. You should be able to do something like this (you'll have to translate into Window lingo, sorry):

```
# Download and extract govcms to govcms-7.x-2.4
# Assuming existing site is called govcms
rm -rf govcms-7.x-2.4/sites
cp -a govcms/sites govcms-7.x-2.4/
mv govcms govcms.bak
mv govcms-7.x-2.4 govcms
```

This approach is essentially a swap out but retaining your settings.php configuration and files.

**Comment by aleayr** [comment]
@TobyWild With relation to official releases, @fiasco means fully built and released on Drupal.org ready to use. Pulling in from this repo requires an update or a build step before it can be used on a site.

**Comment by aleayr** [comment]
@TobyWild How'd you go with this? Anything we can clarify further, or can we close this off?

**Comment by TobyWild** [comment]
Hi,  I got moved to another project and haven't had a chance to confirm
this.  Might as well close it.
