### ISSUE TITLE
Missing dependency for Consultation module

### ISSUE THREAD

**Issue by nathan-w** [govCMS/GovCMS7#285]
As a developer experimenting with govCMS and the Acquia Dev Desktop
I needed to install UUID_Features separately after downloading and setting up the govCMS 7.x-2.4 distro from https://www.acquia.com/downloads 
So that the govcms_Consultation module would run without an error

**Comment by fiasco** [comment]
This seems like a massive bug. 
@aleayr the consultation module was tested right?
@srowlands can you comment on the above?

**Comment by fiasco** [comment]
Confirmed. Consultation module [requires UUID Features module](https://github.com/govCMS/govCMS/blob/7.x-2.x/modules/features/govcms_consultation/govcms_consultation.info#L26) even though its not in the distribution. This may have been used just to export the feature into code. So will need @srowlands to confirm if it can be removed.

**Comment by stooit** [comment]
Definitely a bug. The original PR (#150) had uuid_features in the make file, so it's been lost along the way.

**Comment by nathan-w** [comment]
@fiasco @aleayr I wouldn't say massive bug - backtracking where the make file dependency dropped off will be useful for reviewing our test/release processes though

**Comment by fiasco** [comment]
As it requires adding code to make it work, it means it won't work on the SaaS platform which is a bit of an issue. I've added a PR which also adds tests to ensure the module can be enabled/disabled and uninstalled.

**Comment by aleayr** [comment]
Was tested back in #150, #229 resubmission was where the dependency dropped off.

**Comment by fiasco** [comment]
Committed #286 to fix.
