### ISSUE TITLE
There is a error during request to Google Analytics Metadata API: Error opening socket ssl://www.googleapis.com:443

### ISSUE THREAD

**Issue by fiasco** [govCMS/GovCMS7#287]
When I installed govCMS I got this error message. I haven't done any investigation yet but wanted to track this here.

**Comment by aleayr** [comment]
Anyone else seen this problem?

**Comment by stooit** [comment]
This one is likely an environmental issue where the php ssl extension isn't in place. Check phpinfo(), you'd hope to see something like this:
`Registered Stream Socket Transports => tcp, udp, unix, udg, ssl, sslv3, tls`

**Comment by aleayr** [comment]
Closing this out, if more people see it and isn't related to the SSL extension, then please reopen.

**Comment by mstrelan** [comment]
I just installed govCMS via Acquia Dev Desktop with default php configuration and saw this message too.

PHP 5.5.33
`Registered Stream Socket Transports => tcp, udp, unix, udg, ssl, sslv3, sslv2, tls`

PHP 5.6.19
`Registered Stream Socket Transports => tcp, udp, unix, udg, ssl, sslv3, sslv2, tls, tlsv1.0, tlsv1.1, tlsv1.2`
