### ISSUE TITLE
Update the Shiny theme to the latest version

### ISSUE THREAD

**Issue by rooby** [govCMS/GovCMS7#288]
There are some good bug fixes in the latest version of the shiny theme (currently 7.x-1.7)

Most notably for me, it fixes an issue with field height in FireFox (see img):
![shiny-firefox_field_height](https://cloud.githubusercontent.com/assets/610162/16571256/e0e8c69a-429b-11e6-91b1-c330379d3c37.png)

**Comment by fiasco** [comment]
Yup, thats a no brainier. If you can provide a PR we'll accept it in.

**Comment by Feng-Shui** [comment]
@fiasco https://github.com/govCMS/govCMS/pull/318
