### ISSUE TITLE
No LICENSE.txt file for project

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#289]
As noticed on the [govCMS Community](https://community.govcms.gov.au/t/cost-on-own-server/237/2), we seem to be missing an easy-to-view license.txt file so people can tell at a glance what we're licensed under.

I'll lodge a PR shortly if someone doesn't beat me to it.

**Comment by fiasco** [comment]
You're right, its not obvious that we inherit the GPL license from Drupal: https://github.com/drupal/drupal/blob/7.x/LICENSE.txt

We could simply copy this license file into govCMS - there wouldn't be any harm in doing that.

**Comment by aleayr** [comment]
#291 has solved this.
