### ISSUE TITLE
Remove/repurpose build:remote

### ISSUE THREAD

**Issue by typhonius** [govCMS/GovCMS7#29]
The `build:remote` task has been replaced with `build:local` in #27. This issue is to decide:
1) Whether we need `build:remote`
2) How it should be implemented
3) To document/add changes to the README

**Comment by teamglenny** [comment]
Hi, @typhonius any action on this needed?

**Comment by typhonius** [comment]
@srowlands I think you had comments on this?

**Comment by teamglenny** [comment]
@srowlands anything further?

**Comment by stooit** [comment]
Nothing major, just some of the build.xml could be slightly cleaned up to remove some superfluous steps.

I think this issue can be closed and we can revisit later if required.

**Comment by aleayr** [comment]
Closing now, lets reopen if there are issues later to deal with.
