### ISSUE TITLE
As a content author, I'd like the Menu select box to be easier to navigate so I don't have to go to specsavers

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#292]
When a menu gets long and has many levels, selecting where to place new content items from the Menu Settings tab is in a very long select box.

The user experience of this is pretty bad, using double dashes (--) to indicate levels.

Would be better if that box was replaced by a twistie style navigation to make drilling directly to the place you want the content to appear, quick and painless.

**Comment by pandaskii** [comment]
There is a module called "bigmenu"  in govCMS distribution. Not sure it can meet the requirements 

http://drupal.org/project/bigmenu

**Comment by Chris820** [comment]
We use https://www.drupal.org/project/hierarchical_select on our PaaS govCMS sites to combat this issue.

**Comment by invisigoth** [comment]
+1 for hierarchical select 
thank you @Chris820!

**Comment by aleayr** [comment]
Merged, closing.
