### ISSUE TITLE
[META] Update to Drupal 7.50

### ISSUE THREAD

**Issue by fiasco** [govCMS/GovCMS7#295]
This is a meta ticket to track the merging Drupal 7.50 into govCMS. This update is rather large and has 2 key changes we need to address in govCMS:
### New "administer fields" permission added for trusted users

We need to check and modify the existing roles in govCMS to ensure Admin and Site Builder roles can continue to use the field UI as the have done in the past.
### Allow search engines access to CSS, JavaScript and image files

It is possible to write an upgrade hook in the distribution that attempts to update the robotstxt module configuration to insert this update into an existing sites robots.txt output so that govCMS sites can inherit this change.
### Advisory

In addition to the two above changes, there is an additional change in 7.50 that may break existing sites:
#### Drupal 7 core is now protected against clickjacking by default.

If a site is using the Security Kit module that already writes the X-Frame-Options header on its own, that setting will be automatically respected and Drupal core will not overwrite it. For all other sites, the X-Frame-Options header will be emitted and any uses of govCMS sites as embedded content will cease to work. However, once reported, the seckit module can be enabled and configured to allow specific domains to embed govCMS sites.

SaaS users will be able to file Support tickets to address this issue. All other uses of govCMS will need to address this themselves.

More Information: https://groups.drupal.org/node/512445
Community post about clickjacking: https://community.govcms.gov.au/t/updates-coming-to-govcms-that-may-break-your-site/248
### UTF8MB4 support

This essentially gives Drupal the ability to store 4 byte characters in the database. Emoji characters are typically the main reason why people want this supported, but sometimes extended Chinese characters are also needed.

**N.B.** By updating to 7.50 will not automatically grant you 4 byte character support, you also need MySQL configuration changes, settings.php changes and your database needs converting. More information can be found in the conversion tool https://www.drupal.org/project/utf8mb4_convert

**Comment by rooby** [comment]
This is great news. The administer fields permission means that site builder will now be able to access all the field UI pages.

I'd be happy to help out with whatever is necessary to get this through as quick as possible so let me know if I can assist in any way.

**Comment by fiasco** [comment]
Thanks @rooby! As you can see, we've targeted this change for the 7.x-2.6 release which is [scheduled](https://github.com/govCMS/govCMS/wiki/govCMS-Release-Schedule-and-Roadmap) for the for [28th of July](https://github.com/govCMS/govCMS/milestones).

In order for that to happen, we need 3 PRs:
- A PR to update the version of Drupal core to 7.50 in the [make file](https://github.com/govCMS/govCMS/blob/7.x-2.x/drupal-org-core.make). This is an easy one-liner PR.
- A PR to [modify the govcms_permissions module](https://github.com/govCMS/govCMS/blob/7.x-2.x/modules/custom/govcms_permissions/govcms_permissions.perms.inc) to correctly set the new "administer fields" permission to the site builder and administrator roles.
- A PR to add an update hook to [govcms.install](https://github.com/govCMS/govCMS/blob/7.x-2.x/govcms.install) to attempt an update to the `robotstxt` variable to insert the `Allow` rules that enable search crawlers to index js and css.

**Comment by rooby** [comment]
Cool. I can do that either today or tomorrow if no one else beats me to it.

**Comment by pandaskii** [comment]
@fiasco quick question, do we support 4 byte UTF-8?

**Comment by fiasco** [comment]
Thats dependent on the MySQL configuration (PostgreSQL and SQLite do out-of-the-box). For SaaS platform we do have a MySQL database that supports 4 byte UTF-8 but we've not looked into the changes needed at the application level to support that. An upgrade path would also need to be provided for existing customers.

**Comment by rooby** [comment]
In relation to the robots.txt change, I'm not sure it is possible to reliably add the new rules correctly for all possible configurations a site admin could have configured, however we could potentially make assumptions around what people would or would not have done.

It depends how much risk you want to accept.

An alternative could be to somehow notify the site admin that they have to add these new rules.

**Comment by Feng-Shui** [comment]
"An alternative could be to somehow notify the site admin that they have to add these new rules."

When I've needed to do this before, i.e. there's a code change and you need to let site admin/builders know about it (and you know that most people won't read release notes), I've used a few methods: 

1: a variable and a drupal message based off that.

```The most recent update of govCMS resulted in blah blah blah.

Click here to dismiss this message.```

Menu handler does a `variable_set('the_narly_issue_dismissed', TRUE);`

After a few months you remove this from the codebase.  You can also achieve the same thing through `hook_requirements();`.

2: email by hook_update().

Send an email to the site's email address in `hook_update()` detailing the change, this _should_ have been set to something sane by the site builder.

**Comment by seanhamlin** [comment]
Altered the main comment at the top to include UTF8mb4 information. I would be keen to understand if any agencies would like this supported in the future on their SaaS sites.

**Comment by aleayr** [comment]
Merged, closing.
