### ISSUE TITLE
PSA-2016-001: Is govCMS vulnerable?

### ISSUE THREAD

**Issue by fiasco** [govCMS/GovCMS7#299]
Today the Drupal Security Team announced two highly critical vulnerabilities in contrib:
- [RestWS](https://www.drupal.org/node/2765567) is a web services modules similar to the [Services](https://www.drupal.org/project/services) module we use in govCMS.
- [Coder](https://www.drupal.org/node/2765575) is a coding standards checker

Neither of these modules reside in the govCMS distribution. User's of govCMS in SaaS are not impacted by these vulnerabilities. If you are on PaaS or external hosting you should check your distribution in case your developers have added these modules.

**Comment by Feng-Shui** [comment]
Coder is included in the phing build scripts, but is not in the docroot.

https://github.com/govCMS/govCMS/search?utf8=%E2%9C%93&q=coder

**Comment by Feng-Shui** [comment]
But this will pull in the latest version now, so there's nothing to patch anyway.

**Comment by fiasco** [comment]
And even if it didn't, it would reside in the docroot, accessible to the web.
