### ISSUE TITLE
A pipe separator appears in html title tag on govCMS site front page

### ISSUE THREAD

**Issue by pandaskii** [govCMS/GovCMS7#303]
A pipe separator appears in html title tag on govCMS site front page - this is happened after new govCMS release

After investigation, this is from a module - metatag's default settings.

**Comment by Feng-Shui** [comment]
https://github.com/govCMS/govCMS/pull/316 resolves this issue, test to verify the issue and then the fix.

**Comment by fiasco** [comment]
Merged #316 which addresses the issue in future releases but need to look at whether this is still an issue for existing sites.

**Comment by fribibb** [comment]
Using https://gist.github.com/fribibb/e0844a0dc53bb474f122895308a865ab and running:
`casperjs all-sites-check.js | grep "|$"`
the following 18, live govCMS sites have a trailing `|` in the `<title>` tag:
- Tax Practitioners Board
- ATO Beta
- Australian Training Awards
- Unique Student Identifier
- Australian Apprenticeships
- Professional Standards Board
- Shared Services Centre
- Department of Employment - Strategic Plan 2014
- Department of Employment
- IP Australia
- Australian Sports Anti-doping Authority - ASADA
- Office of National Assessments
- Commonwealth Director of Public Prosecutions (CDPP)
- Office of the Registrar of Indigenous Corporations
- Victorian Budget 2016/17
- Election Costings 2016
- ATO Annual Report 2014-15
- Australian National Audit Office

I'll script up something to check and fix all existing sites - so it will fix live as well as offline sites in blue/green environments.

**Comment by marblegravy** [comment]
Just coming in to this issue seeing a bunch of the sites we look after in the list above - what's the issue with the pipe separator?
Is it just concerns over how some screen readers read out the pipe as "vertical line"?

**Comment by aleayr** [comment]
It's a bug introduced on the homepage of sites in a previous release where the site title will be trailed by a pipe character even though there isn't a second textual component.

Eg, front page title of ANAO is: "Australian National Audit Office |" -> should be "Australian National Audit Office"

**Comment by aleayr** [comment]
I should note there isn't anything wrong with the sites operationally, it's just an aesthetics bug we'd like to fix up.

**Comment by aleayr** [comment]
Was this resolved @govCMS/osb-devs?

I know @courdo1 and/or @fribibb were looking into this.

**Comment by fribibb** [comment]
No sorry @aleayr, both @courdo1 and I have been pulled onto other things. I'll try and make some time next week for this.

**Comment by aleayr** [comment]
Confirmation from a number of people at govCMS Camp that this has been resolved.

Might have some existing sites that need tweaks, and will deal on a case-by-case basis.

**Comment by Feng-Shui** [comment]
@aleayr yes, any existing site that was installed in the period between the Meta Tags module being updated and the PR going in would need a config tweak to fix this.
