### ISSUE TITLE
Quoted Phrases searching not working

### ISSUE THREAD

**Issue by pandaskii** [govCMS/GovCMS7#304]
all govCMS sites except Ageing and Aged Care https://agedcare.health.gov.au/search/content/%22aged%20care%22 , Quoted Phrases searching not working

Rather than the expected behaviour of searching for the string of concurrent words "some keywords", which definitely occurs many times across the site, the site search finds nothing.

For example, Flight crew on casa.gov.au
1. The search found 689 results with keywords flight crew
2. No results with keywords "flight crew"

**Comment by invisigoth** [comment]
This has been reported by FWBC as well.

**Comment by Podgkin** [comment]
It isn't just quoted phrases, most lucene query term modifiers seem to be inconsistent or non-existent.   wildcard search works, but fuzzy matching, boolean, proximity, range, boost and grouping all seem to not function as per spec.

https://lucene.apache.org/core/2_9_4/queryparsersyntax.html
