### ISSUE TITLE
Profile testing files missing/out of date

### ISSUE THREAD

**Issue by Feng-Shui** [govCMS/GovCMS7#307]
Morning all,

I'm working on some test coverage for the consultation module, and was going to add the new consultation node type to the profile's basic test coverage.  However, the test files to not exist in the profile directory (not copied in as part of the build process), and when copied in manually, they don't run anyway because they appear out of date.

The files are:

```
build/tests/govcms_test_base.inc
build/tests/govcms.test
```

They are referenced in the profiles info file

```
files[] = tests/govcms_test_base.inc
files[] = tests/govcms.test
files[] = tests/govcms_metadata.test
```

Note that `tests/govcms_metadata.test` is missing completely.

When copied in manually and run, the tests batch fails with fatal errors `Call to undefined function govcms_supported_themes()` and the content type features referenced in the `setUp()` don't appear to exist in govCMS anymore.

If this was an intentional change I'll open a PR to remove these, if not we should get these up to date - or have we replaced them with behat testing now?

**Comment by fiasco** [comment]
Nice catch @Feng-Shui - thats using Drupal's simpletest framework which we've never used on the govCMS project. These are probably just artifacts left over from the aGov fork.

Our test suite today uses phing and behat and only checks for security updates and runs exclusively behat tests:

`/build/phing/build.xml`

``` xml
 <target name="test:all" description="Runs all tests against govCMS."
            depends="test:security-updates, test:behat"/>
```

As for this issue - happy to merge a PR that cleans this up. Remove the info in the .info file and remove the files from build/tests that are no longer needed.

Definitely keen to have tests contributed but we do want them in behat format. Checkout `build/tests/behat/features/` for some examples.

**Comment by Feng-Shui** [comment]
Cool, I'll PR that out of there.

I'm writing some behat test coverage now, but I also have some unit tests (simpletest) to nail some functions in the consultation module - to help with the work I'm doing.

Do we have a unit testing preference at all? I note that we've currently got none, as you also point out.  Is our preference to test functions implicitly through behat functional tests? This works but it's a slow way to run unit test.

I'm going to commit these tests anyway, there's no point in throwing them away, and there's no need to have them included in the automatic testing process.  But is there any appetite to use unit testing (simpletest), or brining in PHP Unit support?

**Comment by fiasco** [comment]
stemming from Drupal core conversations, unit testing in Drupal 7 has many limitations due to its extensive use of procedural code. As this severely inhibits the what you can test, simpletest adoption really struggled. Behat has certainly been much better with that by nowhere near the speed Drupal 8 can test at thanks to the use of PHPUnit and OOP.

So I'm hesitant to want to support SimpleTests as I've seen the issue it created in the core community. Behat on the other hand, while slower, is a better natural documenter that aligns more with the community of govCMS (IMO).
