### ISSUE TITLE
PHP 7 support

### ISSUE THREAD

**Issue by mstrelan** [govCMS/GovCMS7#309]
In general GovCMS seems to run ok in PHP 7 however I'm expecting there to be a number of issues that need to be resolved in contrib and then in GovCMS. One issue is features exports stripping out field_group machine names. This has been fixed in the dev branch of field_group (see https://www.drupal.org/node/2649648). Is it worth submitting PRs for this or is PHP 7 unlikely to be supported?

**Comment by fiasco** [comment]
govCMS SaaS and PaaS offerings are hosted on Acquia which do not currently provide PHP 7 as an optional runtime environment. So demand for PHP 7 support has been non-existant (till now).

PHP 5.6 will come end of life and Acquia will eventually support PHP 7 and announce a EOL date for PHP 5.6 on the platform. At that point, govCMS would definately take PHP 7 support as a priority. It may even do so when PHP 7 becomes supported on Acquia.

So in my view, the only reason govCMS wouldn't support PHP 7 is if we moved to Drupal 8 before PHP 5.6 was EOL, but I'd say thats fairly unlikely as there is a growing number of sites on govCMS 7.x-2.x that need to also be ported before then too.

Its worth submitting PRs to update custom code and contrib modules to support PHP 7. Its also worth tracking modules that we use that require work. However, its not _yet_ worth tracking patches in govCMS to make contrib modules PHP 7 supported.

**Comment by mstrelan** [comment]
I think most issues should be solved by #327, #331 and #342.

**Comment by aleayr** [comment]
Thanks for taking a look into this @mstrelan 

I'd definitely like to get ahead of the game if possible and it doesn't break existing 5.x compatibility, so this is a good suggestion.

**Comment by aleayr** [comment]
Thanks @mstrelan 

Looks like all of those issues have now been merged, so I'll mark this issue as resolved. If people have other PHP7 issues, please reopen this or submit a new issue.

**Comment by mstrelan** [comment]
The link for Field Group in the OP is still an issue, and fairly major as it breaks feature exports. Sorry forgot about that one in my earlier comment. Unfortunately no stable release including that commit yet.
