### ISSUE TITLE
Replace iconomist and favicon with responsive_favicons

### ISSUE THREAD

**Issue by typhonius** [govCMS/GovCMS7#31]
The iconomist and favicon modules could be replaced with [responsive_favicons](https://www.drupal.org/project/responsive_favicons). This will allow us to reduce the module footprint of govCMS whilst also increasing functionality.

This patch will need to:
- Add responsive favicons to the make file
- Add an update hook to a govCMS module (probably tweaks but perhaps the profile) to port any settings on sites which have these modules enabled.
- Disable and uninstall those modules
- Perhaps disable those modules from being enabled (hook_paranoia_disable_modules())?

We'll also need a follow-up patch for removal of those modules from the make file.

Patches welcome

**Comment by fiasco** [comment]
Seems like a good idea, can we get a pull request for it?

**Comment by aleayr** [comment]
As part of testing and merging this in, we need to consider how this will effect (and how we test) the change on existing sites.

**Comment by fiasco** [comment]
@aleayr agreed, but we need to do that with a pull request provided ;)

**Comment by fiasco** [comment]
@typhonius we're keen to see this in govCMS but we need some help:
1. we need to reroll the PR
2. we need instructions for how an agency can test this change

**Comment by typhonius** [comment]
I've addressed this in #247. An agency should undergo the following steps:
- Patch govCMS codebase to include change
- Run update
- Ensure favicon and iconomist modules are disabled, uninstalled and unable to be reinstalled
- Ensure that responsive_favicon module is enabled if favicon module was enabled prior.

**Comment by aleayr** [comment]
@Venkata-modgu Can we get this tested #247 for merging?

**Comment by aleayr** [comment]
Due to complexities in modifying existing customer sites, and depecating this, I'm closing.
