### ISSUE TITLE
New drafts cannot be scheduled for publication

### ISSUE THREAD

**Issue by dylan-oxide** [govCMS/GovCMS7#312]
We have found that once a node has been published, a new draft of that node cannot be scheduled to be published. The fields are disabled and a message is displayed "A scheduled publish date may not be set because this content item already has a published revision." 

[Workbench Scheduler](https://www.drupal.org/project/workbench_scheduler) seems to be an appropriate solution for this problem. The Scheduler Workbench Integration module that is included only seems to set a workflow state with a scheduled publish or unpublish.

The only reason I think this is a necessary addition is that it seems a little incomplete to include a scheduler that cannot schedule publication of new drafts if workbench moderation is included.

Let me know if this is something that might be included in future releases.

**Comment by Podgkin** [comment]
We have also encountered this problem.

 The use case we have is that we regularly do bulk updates of industry guidance material, which is then published over staggered release dates to avoid overwhelming industry with large quanities of simultaneous changes.  These updates are usually to existing nodes, and the release dates are not uniform.  Currently we have an offline manual publishing schedule,  improving the scheduler would let us automate these processes.   

The scheduler incompatibility gets worse when you implement custom workbench moderation states to support a content approval processes, as the current scheduler just bypasses those approval states.  Workbench Scheduler would allow us to schedule content for approval and have automated review timeframes.  

We have investigated using rules to set up content state change scheduling, but it ends up being a very complex rule set that requires manual maintenance to accomodate any future changes to the workflow or publishing times, and it is a complex manual solution to accomplish something that is better handled by a module.

**Comment by fiasco** [comment]
I like the idea of using Workbench Scheduler as the problem defined here seems like a very common scenario of government agencies. To that extent, it sounds like an attractive enhancement for govCMS.

However, as the functionality is quite specific in nature, this module would not get into govCMS unless there were behat regression tests that accompanied the contribution that showed the module could be used to solve the problem outlined.

**Comment by andrew-mel** [comment]
We have the same issue. I am wondering if there is any update.

**Comment by fiasco** [comment]
To progress this issue, we need a PR contributed from the community which should contain behat tests that verify workbench scheduler working correctly.

**Comment by Venkata-modgu** [comment]
User able to schedule publishing a  new draft of published content.
Test passed.

**Comment by aleayr** [comment]
Merged, closing.
