### ISSUE TITLE
Updating composer dependencies

### ISSUE THREAD

**Issue by Feng-Shui** [govCMS/GovCMS7#317]
Evening all,

Running `composer update` at the moment results in a number of dependences being updated. `composer.json` doesn't look like it's been meaningfully updated since it's original commit in Sept 2014.

Is there a process that we follow to keep to the build tooling updated?

I'd also love to see the govCMS assets in the repo root moved into a govCMS folder.  It gets pretty noisy in there when you start adding things like vagrant and your own tooling.

The reason I ask is because I have a PR for https://github.com/govCMS/govCMS/issues/238 but can't get the project to build successfully on drupalvm.  Ran `composer update` and noticed the diff for `composer.lock` was pretty big - 250+ lines.

```
Script PhantomInstaller\Installer::installPhantomJS handling the post-update-cmd event terminated with an exception`

  [ErrorException]                                                                    
  copy(/var/www/drupalvm/build/bin/phantomjs): failed to open stream: Text file busy  
```

**Comment by fiasco** [comment]
Looking at the history of `composer.lock` it looks like it was committed by mistake. @gollyg can you confirm? If so we should remove it which should resolve this issue I think.

**Comment by Feng-Shui** [comment]
`composer.lock` should be in the repo to force the installation of exact versions of the packages we're using.  I guess my concern is that a `composer update` reveals that our lock file is getting pretty out of date as packages have been updated.

**Comment by fiasco** [comment]
As far as executable code goes, composer doesn't contribute to the make up of govCMS itself, just the supporting framework that compiles and tests it.

So while there is lower risk in removing composer.lock, we don't really have active maintainers of the build infrastructure for govCMS. If someone could pick up that mantle, then we could definately get composer.lock updated. Keeping in mind it may also require updating our build framework.

**Comment by Feng-Shui** [comment]
> we don't really have active maintainers of the build infrastructure for govCMS

So who's "owns" the build infrastructure in that case? I assume we're using the Open Source tier on Travis CI and there's passwords and accounts for that kind of stuff. Is that Finance's account?

**Comment by fiasco** [comment]
@srowlands built the govcms testbot which is hosted on a server sponsored by Acquia. We removed travisCI support as the open source builds often failed due to timeouts. @srowlands also built the govcms-devkit. @gollyg, @typhonius and myself built a lot of the original phing build scripts which were derived from PNX work in agov.

**Comment by typhonius** [comment]
Just chiming in here. I agree we need to keep the lock file committed so everyone building from scratch has the same packages. Perhaps what @Feng-Shui could help me to understand though is why the packages need to be updated. If there aren't additional features that we need in the build, perhaps it should remain stable.

If updating a composer package fixes #238 however then absolutely we'd want to update that package and commit that difference in the composer.json and composer.lock files.

**Comment by Feng-Shui** [comment]
Thanks for the info @fiasco, I'm still trying to get my head around who does what, who manages what etc.  I’ll see if I can figure out what specifically is giving me this build failure.

**Comment by pandaskii** [comment]
> Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.

Got this warning message when trying

```
composer install --prefer-dist --working-dir=build
```

Problem 1
- Installation request for d11wtq/boris v1.0.10 -> satisfiable by d11wtq/boris[v1.0.10].
- d11wtq/boris v1.0.10 requires ext-pcntl \* -> the requested PHP extension pcntl is missing from your system.

Problem 2
- d11wtq/boris v1.0.10 requires ext-pcntl \* -> the requested PHP extension pcntl is missing from your system.
- drush/drush 7.0.0-rc2 requires d11wtq/boris ~1.0 -> satisfiable by d11wtq/boris[v1.0.10].
- Installation request for drush/drush 7.0.0-rc2 -> satisfiable by drush/drush[7.0.0-rc2].

**Comment by pandaskii** [comment]
> Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

One more outdated package

**Comment by aleayr** [comment]
Thanks @jozhao - Let's investigate this with an upcoming govCMS sprint if their isn't a PR from the community by then. I'd like to simplify the developer experience as we discussed in the last sprint.
