### ISSUE TITLE
Request to enable google analytics when enabling the consultation feature

### ISSUE THREAD

**Issue by pandaskii** [govCMS/GovCMS7#321]
"When I am enabling the consultation feature system displaying request to enable google analytics. "

![snip20160811_5](https://cloud.githubusercontent.com/assets/1326673/17579703/25d36150-5fdb-11e6-9dd1-ed1ff4f29306.png)

This is from module "google_analytics_reports". 

"google_analytics_reports_api" is a sub module of "google_analytics_reports" and is required by "google_analytics_reports"

It seems that the update path of module "google_analytics_reports" from 1.\* to 3.\* does not cover this required module - "google_analytics_reports_api". In another word, for an existing govCMS site with this module enabled before. "google_analytics_reports_api" is not enabled after govCMS new release.

**Comment by Feng-Shui** [comment]
I was just ran into this, got fatal errors due to `Base table or view not found: 1146 Table 'drupal.google_analytics_reports_fields' doesn't exist'`.  This only become an issue after I cleared the cache.  In order to get things running again:
1. `drush dis google_analytics_reports`
2. `drush pm-uninstall google_analytics_reports`
3. `drush en google_analytics_reports`

Getting the module reinstalled so the table is created worked in this instance, but that obviously nuked any data.

**Comment by fiasco** [comment]
Shouldn't this have worked?: 

```
drush en google_analytics_reports_api -y
```

I would image the fix here should be:
- Ensure `google_analytics_reports_api` is made a dependency in `govcms.info`
- Provide an update hook in `govcms_install` to enable `google_analytics_reports_api`

**Comment by Feng-Shui** [comment]
I can test this again today, but from memory running `drush en google_analytics_reports_api -y` results in the table not found error.

**Comment by pandaskii** [comment]
Two more issues on google_analytics_reports upgrade path:
- google_analytics_reports 1.x dependencies[] = chart has been removed in 3.x do we want to remove the module "chart" from govCMS distribution?
- need a method for 1.x variables - google_analytics_reports_hd, google_analytics_reports_oauth_token, google_analytics_reports_oauth_token_secret, google_analytics_reports_profile_id and google_analytics_reports_cache_length

**Comment by fiasco** [comment]
Chart maybe in use by adopters of govCMS. To that end, removing it would be a breaking change. This is the reason we've not dropped iconomist yet.

Introducing breaking changes, IMO, should be done through major version release (7.x-3.x)

> need a method for 1.x variables 

Can you expand on this?
