### ISSUE TITLE
Revert PR #270 - linkit_panel_pages

### ISSUE THREAD

**Issue by pandaskii** [govCMS/GovCMS7#329]
Module linkit_panel_pages 2.0 is not compatible with the module linkit 3.x in govCMS

https://github.com/govCMS/govCMS/pull/270

**Comment by fiasco** [comment]
@jozhao can you please provide a summary or evidence to support this?

**Comment by pandaskii** [comment]
class LinkitPlugin used in linkit_panel_pages 2.0 is removed in linkit 3.x 

http://cgit.drupalcode.org/linkit_panel_pages/tree/plugins/linkit_plugins/linkt_panel_pages.class.php?h=7.x-2.x

@Venkata-modgu may have more details as he did the testing.

**Comment by fiasco** [comment]
Rather than removing linkit_panel_pages can we fix this issue instead?

**Comment by pandaskii** [comment]
A patch for this issue is available on Drupal community https://www.drupal.org/node/2405963

Needs codes review and testing (may take a while)

For the sake of platform stability and govCMS release cycle, I would like to suggest that removing this module temporally from next release to production sites, then add it back after codes review and testing positive

**Comment by aleayr** [comment]
@jozhao Can you confirm whether this is still an issue?
