### ISSUE TITLE
Twitter Block module cannot be uninstalled

### ISSUE THREAD

**Issue by pandaskii** [govCMS/GovCMS7#334]
Twitter Block module https://www.drupal.org/project/twitter_block

A PHP Fatal error: Call to undefined function twitter_block_clear_js_cache() 

profiles/govcms/modules/contrib/twitter_block/twitter_block.install on line 77

```
function twitter_block_uninstall() {
  // Remove blocks.
  db_delete('block')
    ->condition('module', 'twitter_block')
    ->execute();
  db_delete('block_role')
    ->condition('module', 'twitter_block')
    ->execute();

  // Remove variables.
  variable_del('twitter_block_cache');
  variable_del('twitter_block_last_cache');

  // Remove the cache directory.
  twitter_block_clear_js_cache(); 

  // Clear the site cache.
  cache_clear_all();
}
```

**Comment by Venkata-modgu** [comment]
User able to uninstall Twitter block module without any errors.
twitter_block module updated to 7.x-2.3.
Test passed.
