### ISSUE TITLE
Install govcms error displayed when accessing the PR environment.

### ISSUE THREAD

**Issue by Venkata-modgu** [govCMS/GovCMS7#345]
Install govcms error displayed when accessing the PR environment.
Here is the screenshot. 

[![PR load error.jpg](https://s11.postimg.org/o4fr1bn9v/PR_load_error.jpg)](https://postimg.org/image/mcms6f3wv/)

**Comment by aleayr** [comment]
@govCMS/osb-devs Can someone take a look into this and see if it is still an issue and confirm?

**Comment by seanhamlin** [comment]
The PR environment should be built (i.e. fully installed) prior to you visiting the URL. If you see that screenshot the build failed, there is no point testing it. Closing.
