### ISSUE TITLE
As a site builder, I would like the option to have external links open in a new window

### ISSUE THREAD

**Issue by rooby** [govCMS/GovCMS7#363]
As a site builder, I would like the option to have external links open in a new window

Could we include the https://www.drupal.org/project/extlink module?

It's pretty much plug and play.

**Comment by mgdhs** [comment]
You already can, it is just a touch hidden. 

<img width="200" alt="linking2" src="https://cloud.githubusercontent.com/assets/13895751/18620557/5a566e90-7e58-11e6-91f4-8106021ad259.png">

The module you've listed _identifies_ links to the end user. You could do this through your own theme CSS or JS.

I would however caution against using too many 'new window' links. I can send you a copy of our policy if you are interested.

**Comment by rooby** [comment]
Yes but that is per link, which is more overhead when administering content.

Yeah the policy would be interesting if you have it on hand, thanks.

**Comment by mgdhs** [comment]
```
jQuery(function(){
  jQuery('a').filter(function(){
    return !Drupal.googleanalytics.isInternal(jQuery(this).prop('href'));
  }).attr('target', '_blank').addClass('link-external');
});
```

Are you in the community? I can post it there after I check it is OK.

**Comment by Chris820** [comment]
Why not leave it to the user to decide if they wish to open links in a new window? 
As a site user I would prefer to retain control over my own windows and tabs.

I don't mind the idea of including a little indicator along with external links tho.

**Comment by dman-coders** [comment]
At the risk of sounding like an accessibility wank...

Doing this unilaterally, by default, is often user-hostile.
The 'feature' is frequently requested by brand managers who don't want the user to "leave their site". It's often assumed by graphic designers who don't want to "lose their audience" on the site, and I argue with them monthly.

It is almost never requested by the content audience.

Or from genuine user testing - in fact, user-testing brings this decision/quirk up as a fail most often.

Assumptions about audience retention have more weight if you were a click-through-driven ad-revenue-generating site. Our public-sector work is less about that, and more about assisting people (often less-tech-savvy) find the information they need, and finishing their transaction.

As such, some revenue-driven 'SEO' techniques _do not apply_ to public sector works.

MOBILE-driven issues have also changed this landscape. I can point at my mothers IPads hundred "open windows" and the "Breaking of the back button" that this tendency produces.
As a Techie, I am comfortable with tab management ... This is not the case for my sites target audience. So I accept that.

The accessibility guidelines we follow start with the "Web Content Accessibility Guidelines" - 
https://www.w3.org/TR/WCAG20-TECHS/G200.html
https://www.w3.org/TR/WCAG20-TECHS/G201.html

These do not prohibit new windows, but ask that you think if they are truly necessary for the completion of the users task.

I'll allow that it's OK if the content editor has deliberately chosen to do so (and the link editor supports that). After the content editor has undergone accessibility training.
There are situations where this works, and is the correct response (Twitter, Facebook etc) and you would be losing context of what you were doing. This is not the case in a click-driven browse or search of 'leaf' content pages that make up most public-sector sites.

When someone is bouncing between different government departments offering answers - getting to the answer in the right host is often the most important goal, and keeping an open window for where they came from in the background is - ultimately - not useful for them.

_disclaimer_ this is just "content editing for the web" _advice_ and not a rule, but I'm offering it as why accessibility mavens pull faces at the idea of "open every link in a new tab without asking" requests.
If you spend time in an accessibility seminar and watch a blind user really struggle with your navigation choices, you'll see why these guidelines exist.

It's OK to _ask_ that all external links open in a new window. I'm just offering background reasons why it's been decided against. As an accessibility policy.

**Comment by dman-coders** [comment]
(Also) Extlink module, when used judiciously to provide the visual indicator and confirmation does do a good job of addressing these concerns - so is a fine candidate for inclusion. We use it a lot.

My rant was about the headline more than the constructive suggestion ;-)

**Comment by aleayr** [comment]
From my own user testing I've conducted, opening links in external windows often confuses users who don't understand tabs/windows, and wonder why the back button doesn't work anymore.

As such, given that we have a mechanism to allow links to be opened on a per-link basis, I'm hesitant to include a feature that does have dubious usability value.

JavaScript at the theme level could achieve the same result without govCMS endorsing this as a potential approach if it definitively needed to happen.

As for Extlink itself, I'm not opposed to the visual indicator, but looking for more people to advocate one way or the other. Should it be there but on or off by default? Should we leave this sort of thing to the theme/JavaScript layer?

**Comment by aleayr** [comment]
Having discussed this, I think we'll close this out. Site Builders can implement the JavaScript option if they need to enable this feature.
