### ISSUE TITLE
OpenTags module

### ISSUE THREAD

**Issue by yangli0516** [govCMS/GovCMS7#37]
Hi all

We’ve recently submitted the [OpenTags module](https://www.drupal.org/sandbox/yangli0516/2536148) for approval.
It’s intended to work with govCMS, to improve the metadata tagging experience for end users.

Hoping that some of you might give us a hand by [reviewing it](https://www.drupal.org/node/2537434) to help move us through the approval process.

Thanks
Yang (Systemik Solutions)

**Comment by fiasco** [comment]
Looks like you guys to through the approval process fine. Congrats and closing!
