### ISSUE TITLE
spamspan - how to permanently disable module due to abnormal performance

### ISSUE THREAD

**Issue by therobyouknow** [govCMS/GovCMS7#372]
I don't require spamspan but cannot disable it permanently. When I disable it, after cron runs, I find it to be enabled again.

I am not sure why the module is re-enabled. Can you advise, please?

My inconclusive investigation so far as to why auto-enabling of spamspan occurred:
1) I thought perhaps a Features dependency caused it to re-enable, but I couldn't be sure - search showed up test code in the profile folder but so far I'm not sure.

2) I identified a function module_enable in Drupal core "module" module. So I put a xdebug breakpoint on this and ran cron, but the breakpoint was not hit. I was hoping that it would get hit and I could inspect the stack trace to see "who" was enabling it. I may need to do further runs to confirm this initial outcome, but at the moment I find it unexpected and perhaps disappointing as it suggests that there is more than one programatic way to enable modules in Drupal which complicates this investigation and is perhaps generally not the best design to have multiple places for this.

Why disable spamspan
The reason for wanting this module permanently disabled is because when I attempt to add "Promotion" content - node/add/footer-teaser the page never loads with the module enabled. But with the module disabled, the add content page loads. Moreover performance tools identify the module as shown to be using a higher than usual amount of server resources.

**Comment by pandaskii** [comment]
@therobyouknow any inline SVG in the content?

This module is required by govCMS distribution so it cannot be disabled. Every cron job the dependencies are checked and re-enabled. And you can find the dependencies list from "govcms.info" file

However, this filter can be disabled from "Text formats" or you can add a new text format for this content type

![screen shot 2016-10-20 at 11 37 40](https://cloud.githubusercontent.com/assets/1326673/19542406/a572a668-96b9-11e6-9907-3b74087688a5.png)

**Comment by therobyouknow** [comment]
This works, thank you:  I went to admin/config/content/formats/rich_text and unchecked/unticked the box next to "SpamSpan email address encoding filter" so that it was not enabled.

The page node/add/footer-teaser now loads.

Solved - closing ticket. Thank you.

By the way, I haven't seen any SVG used on the page.
