### ISSUE TITLE
As a content admin, I want to insert an image into a page that uses a relative URL so browsers do not identify the images as cross domain errors

### ISSUE THREAD

**Issue by mpigott** [govCMS/GovCMS7#374]
**Currently when we add images from the Media Gallery, the image uses an absolute URL, which is not good.** 

In our instance of GovCMS, I insert an image into the page using the Media Gallery button. I do this from our govcms.acsitefactory.com link. My browser is Firefox. 

I published the page and look at the page in Internet Explorer using the beta domain name. The image is not appearing. 

I checked the source and I notice the image is using the absolute URL of the govcms.acsitefactory link, which is a site that has not been added to the SSL certificate. 

This is really annoying. Is this a setting that I need to change or is this expected behaviour when inserting images from the Media Gallery.

**Comment by Podgkin** [comment]
Have you looked into configuring pathologic? 

https://www.drupal.org/project/pathologic

**Comment by mpigott** [comment]
@Podgkin I think it is working with the pathologic settings so thanks for the tip. Caching does make it rather mysterious though.

**Comment by aleayr** [comment]
Good to see this is resolved, I ran into some Pathologic issues on another site recently, so I'll flag to have a look at the default Pathologic settings.
