### ISSUE TITLE
Autoplay of videos should be disabled by default

### ISSUE THREAD

**Issue by nathan-w** [govCMS/GovCMS7#375]
As a content editor
I want video autoplay to be disabled by default when inserting media into the WYSIWYG
So that people looking at my page dont get bombarded by content they havent chosen to view

[Workaround]
Insert media through the dialog box, choose the "autoplay" option, then edit the HTML and change the flag from 1 to 0

**Comment by aleayr** [comment]
Can reproduce. Autoplay is unchecked when entering the video, but it still autoplays. As @nathan-w indicates above, you need to turn it on, then manually turn it off.

If someone could provide a PR with tests to resolve this, that would be great.

**Comment by mgdhs** [comment]
I've got this working. It is an upstream change. Give me a day to document and patch upstream and here.

**Comment by mgdhs** [comment]
[Drupal.org issue 2848249](https://www.drupal.org/node/2848249) against Video Filter solves the issue. 

We can wait and see if they accept the patch and create a new version, or just use the patch. It is also against the newest version, 7.x-3.4 which could be done in #450
