### ISSUE TITLE
Consultation feature does not accept certain valid Australian phone numbers

### ISSUE THREAD

**Issue by invisigoth** [govCMS/GovCMS7#378]
It has been noted the "phone" module on which the consultation feature is based does not allow valid Australian phone numbers such as 0261xxxxxx (TAS) and 025xxxxxxx (ACT) and some mobile numbers.

**Comment by Wongad** [comment]
This is the same for the Phone field in the Webform as well, not just the Consultation feature.
We've workaround it by using just a Number field, with integer, not thousand separator and uncheck the Exclude zero

**Comment by Feng-Shui** [comment]
PR up to provide support for the missing numbers #463
