### ISSUE TITLE
Suppress messages after profile install 

### ISSUE THREAD

**Issue by mstrelan** [govCMS/GovCMS7#380]
After installing govCMS the user is bombarded with messages from installing the contrib modules. These are not really useful at this stage. Perhaps they should be removed? Obviously the hard part will be ensuring that any relevant messages are displayed. Thoughts?

Status messages:
> Thank you for installing the Metatag module. It is recommended to read the module's README.txt file as there are some known issues that may affect this site.
> It may be worth verifying on the Settings page which types of content on the site should allow meta tags.
> Honeypot installed successfully. Please configure Honeypot to protect your forms from spam bots.
> To use menu blocks, find the "Add menu block" link on the administer blocks page.
> Password policy module successfully installed. Please review the available configuration settings.
> Risky permissions have been automatically disabled.
> To use Superfish go to the administer blocks page and enable a Superfish block.
> Metatag support has been enabled for the Tags vocabulary.
> Metatag support has been enabled for the Slide content type.
> Metatag support has been enabled for the Standard page content type.
> Metatag support has been enabled for the Blog Article content type.
> Metatag support has been enabled for the Event content type.
> Metatag support has been enabled for the Publication content type.
> Metatag support has been enabled for the Media Release content type.
> Metatag support has been enabled for the News Article content type.
> Metatag support has been enabled for the Promotion content type.
> Content permissions have been rebuilt.

Errors:
> There is a error during request to Google Analytics Metadata API: Error opening socket ssl://www.googleapis.com:443

Warnings:
> Login Security and Flood Control modules are automatically disabled.

**Comment by aleayr** [comment]
Thanks @mstrelan 

I did an install on simplytest.me the other day and saw this as well. Would be interested as well if anyone has any ideas on how to remove these without losing the important messages.

**Comment by deanvucic** [comment]
We will look into this more closely in the future. For now, I am closing this issue.
