### ISSUE TITLE
Media oEmbed module not working with Clamav

### ISSUE THREAD

**Issue by pandaskii** [govCMS/GovCMS7#383]
This affects all govCMS sites with Clamav module enabled.

![screen shot 2016-11-17 at 10 20 23](https://cloud.githubusercontent.com/assets/1326673/20370210/9b3de050-acb1-11e6-956c-ababa9d91585.png)

REF PR: #205

**Comment by invisigoth** [comment]
https://www.drupal.org/node/2690329#comment-11014049

**Comment by aleayr** [comment]
Good pickup, ClamAV needs an update as well as Media: oEmbed. I'm going to go through and update modules that have fallen out of sync shortly.
