### ISSUE TITLE
Provides a govCMS build version at site status report page

### ISSUE THREAD

**Issue by pandaskii** [govCMS/GovCMS7#386]
Currently, at site "Status report" page it displays an empty value of govCMS version which brings difficulties on testing, debugging and project management. This happens if the user builds the govCMS instance instead of downloading from Drupal project page. Therefore, all the SaSS sites are with this issue.

![snip20161124_1](https://cloud.githubusercontent.com/assets/1326673/20584238/daa7cbfa-b244-11e6-809f-5bd25f080129.png)

The proposal is to create a file containing govCMS build information then shows the information at "Status report" page if the govCMS profile version is unknown.

By applying this method, the testers, developers and project managers will re-gain the picture regarding their current running govCMS instance.

![snip20161124_2](https://cloud.githubusercontent.com/assets/1326673/20584375/157140bc-b246-11e6-8b04-559926f41948.png)

**Comment by tobybellwood** [comment]
no idea when this happened, but ta-da!
![image](https://user-images.githubusercontent.com/4373945/39352223-6f66ef82-4a47-11e8-8e3e-b4fb0835adfe.png)
