### ISSUE TITLE
Problem with view showing node twice when the node is tagged with two taxonomy terms

### ISSUE THREAD

**Issue by mpigott** [govCMS/GovCMS7#393]
Hi govCMS community, 

I have a problem that I need help with. 

I have a view that filters a particular content type and groups the title fields of this content type by taxonomy term. 

This view also has a contextual filter **Content: Has taxonomy term id** with a depth of 1. 

There is one node that is tagged with two different taxonomy terms from the same vocabulary. This causes the node to be displayed on the view twice under each of the taxonomy terms, even though one of the taxonomy terms is not a  child of the taxonomy term being viewed. 

I have tried the following but they haven't been able to get rid of the duplicate node: 

- selecting the reduce duplicates checkbox in the **Content: Has taxonomy term** filter criteria 

- Turning on aggregation and selecting Count distinct for the **Content: Has taxonomy term** filter criteria

- Selecting **Distinct** in the query settings. 

Has anybody come across this problem before?

**Comment by Chris820** [comment]
Ooh yeah, I've ran into that before too.

Sometimes with Views there's a fine line between: _it works and I don't know why_ and _it doesn't work and I don't know why_

So with Aggregation turned on, head into the Aggregation settings of the field used to set the Taxonomy Term, and set the Group Column drop-down to **Entity ID** (it may default to **Tid**).
This should comma seperate the terms if there's more than one on a node.

HTH

As a footnote: When I get a View working, I export the code and add it into a Module. So it can be source controlled. Makes it much easier to revert if a misconfiguration breaks things.

**Comment by mpigott** [comment]
Thanks Chris. I tried what you suggested and it partially worked. 

- I turned aggregation on. 

- I went to the aggregation settings for the grouping field and set the Group column drop-down to **Entity ID**. Nothing really happened until I selected **Tid** for Group Columns (additional). 

This removed the duplicate node title under the grouping field. For example, **Taxonomy Term 1 > Node 1, Node 1** became **Taxonomy Term 1> Node 1**. 

However, I still have the problem of the taxonomy term that is not a child term of the viewed term being repeated on the view. For example, I can still see **Taxonomy Term 1 > Node 1** and **Taxonomy Term 2 > Node 1** despite Taxonomy term 2 not being a child of the parent term. 

This might be a bug that I can't avoid. :-(

**Comment by Chris820** [comment]
Hmm.
So the View would be querying the Nodes and drawing a relationship to the Taxonomy. 
Rather than a Taxonomy query with a Node relationship.

Perhaps try creating a complete new View and trying the above.
Instead of Show [Content] of type [all] - Show [Taxonomy terms] of type [your vocab].
