### ISSUE TITLE
Font reset button in the header does not work 

### ISSUE THREAD

**Issue by chloeleichen** [govCMS/GovCMS7#40]
The font reset button in the header does not work
![screenshot](https://cloud.githubusercontent.com/assets/7508939/9187319/73e9c12a-4012-11e5-88aa-f744c785bbdd.png)

**Comment by fiasco** [comment]
Hi @chloeleichen, could you please provide more information about how to replicate your issue? Are you running the out-of-the-box installation? Did you observe and javascript errors in the console (e.g. in Chrome developer console?)
