### ISSUE TITLE
As a content admin, I want empty fields to show on a content type with a message

### ISSUE THREAD

**Issue by mpigott** [govCMS/GovCMS7#409]
I have an issue that relates to #364 

We have a publication that features embargoed documents. We don't want to upload the documents to govCMS before  the embargo is lifted because that creates a risk of someone finding them and using them to gain an advantage over someone else. 

Therefore, I had an idea of publishing the HTML version of the publication once the embargo is lifted, using a content type that has a file field. When the HTML version is first published, the file field would be empty and display a message like 'The associated documents for this publication will be published shortly'. 

Our content publishers will then quickly upload the documents after the embargo time is lifted and republish the publication as soon as possible. This would mean we don't have to worry about linking documents, etc and the publication will have a consistent format. 

When I tried to implement this idea, I found there was no way of creating a message for an empty field of a content type. In fact, empty fields aren't even displayed. I thought about using views, but this got too complicated. 

Is there any way I can solve this issue? There is a module called [Empty fields](https://www.drupal.org/project/empty_fields). It seems to do what I am suggesting.

**Comment by Chris820** [comment]
I would likely tackle this using a field preprocessor in my theme's template.php file.
Implement a THEME_preprocess_field() hook to check for the field, check if there's anything in it, and if not modify the [#markup].
This is off the top of my head, so am probably forgetting a couple of things, but would only end up being only a few lines of code never-the-less.

Let us know if this sounds like it's worth a shot.

**Comment by mpigott** [comment]
Thanks @Chris820 It definitely sounds worth a shot.

**Comment by mpigott** [comment]
After discussion with my colleague, I think we came up with a solution that doesn't require a theming update. 

- Added a list field to the content type and positioned it above the file field. 

- Added one value to the list field, which is the message 'Documents will be available shortly'. 

- In manage display for the content type, added a HTML element with the label 'Documents' and positioned both the list and file fields within this group. 

- If there are no documents in the content, then you can check the list field to display the message or uncheck it if there are documents.

**Comment by Chris820** [comment]
Nice. That's a really good solution.
You made a good point earlier, about how if the file field is empty then it just won't show up in the rendered output at all. So in hindsight a field preprocessor on its own would not have worked.
It's still possible to do in code, but some would likely say that the less code hacking you do, the better it is for your sites long-term maintainability.

**Comment by aleayr** [comment]
Good to see you've found a solution @mpigott!
