### ISSUE TITLE
UI select box improvement! (Admin UI)

### ISSUE THREAD

**Issue by ArmyIM** [govCMS/GovCMS7#410]
When you are using the GovCMS distribution of Drupal for a large website, with hundreds of links in the menu, the standard select list is very frustrating to use (as you can see in the attached image). 

Adding the Select2 module (or similar), would really enhance the experience for content editors. The Select2 module replaces the standard select box with one that supports searching and infinite scrolling of results. This means searching for a menu item is much quicker and easier - making everyone happy! :)

[https://www.drupal.org/project/select2](url)

![dropdown](https://cloud.githubusercontent.com/assets/19546383/22047868/963df246-dd7d-11e6-9649-e5e5251d9f85.jpg)

**Comment by Chris820** [comment]
Hi ArmyIM

The Hierarchical Select module should do the trick. I'm fairly certain that it's already in the govCMS distribution. 
If you have the access, enable the Hierarchical Select Menu module and see how you go.

**Comment by ArmyIM** [comment]
Hi Chris820,

Thanks for the tip, but after searching through all the modules, the Hierarchical Select module is nowhere to be found. :(

**Comment by Chris820** [comment]
Yeah bummer. It should be there tho. It's in the .make file.
Perhaps one of the govCMS maintainers could jump in here and explain where I've gone wrong.

**Comment by mgdhs** [comment]
You may have to ask Finance to enable it for your site. On factory we can't see or enable all of the modules.

**Comment by ArmyIM** [comment]
I'll submit a ticket request - hopefully can have it enabled and the module makes editing a bit easier! :)

**Comment by marblegravy** [comment]
If you have issues with getting the module enabled or it doesn't do what you want it to do, you can always add Select2 to your theme manually.
https://select2.github.io/

I'd also recommend you and govCMS consider Chosen as a better UI for complex select fields. It's got a lot of neat options - it's also got a much more substantial installation base than Select2 and has a D8 version already.

Module:
https://www.drupal.org/project/chosen

JS Library for use directly in your theme:
https://harvesthq.github.io/chosen/

**Comment by ArmyIM** [comment]
Hi marblegravy,

Chosen looks like a great module, however I need this to be in the GovCMS drupal admin theme....but you're right, I could probably just manually add the JS Library to my admin theme overrides. 

I guess I really just wanted to raise awareness of this UI issue. Hopefully I can get some support from other users of the GovCMS drupal distribution, and an improvement to the admin UI select fields will be added in a future update.

**Comment by aleayr** [comment]
Hi @ArmyIM 

Looks like Hierarchical Select hasn't been added to the module whitelist (our oversight) when it was added to the distribution - I'll get this fixed up to a subsequent release.

I've added this to your sites now for you, so you should be able to enable both the base Hierarchical Select, and the Hierarchical Select Menu modules and you'll be fine :)

**Comment by ArmyIM** [comment]
Hi @aleayr,

Just enabled the modules...Such a HUGE improvement! You've made my day! Thank you!!! :D
