### ISSUE TITLE
Drupal core update

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#412]
Drupal 7.53 is available.

From [Drupal.org](https://www.drupal.org/project/drupal/releases/7.53):
> # All changes since 7.52:
> Issue #2821441 by davic, droplet, David_Rothstein, Joe Keene, Fabianx, tory-w: Fixed that newer Chrome versions cannot drag and drop anymore on desktop after 7.51 update when jQuery is updated to 1.7-1.11.0

**Comment by tobybellwood** [comment]
PR #502 has been submitted for an upgrade to 7.54
