### ISSUE TITLE
Module update: Chaos tools suite (ctools)

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#414]
ctools 7.x-1.12 is available. Currently running 7.x-1.10.

> ## Changes since ctools 1.11
> #2808985 by DamienMcKenna: Ensure CTools 7.x-1.x tests run, enable automated tests
> #2826313 by shailesh.bhosale: Help / permission links text not aligned correctly.
> #2822809 by michel.g: Constant UUID_PATTERN already defined
> #2449245 by ndf, das-peter: Cloning page manager handlers leads to duplicated uuids
> #2670160 by Albert Volkman: Spelling error "dispaly" in drush commands
> #2598750 by eugene.ilyin: ajax key defined twice
> #2539454 by ibonelli: Invalid plugin module/type combination requested (due to cache issues).
> #2373297 by David_Rothstein, DamienMcKenna: hook_ctools_content_subtype_alter() does not provide any reliable way to identify the subtype being altered
> #2184205 by jweowu, rivimey: ctools_content_render() claims to return an array; actually returns an object
> #2068335 by Mac_Weber: function ctools_get_plugins() documentation
> #640226 by clemens.tolboom, rivimey, jwilson3: Adding Book Navigation Block to panels and mini-panels
> #1226648 by chasingmaxwell, Apfel007: Strict warning: error ctools_term_breadcrumb()
> #935168 by Darvanen, codewatson, rivimey, DamienMcKenna: "Use context keywords" strips out anything after a % if it doesn't match
> #528036 by rajeshwari10: Create text for the "Getting Started >> The page list" page in page manager advanced help
> ## Changes since ctools 1.10
> #1265272 by dimduj, DamienMcKenna, rivimey, johnnydarkko: Page manager task_handlers plugin should provide "302 temporary Redirect" in addition to the 301 Permanent Redicrect
> #636052 by rivimey, mike.roman: Documenting that Drupal menu system overrides Panels menu setting
> #2679747 by Omar Alahmed: Add RTL support for modal css.
> #1956528 by pdcarto, sgurlt, lukio, jessepinho, texas-bronius: Disabled page variant is exported as "disabled = FALSE"
> #2645612 by japerry, Upchuk, Sam152, benoit.borrel: Missing Classes after update to 7.x-1.10 (was: Attributes array doesn't populate classes)
> #2087105 by rbayliss: user_edit_form relationship does not work on pages other than user/*/edit
> #1910608 by mkhamash, mpotter, beeradb, gmercer, hefox, redndahead, vordude, eyilmaz, lucas.constantino: Ajax + Allow settings: Allowed settings lost on ajax (exposed forms/pager)
> #2208433 by DamienMcKenna, fubhy, Andrew_Mallis: Query string context and relationship
> #2275355 by artemln: Auto submit to submit a non-existent form
> #1700378 by logickal, DamienMcKenna, dimduj: Number of Page Variants

**Comment by tobybellwood** [comment]
Merged in #482
