### ISSUE TITLE
Module Update: Context

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#417]
Available version: 7.x-3.7
Current version: 7.x-3.6

> ## Changes since 7.x-3.6:
> Translatable string review
> Issue #1828018 by hass: Duplicate 'active' classes are added if it's the current page or views tabs
> Issue #1272582 by tien.xuan.vo: Error: uncaught exception: Syntax error, unrecognized expression: [value=facetapi-apachesolr@solr:current_search]
> Issue #2311645 by tekante: terms selected using entity reference and context module
> Issue #1466422 by KarlShea: Book Root condition patch
> Issue #2374445 by hass: Failed to set field reactions[plugins][menu] to node/add/blog
> Issue #2374445 by hass: Undefined index - menu in context.module line 211 while context.conditions.test is running
> Issue #2117447 by sdrycroft: Override of tearDown() results in an error in taxonomy_get_tree()
> Issue #2374445 by hass, TuWebO: Reaction MENU to set active menu item does not work anymore after upgrade to 7.x-3.3
> Issue #2403863 by hass, Agileware: No HOME link for Context breadcrumbs
> Issue #2721621 by hass: Double checkplained top level menu names

**Comment by tobybellwood** [comment]
closing in favour of #529
