### ISSUE TITLE
Module Update: Crumbs, the Breadcrumbs suite

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#418]
Available version: 7.x-2.3
Current version: 7.x-2.5

> ## Changes since 7.x-2.4:
> 8f1cf25 #2488208: Crumbs module breaks if module_implements cache is poisoned and only lists bootstrap modules by stefan.r
> 5bbaf41 #2500187: Robust behavior in case of invalid frontpage. by mortenthorpe
> fb599bb #2527570: Menu hierarchy plugin should prefer top links over other matching menu links by donquixote, GaëlG
> a80ee21 #2510420: Plugin for the References module (node_reference and user_reference) by valentin schmid: Plugin for node_reference.
> 3597276 #2510420: Plugin for the References module (node_reference and user_reference) by valenitin schmid, donquixote: Plugin for user_reference
> ## Changes since 7.x-2.3:
> - f25b032 Improve/Fix the form element description for custom breadcrumb separator.
> - 0e937dd crumbs_separator_span setting is boolean (checkbox), not string.

**Comment by tobybellwood** [comment]
closing in favour of #529
