### ISSUE TITLE
Module Update: Default config

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#419]
Available version: 7.x-1.0-alpha11
Current version: 7.x-1.0-alpha9

> ## Changes since 7.x-1.0-alpha9
> Issue #2276069 by loopduplicate: .info file formatting and spelling update needed.
> Issue #2221005 by lorique: Modules appears double in defaultconfig overview.
> Issue #2008178 by mpotter | hefox: Fatal error when adding a permission that doesn't exist.
> Issue #2043307 by hefox: 'features.defaultconfig.inc' file never added during install -- what is 'group' key for?.
> Issue #1947670 by g.oechsler: Variants are lost when rebuilding page manager pages.
> Issue #1861054 by emattias: Defaultconfig_rebuild_all() doesn't work.
> Issue #2042799 by hefox: Undefined property: stdClass::$did in panels_mini_delete().
>

**Comment by tobybellwood** [comment]
closing in favour of #529
