### ISSUE TITLE
Module Update: Diff

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#420]
Available version: 7.x-3.3
Current version: 7.x-3.2

> ## Changes since 7.x-3.2
> #2421463: Render revision as entity by markusbroman
> #2399579: A diff is erroneously displayed whenever an HTML ID generated by drupal_html_id() is used in the rendered entity by David_Rothstein, Alan D.
> #2637908: diff_field_diff_view() returns results even if the entity has no field values in the requested language by David_Rothstein, Alan D.
> #2667654: Wrong redirect when coming from admin/content by caminadaf, Alan D.
> #2401143: In sanitized [node:diff] token, table HTML is escaped by smokris
> #2829781: Provide ability to restrict the 'View changes' button by joelpittet, Alan D.
> #2117133: Change "This is the published revision" by Alan D., gmclelland, hass
> #1964018: Don't use $reset flag with node_load() by jweowu, Alan D.
> #2377565: Warning: Invalid argument supplied for foreach() in diff_process_state_lines() by anrikun, merlinofchaos
> #2533058: Spelling errors in D7 by rrfegade
> #2640478: Deprecating PHP4 style constructors by heddn
> #2557287: Logic to show inline differences on certain node types does not work. by jastraat
> #2068015: Radios missing by Amathieso, Tilo, Alan D.
> #1982432: Remove excessive empty line in marked-down diff by Pancho, Alan D.
> #1970872: Add permissions help for admin theme setting by Alan D.
> #239056: Fixed path to the latest diff (and handle case when there is only 1 revision) by Leeteq, smokris & Alan D.
> #1838364: Minor admin Default display settings error by Alan D.
> #1893766: Highlight published revision in diff compare table by hass, torpy
> #2101391: File Entity Improvements by haydeniv, Alan D.
> #1951546: Inline Diff incorrectly identifies an addition as a change within a table cell bu El Bandito, Alan D.
> #2110371: Providing User entity support by Alan D.
> #2109905: Extending node comparison to optionally include status, sticky, promoted, revision timestamp and title. by Alan D.
> #1708696: Diff between two different entities by Alan D.
> #2109725: Redundant table row when empty. Why do we need to "keep safari happy" by Alan D.
> #1995962: Link to config page not showing in modules list by Pat Redmond
> #2021651: API ref for hook_entity_diff_alter() doesn't list $entity_diffs as by ref by BrockBoland
> #1894120: Use of scalar class instead of an array in attributes array. by michael_cristal, Alan D.
> #2077853: Slight change to diff_entity_fields_diff() so it is more re-usable from hook_entity_diff by douggreen, Alan D.
> #1280880: Diff module Features integration by crea, Angry Dan, Alan D.

**Comment by tobybellwood** [comment]
closing in favour of #529
