### ISSUE TITLE
Module Update: Display Suite

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#421]
Available version: 7.x-2.14
Current version: 7.x-2.8

> ## Changes since 7.x-2.13
> #2503653: Per node template suggestion introduced a regression. This release fixes those problems.
> ## Changes since 7.x-2.12
> Fix integration for Fieldable Panels Panes.
> ## Changes since 7.x-2.11
> Bug fix release
> ## Changes since 7.x-2.10
> Issue #2492661 by Erik Frèrejean: Incorrect field info api documentation for 'block fields'
> Issue #2507163 by aspilicious: Block regions cannot be deleted following upgrade to 2.10
> Issue #2497445 by aspilicious: Upgrading from DS 7.x-2.8 > DS 7.x-2.10 changes view mode on nodes from full content to default on page
> Issue #2493145 by artis: Typo in recent commit for Token support in 7.x-2.x branch
> Issue #2490932: Undefined property: DatabaseConnection_mysql::$sid in node_ds_search_execute() (line 488 of ds_search.module)
> Issue #2453137 by aspilicious: Unable to overwrite theme_ds_field_expert
> ## Changes since 7.x-2.9
> This is a bug fix release for a bug that is affected many websites using ds search. See #2385835: Adding 'theme_hook_original' triggers PHP warning in theme_ds_search_page
> ## Changes since 7.x-2.8
> This release contains various bug fixes and a couple of new features.
> 
> New features:
> 
> Enable/disable view modes per content type
> Ability to Disable the CSS file added on Layouts
> Replace tokens in layout attributes

**Comment by tobybellwood** [comment]
closing in favour of #529
