### ISSUE TITLE
Module Update: Entity API

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#422]
Available version: 7.x-1.8
Current version: 7.x-1.6

> ## Changes since 7.x-1.7:
> #2323619 by Weaver, lex0r, a.milkovsky, fago: Improve entity_metadata_taxonomy_access to cover existing permissions
> #1874006 by fago: Expose entity references as CTools relationships
> #1989444 by nuez, djdevin: Views integration for properties of type = duration does not work
> #1621002 by grahl, valderama, mfb, fago: Fix typo in comment of entity_metadata_node_entity_property_info_alter().
> #1621002 by grahl, valderama, mfb, fago: Cardinality breaks node indexing on main body
> #2448151 by Aleksander Belov, alesr, joelpittet: Speed up feature revertion of entity exportables
> #2512744 by rrfegade, joelpittet: Typos and Spelling - D7
> #1986736 by tedbow, ciss, coline: EntityDefaultFeaturesController doesn't export field instances. Breaks export with Features 2.x
> #2445881 by plopesc, e0ipso: Remove extra space in Entity UI table
> #1621226 by joachim, DuaelFr, cthiebault, fago: Entity Metadata Wrapper: Add field information to exception message on validation exception
> #2476821 by znerol, ladybug_3777, jmouse888: Array flip errors when books are not part of a book hierarchy. --author="znerol
> ## Changes since 7.x-1.6:
> #2340487 by das-peter: Views Row Plugin "Rendered entity" should add reference to the view
> #2420551 by e0ipso, fago: Add EntityInterface to allow programming to interfaces.
> #977372 by joachim, jacob.embree: grammar in docs - stray commas
> #2109825 by joachim: theme_entity_property() doesn't respect 'content' variable
> #2112755 by phenaproxima, kristiaanvandeneynde, SchnWalter, ofry, ruscoe, dangswiss: Fixed error 'Call to a member function label() on a non-object' in generated admin UI
> #2241979 by das-peter, a.milkovsky, fago: Add a way to prevent exportable rebuild on cron run

**Comment by tobybellwood** [comment]
closing in favour of #529
