### ISSUE TITLE
Module Update: Entity cache

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#423]
Available version: 7.x-1.5 (Proposed to go to 7.x-1.4)
Current version: 7.x-1.2

**Due to the following warning on upgrading directly from 7.x-1.2 to 7.x-1.5, I'm proposing to upgrade to 7.x-1.4 before going to 7.x-1.5 at a later stage**

_Updates from 7.x-1.2 may fail on some sites with fatal errors due to issues with Drupal 7's classloader, making update.php and the rest of the site inaccessible._

_There is no way to resolve this in entitycache itself, so it requires an additional step when updating the module._

_Ensure you have drush available for your install, or download https://www.drupal.org/project/registry_rebuild and follow the instructions before updating from 7.x-1.2 to 7.x-1.5._

> ## Changes since 7.x-1.3:
> #1851398 by stefan.r, heddn, wiifm: PDOException:Invalid text representation when attempting to load an entity with a string ID
> Changes since 7.x-1.2:
> #2441965 by lord_of_freaks, joelpittet, vijaycs85: Broken updates due to Classes living in .module files
> #1349566 by Devin Carlson, lex0r, jrbeeman: Add tests for content translation
> #1262430 by dawehner, sdboyer: Convert $conditions to use EntityFieldQuery then load by ID from cache
> #2135169 by fago: Support caching of failed load operations.
> #1670848 by torgosPizza, colan, ndeschildre: Fixed Unnecessary recaching of terms when using taxonomy_get_term_by_name.
> #2086633 by alanmackenzie: Allow for the clearing of individual entitycache caches via drush cc.
> Fix docs to keep coder-review happy

**Comment by tobybellwood** [comment]
closing in favour of #529 (with notes)
