### ISSUE TITLE
Module Update: Entity reference

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#424]
Available version: 7.x-1.2
Current version: 7.x-1.1

> ## Changes since 7.x-1.1
> Issue #2175949 by AndyF: Drupal_static() used without reference.
> Revert "Issue #2175949 by AndyF: Drupal_static() used without reference."
> Issue #2193483 by NofarG: EnsureBaseTable() Does not get the correct table name.
> Issue #2394725 by pakmanlh, rodrigoaguilera: Migrate multiple entity reference fields using migrate module support
> Issue #1852112 by ezra-g, chrowe, dww: Invalid field value with devel_generate
> Issue #2394725 by rodrigoaguilera, FluxSauce, pakmanlh: Migrate multiple entity reference fields using migrate module support
> Issue #2013849 by plach, bojanz: Term names are not translated
> Issue #1753774 by tedfordgif: Multiple warnings when using entity reference field filtered by a view using contextual filters, inside a field collection
> Issue #2495405 by jenlampton, geoffreyr, dtamajon: Notice : Undefined variable: element in entityreference_field_formatter_settings_form() (line 1141 in /sites/all/modules/entityreference/entityreference.module)
> Issue #1836106 by cs_shadow, Xano, deetergp, RobLoach: Fatal error: Call to undefined function entityreference_get_behavior_handlers() in entityreference_schema()
> Issue #2614680 by Devin Carlson: Add Feeds and Views modules as test dependencies
> Issue #1823406 by idflood, jenlampton: Undefined index entityreference_field_formatter_prepare_view()
> Issue #1674792 by ademarco, DamienMcKenna, valderama, SchnWalter, s_leu, interdruper, Dave Reid, ndf, GiorgosK, ShaxA, rudins, Cyclodex: Rendered entity is not language aware
> Issue #1943300 by Rob_Feature, rudiedirkx: array_keys() and reset() notices in entityreference_feeds_set_target() during feed import if entity doesn't exist

**Comment by tobybellwood** [comment]
closing in favour of #529
