### ISSUE TITLE
Module Update: Event Log

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#425]
Available version: 7.x-1.6
Current version: 7.x-1.4

> ## Changes since 7.x-1.5
> Fixed multiple issues
> 2829519 by Mingsong: menu update and delete event in wrong operation category
> 2365895 by DrCrod: password request PHP notice
> 2790091 by rich.3po: purge old entries
> 
> Settings for purging on: admin/config/development/logging
> ## Changes since 7.x-1.4
> Description field in the event log size increased from 20 to 120.
> 
> Important! please run yourdomain.com/update.php to run the database update script.

**Comment by tobybellwood** [comment]
closing in favour of #529
