### ISSUE TITLE
Module Update: Features

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#426]
Available version: 7.x-2.10
Current version: 7.x-2.9

> ## Changes since 7.x-2.9:
> #1867910 by rho_, drzraf, cyborg_572: Undefined index: dependencies features.drush.inc:252
> #1633442 by Jaza, kenorb: features_get_component_states() should pass on its $reset param
> #2707427 by mpotter: Drush fl returns no output since updating to 2.8

**Comment by tobybellwood** [comment]
closing in favour of #529
