### ISSUE TITLE
Module Update: Honeypot

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#427]
Available version: 7.x-1.22
Current version: 7.x-1.17

> ## Changes since 1.21
> #2674008: Remove usage of Flood service from Honeypot
> #2674952: Switch to REQUEST_TIME instead of time() in honeypot_cron and honeypot_get_time_limit
> #2562733: Only allow [A-Za-z] first character for Honeypot class name
> #2608060: Rebuild CSS when the element name changes due to changing variable
> #2677126: Honeypot should not be triggered on programmatically submitted forms.
> ## Changes since 1.19
> #2553319: disable page cache through the API rather than hacking global conf
> #2541026: Fix notice in honeypot_get_time_from_signed_timestamp()
> ## Changes since 1.18
> #2525760: Sign timestamp values
> #2324223: Warn user if certain common field names are used as Honeypot element name
> #2508353: Remove .gitignore
> #2509442: Honeypot 7004 fails if module disabled
> #2491723: Check honeypot_expire when counting honeypot_users
> #2503309: Honeypot does not ensure that honeypot.css exists or is consistent with variable 'honeypot_element_name'
> ## Changes since 1.17
> #1355374: Hide blank field when form displayed in modal
> #2394987: XHTML validation fails due to autocomplete="off" attribute
> #2480185: honeypot_get_protected_forms cache not working properly
> #2504015: Don't show help text on module install in CLI contexts

**Comment by tobybellwood** [comment]
closing in favour of #529
