### ISSUE TITLE
Module Update: Image Link Formatter

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#428]
Available version: 7.x-1.1
Current version: 7.x-1.0

> ## Changes since 7.x-1.0:
> #2070121 by DYdave: Use field_get_items() in the field_formatter_view.
> #2069917 by DYdave: Fixed Link anchor/fragment missing with older Link Field module versions lower than 7.x-1.1.
> #1932184 by gaofengzzz, DYdave: Views integration: Added special case for the link types to support ctools bundles and display a choice of related link fields on any of the bundles to which the image field is attached.
> #1907674 by DYdave: Added support to fragment query string for links path wrapped around images.
>

**Comment by tobybellwood** [comment]
closing in favour of #529
