### ISSUE TITLE
Module Update: Libraries API

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#429]
Available version: 7.x-2.3
Current version: 7.x-2.2

> ## Changes since 7.x-2.2
> #1884246: Drush download of defined libraries by BR0kEN, tstoeckler et al: Allow downloading libraries via Drush.
> by tstoeckler: Allow detecting all libraries by calling libraries_detect().
> by tstoeckler: Prevent LibrariesWebTestBase from being displayed in the UI.
> #819610: Provide a UI for Libraries by tstoeckler: Add tests for the Libraries UI.
> #1884246: Drush download of defined libraries by BR0kEN, tstoeckler: Show the provider in drush libraries-list
> #819610: Provide a UI for Libraries by Pol, tstoeckler: Show the provider in the UI.
> #2634732: Libraries UI should sort by title and not machine name by Rob Holmes, tstoeckler: Sort libraries by title in the UI.
> #2585395: Library version callback fails if namespace array is passed as function name by robinsonsarah01: Allow object methods as version callbacks.
> #819610: Provide a UI for Libraries by tstoeckler, Pol: Provide a status report for library information.
> #2352251: API Documentation incorrectly names hook by netw3rker: Fix incorrect hook name in libraries.api.php.
> #2352237: Drush CC does not list the libraries cache by netw3rker, tstoeckler: Allow clearing the libraries cache from Drush.
> #2193969: Undefined index: post-load integration files in libraries_load_files (solved: clear your cache) by tstoeckler: Avoid warnings for stale library caches.
> #2287529: README.txt references only D5 and D6 module installation page by drupalshrek, tstoeckler: Update installation link in README.txt.

**Comment by tobybellwood** [comment]
Merged in #516
