### ISSUE TITLE
Module Update: Link

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#430]
Available version: 7.x-1.4
Current version: 7.x-1.3

> ## Changes since 7.x-1.3
> Issue #2470377 by rhclayto: Adding a class with underscores, the class gets rendered with hyphens
> Issue #609560 by Boobaa: Provide token for hostname
> Issue #2632728 Apply patch: link-field_link_validate_overrites_langcode-2632728.patch
> Issue #2247261 by heddn, sumitmadan: URLs are not validated
> Issue #2513706 by rrfegade: Spelling errors in D7
> Issue #2470968: Add README.txt
> Issue #2055111 by joelpittet, mikeytown2: skip over re-loading entities for tokens in link field attributes unless there's a token to process.
> Issue #2367069 by jcfiala:Fixed entity_token for link after node_view was called.
> Added setup function to LinkValidateUrlLight to enable link module, which was failing drupal.org qa testbot.
> Issue #2364673 by jcfiala: Replaced drupal_html_class() with drupal_clean_css_identifier() so that link field classes are not forced to lower case.
> Added tests to test entity_token token with link.

**Comment by tobybellwood** [comment]
closing in favour of #529
