### ISSUE TITLE
Module Update: Link checker

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#431]
Available version: 7.x-1.3
Current version: 7.x-1.2

> ## Changes since 7.x-1.2
> #2060243: Split linkchecker_scan_nodetypes as content type specific
> #2651180: Ignore fragment used for ajax requests
> Upgrade outdated HTTP user agents.
> #2660694: PHP 7.0 errors
> Fixed two typos
> #2443055: Optionally reduce the number of LinkChecker log entries
> #2616082: Add @return type and @param values in the comment docblocks.
> #2303177: "Back to Top" Page anchor being reported as a 404 error?
> #2340211: Error on adding content submission

**Comment by tobybellwood** [comment]
closing in favour of #529
