### ISSUE TITLE
Module Update: Login Destination

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#432]
Available version: 7.x-1.4
Current version: 7.x-1.1

> ## Changes since 7.x-1.3
> Fix bugs after updating module from previous version.
> #2631630 Getting "Incorrect path, Please Enter valid Path" error when trying to add a new path that does work
> ## Changes since 7.x-1.2
> #2631630 Use of empty() in login_destination.admin.inc line 538 imcompatible with PHP pre-5.5
> ## Changes since 7.x-1.1
> #2231269 by mr.york, joshf: Wrong current path validation
> #1628030 by DmitryDrozdik: Add an ''Administer login destination'' permission
> #1964602 by elliotttf: Redirect fails on front page
> #2610320 by Lonnytunes: Conflict with change_pwd_page module
> #2036699 by jsacksick, Cookiz: The dropdown Commerce Kickstart Menus stopped dropping down after enabling login destination module
> #2424601 by akashjain132, rsvelko, joelpittet, DmitryDrozdik: Getting "Incorrect path, Please Enter valid Path" error when trying to add a new path that does work
> #2617156 by lucass: Incorrect path - < current >
> Code refactoring

**Comment by tobybellwood** [comment]
closing in favour of #529
