### ISSUE TITLE
Module Update: navbar

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#435]
Available version: 7.x-1.7
Current version: 7.x-1.6

> ## Changes since 7.x-1.6
> Issue #2550367 by eshta: Use full window location for back to site length.
> Issue #2571289 by eshta, hass: Rename 'Menu' to 'Manage' to better align with Drupal 8
> Issue #2434655 by eshta, partdigital: Update menu tree build process to review access for each load
> Issue #2509740 by eamonogealagain: Fix Modernizr version detection regex.
> Issue #2477473 by eshta: In narrowest viewports, make the vertical toolbar menu 100% width
> Issue #2448023 by eshta: Remove unused CSS.
> Issue #2182939 by eshta: Add modernizr.min.js as an accepted minified filename.
> Issue #2429669 by eshta: Fix body 'shake' on table pages by caching the top displacement amount.
> Issue #2448925 by msound: Fix line ending in navbar.make.example.
> Issue #2227293 by hass, lsolesen: Remove navbar from print view.

**Comment by tobybellwood** [comment]
closing in favour of #529
