### ISSUE TITLE
Module Update: Panels

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#436]
Available version: 7.x-3.8
Current version: 7.x-3.7

**Note: This update requires ctools 7.x-1.11**

> ## Changes since 7.x-3.7
> #2808983 by DamienMcKenna: Add tests to Panels
> #2785981 by Елин Й.: Undefined variable $page in panels_panel_context_save() function in panel_context.inc
> #2329419 by heddn, mglaman: Style permissions not granular enough
> #2479879 by temkin, joelpittet, Mixologic: Move 'panels_page_allowed_types' variable to a custom table
> #2792651 by dsnopek: Watchdog error when changing layout
> #2787637 by dsnopek: Page manager gives access denied when managing newly added variants to tasks other than 'page'

**Comment by tobybellwood** [comment]
Merged in #482
