### ISSUE TITLE
Module Update: Paranoia

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#437]
Available version: 7.x-1.6
Current version: 7.x-1.4

> ## Changes since 7.x-1.5
> #2640480 greggles, coltrane: this and the build caused double-prefixing and tables to be truncated
> #2640480 greggles, dpintats, c4rl: fix review feedback
> #2640480greggles: add a sanitize whitelist system
> #2565759 by gabrielmachadosantos: Make purging inactive users optional
> #2313945 by greggles: block all "import foo" boxes that use php arrays as a data structure
> #2294061 by greggles: Remove all sessions for a uid if password is changed
> ## Changes since 7.x-1.4
> Code style issues
> #2359095 by greggles: Add auto_username
> #2053075 by greggles: prevent PHP execution by Skinr module
> #2476739 by mglaman, greggles: Add hook to deny access to menu paths
> #2462509 by mglaman: Block ctools' custom PHP access
> #1884338 by douggreen, Matt V.: more sanitizing - usernames/emails
> #2430281 by greggles: Disable the ds_format module from display suite to avoid php eval
> #2401063 by drumm: Hide 'use PHP for service [links] visibility' permission
> #2429899 by greggles: Prevent auto_entitylabel.module 'use PHP for label patterns'
> #2031017 by greggles: re-run the risky permissions remover in hook_modules_enabled
> #2261005 by loopduplicate: First time install fails
> #2429543 by klausi: Rules "bypass rules access" should not be blacklisted

**Comment by tobybellwood** [comment]
closing in favour of #529
