### ISSUE TITLE
Module Update: Redirect

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#440]
Available version: 7.x-1.0-rc3
Current version: 7.x-1.0-rc1

> ## Changes since 7.x-1.0-rc2
> #2516740 by Dave Reid, DamienMcKenna: Fixed errant logic for watchdog message logic about being unable to purge unused redirects.
> #2485459 by Dave Reid: Update hook 7100 does not do a registry rebuild or entity info cache clear.
> Use isset() instead of property_exists().
> Fixed redirect_fetch_rids_by_path() to fail gracefully if the redirect.status column does not exist yet.
> #2516740 by Dave Reid: Avoid watchdog message about being unable to remove unused redirects, if the redirect purge variable is disabled.
> ## Changes since 7.x-1.0-rc1
> #2308717 by Pere Orga, oadaeh, Kristen Pol: Add watchdog message when inactive redirect purging is enabled, but unable to do so.
> #2135575 by mfb, René-Marc Simard: Fixed Views handlers for source and redirect fields were broken.
> #1198028 by mxwright, gundarx, chellman: Redirects do not work if $_SERVER['SCRIPT_NAME'] does not follow base_path
> #1796596 by stefan.r, Eric_A, Steven Jones, Dave Reid, damien_vancouver, azinck, DamienMcKenna, SylvainM, nicholasruunu, GoZ, deviantintegral, mrmikedewolf, tannerjfco, Yorirou, attila.fekete, vadym.kononenko, heddn, hass, candelas, fenstrat, cmseasy, rooby, vinmassaro, Alan D., hanoii: Fix and prevent circular redirects
> #1444506 by helmo, clemens.tolboom, Dave Reid: Fixed users with the "access site in maintenance mode" permission should still be allowed to use redirects.
> #2296035 by Pere Orga: Fixed documentation, especially for redirect_load_by_source().
> #1872242 by TravisCarden: Fixed typo in redirect_purge_inactive admin form description.
> #1913924 by Simon Georges, Dave Reid: Removed useless files[] directive for files that do not contain classes.
> #2176175 by fearlsgroove, brad.bulger: Don't add URL redirects to extra fields for excluded entity types.
> #2048137 by mfb, Pere Orga, heddn: Disable canonical redirect code that calls drupal_get_path_alias() and breaks path cache (core bug https://www.drupal.org/node/2400539).
> #1263832 by hefox, Sneakyvv, scott.allison, Mark Theunissen | grendzy: Fixed Remove session-based flood / loop detection since it performs poorly and has unfix-able race conditions.
> #2051313 by mfb, Matt V.: Fixed redirect user ID not stored when redirects added via the user interface.
> #2049151 by mauritsl, justanothermark: Fixed vertical summary with number of redirects was incorrect.
> Skip infinite redirect loop handling when running in SimpleTests for now.
> Removed the crappy redirect loop message and replaced with proper trigger_error() warning.
> #1828696 by johannez, Dave Reid: Fixed compatibility with entities that return invalid values for entity_uri().
> Fixed redirects could not be created to existing files.
> #1244524: Fixed redirect vertical tab table is inconsistent with placement of actions.

**Comment by mgdhs** [comment]
I'm testing this as part of the camp. I'm running into a [missing status field](https://www.drupal.org/node/2578019). I'm going to keep testing.

**Comment by mgdhs** [comment]
There is a bug with 1.0-rc3 related to update hooks. I've [commented upstream](https://www.drupal.org/node/2578019#comment-11898757). As it is now, an update hook will not run and it renders your site uneditable.

We can either wait for rc4 (if they ever do it), or run with the patch. I suggest waiting for a few days.

**Comment by NigelCunningham** [comment]
Sounds good.

Mainly here to add a note that I'm running into the issue fixed in 0b7b8dc2d58cb277874d87c91c45f0a361e148f7 wherein the size() method that was removed in jQuery 3.0 is used. This kills client side JS when the redirect module is enabled.

**Comment by tobybellwood** [comment]
closing in favour of #529
