### ISSUE TITLE
Module Update: Shield

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#444]
Available update: 7.x-1.3
Current version: 7.x-1.2+28-dev

**Note: Some of the below changes are already available as we're running a development version of Shield**
> ## Changes since 1.2
> #2198491: Robustify user/pw check
> #2347853 by Dane Powell, Sutharsan, axel.rutz: Set HTTP Auth server variable
> #2671424 by yivich: Conflict with Path Cache module
> Amended #2479091 to use t() for boost message.
> #2479091 by joelstein: Incompatible with Boost
> Improved readme in #2471000
> #2471000 by switzern: Add readme.txt to explain use and installation
> #2364767 by drikc: Domain Access integration to shield specific domains
> #2340661 by GBenoit, axel.rutz: Correct REQUEST_URIIssue #2340661 by GBenoit, axel.rutz, dawehner, chx: Correct REQUEST_URI
> #2078697 by cossovich: Certain PHP CGI hosting configurations don't allow environment variables to be passed through to PHP
> #1829694 by Boobaa, axel.rutz, Daniel Wentsch, eiriksm: Won't take user name and password with FCGI
> #2382243 by xtfer: FastCGI param selection is not always correct
> #2336691 by LinL: Fixed Typo in Credentials section of admin form.
> White lists for ip addresses.
> Move corret order the lines and remove false code comment.
> #2063945: Refactor exclude paths.
> Merge branch '7.x-1.x' of git.drupal.org:project/shield into 7.x-1.x
> Some coding standard modification.
> Change default print text when showing it not only the admin interface.
> #1989354 by azinck, pbull: Added Allow other modules to be 'Shield-aware'.
> Use DRUPAL_ROOT in path of included files
> Fix some code comment.
> #1898216 by azinck: Added Choose shield method = protect all, exclude or include.
> #2030017 by balsama: Allow cron to run.
> #1898216 by 7wonders: Added Choose shield method = protect all, exclude or include.
> #1706902 by katbailey: Fixed Canceling authentication prompt displays blank white page where users can view the actual page source.
> Typo fix for enabled variable.
> #1604808 by samhassell: Added Disable checkbox on admin page.
> issue #1829694 by Boobaa: FastCGI and plain old mod_cgi support.
> Remove exclude patchs variable during the uninstall. .
> issue #1826418 : Popup shouldn't display user and pass by default.
> issue #1515612 by ezra-g: Exclude paths support.
> issue #1706752 : The module's name is changed to Shield.

**Comment by tobybellwood** [comment]
PR merged in #559 - closing
