### ISSUE TITLE
Module Update: Site map

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#445]
Available version: 7.x-1.3
Current version: 7.x-1.2

> ## Changes since 7.x-1.2
> ba09f58 Issue #1920722: Accessibility enhancements by jptaranto and kim.pepper: Accessibility enhancements
> 34d5d07 minor coding issue fixes in site_map.theme.inc
> de8ea46 minor coding issue fixes in site_map.install
> 9506e4a minor coding standard issues fixed in site_map.module
> 7124eb7 Issue #1529708: Allow ordering of site map content by imperial_dalek, torpy, janekD7, helmo: Allow ordering of site map content
> 5389d87 Issue #1545422: Expose configuration options to variable module to enable per language settings by Tom Robert, Jax: Expose the menus to show to Variable.
> 8128f55 Issue #1986086: Customize Breadcrumb title by julioneander: Set the page title if configured.
> c67a064 Revert "Issue #1529708: Allow ordering of site map content by imperial_dalek, torpy, janekD7, helmo: Allow ordering of site map content"
> 0ad2752 Issue #2500421: Make custom page titles translatable by colan: Make the built-in page title translatable until it gets overridden.
> 8408d57 Issue #1706162: Add support for taxonomy term translation by facine, defrost, colan: Added term translation support for each type.
> 16f54fb Issue #2500421: Make custom page titles translatable by colan: Don't use configured page title if it's empty.
> bcb4678 Issue #2509164: Allow other modules to alter list of displayed menus by colan: Allow other modules to alter the list of displayed menus.
> ec4bca7 Issue #2500421: Make custom page titles translatable by colan: Added more help text for translating the page title.

**Comment by tobybellwood** [comment]
closing in favour of #529
