### ISSUE TITLE
Module Update: SpamSpan filter

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#446]
Available version: 7.x-1.3
Current version: 7.x-1.2+14-dev

**Note: Some of the below changes are already available as we're running a development version**
> ## Changes since 7.x-1.2
> #1012088: Attributes of spam filtered <a>-tags disappears
> #1422462: Broken output if mailto: address has subject & body in D7
> #1167084: Tags embedded inside the < a href="..."> tag break spamspan
> #2411661: spamspan.test could not be found
> #723460: "mailto" links over images displayed broken#
> #2403885: The use_form functionality does not work
> #2386583: No @ image customization.
> #1243042: Spamspan incompatible with big base64 inline images
> #2462471: Longer TLDs get trimmed
> #2451115: Certain characters in mailto: subject break output
> #2700333: Override default settings is not possible in spamspan function

**Comment by tobybellwood** [comment]
Commit version that we're including specifically [(Issue #2451115 by earlofsandwich, vitalie: Certain characters in mailto: subject break output)](http://cgit.drupalcode.org/spamspan/commit/?id=cebf9dd3a360b466b498755fe800580e6b215646) is included in 7.x-1.3 release

**Comment by tobybellwood** [comment]
PR over at #599 - closing
