### ISSUE TITLE
Module Update: TOC Filter

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#447]
Available version: 7.x-1.3
Current version: 7.x-1.2

> ## Changes since 7.x-1.2
> #2106999 by merlin06: toc filter only recognizes lower case heading tags
> #2091117 by jrockowitz - Add optional support for using a ctools jumpmenu as a TOC.
> #2058875 by jrockowitz - Target anchor not focused; breaks keyboard navigation
> by jrockowitz: Fix typos in README.txt
> #2009466 - Filter tip doesn't have proper heading tag

**Comment by tobybellwood** [comment]
closing in favour of #529
