### ISSUE TITLE
Module Update: Universally Unique IDentifier

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#448]
Available version: 7.x-1.0-beta2
Current version: 7.x-1.0-alpha6

> ## Changes since 7.x-1.0-beta1
> #2763369 by BR0kEN: Populate information about DB index to Schema API
> Switch to trait for assertUuid and bump minimum PHP version to 5.5
> #2763727 by BR0kEN: Optimizations and fixes for tests
> Fix issues found by PHP Code Sniffer
> Add UUID v5 generator function
> #2636906 by JeroenT: Fix uuid/[entity]/[uuid] notice
> #2043273 by skwashd, recidive: Improve how UUID services sets the node author.
> #2043273 by recidive: UUID services does not properly set node author.
> #2365281 by timcosgrove: Refine UUID validation pattern
> #2300301 #2236497 by skwashd: Fix formatting
> #2300301 by dkingofpa: Fix undefined property notice in stdClass::$fid in file_entity_access()
> #2236497 by RoSk0: Documentation: Add link to integration docs
> #2121031 by RoSk0, pingers, maijs: Error when trying to create empty file or destination directory not set
> #2391701 by joseph.olstad: Typo in uuid_services_menu description
> #2724323 by skwashd: Ensure passwords are always encrypted
> #2738499 by chaitanya17: Remove type element from admin/config/system/uuid
> Fix broken tests
> Enable testing with TravisCI
> ## Changes since 7.x-1.0-alpha6
> #2374691 by alexdmccabe: Call to undefined function uuid_sync_all()
> #2364859 by daniel_j: Fixed entity_save in uuid_update_7103 fails due to missing parameter.
> #2179475 by jweowu: Improve UUID generation
> #1565082 by jeffschuler: Fix features hook docs
> #1795152 by jamesharv: Localise tnid of node in hook_entity_uuid_save() if not yet done
> #2339411 by joseph.olstad, skwashd: Check entities delete before trying to delete them
> #2308501 by james_kerrigan: Implement static caching for uuid/id lookups
> #1959276 by jpstrikesback, skwashd: Return 406 if user doesn't exist
> #2074599 by timaholt, skwashd: Remove all contrib module suppport
> #2276507 by dkingofpa, skwashd: Use correct $op check for taxonomy terms
> #2302575 by dkingofpa: Don't change comment op for access check
> #1859234 by CarlHinton: Make entity_uuid_save() return result from entity_save()
> #1665084 by skwashd: Drop references to deleted hook
> Implement access check before the redirect to prevent information disclosure
> Prevent fatal errors in UUID entity functions if entity type does not support UUID

**Comment by tobybellwood** [comment]
Now at 7.x-1.0
https://www.drupal.org/project/uuid

>No changes since 7.x-beta2. 
Changes since 7.x-1.0-beta1:
•#2763369 by BR0kEN: Populate information about DB index to Schema API
•Switch to trait for assertUuid and bump minimum PHP version to 5.5
•#2763727 by BR0kEN: Optimizations and fixes for tests
•Fix issues found by PHP Code Sniffer
•Add UUID v5 generator function

**Comment by fiasco** [comment]
PR?
