### ISSUE TITLE
Module Update: Username Enumeration Prevention

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#449]
https://www.drupal.org/project/username_enumeration_prevention
Available version: 7.x-1.2
Current version: 7.x-1.0

> ## Changes since 7.x-1.1
> Issue #2172705 by a_thakur, Angry Dan, jts86: username_enumeration_prevention_form_alter can break other contributed modules
> Issue #2483015 by mikebarkas: hook_requirements usage breaks installer
> ## Changes since 7.x-1.0
> #1651294: Warn of default Pathauto and Global Redirect settings that can expose usernames.
> #2146959 by bbdata: menu_alter creates an empty link in admin page when views is disabled
> Moved requirements hook to install file, as suggested by anavarre.
> #1524292 Switching notification to hook_requirements instead of hook_enable.
> Applied patch by tim.plunkett

**Comment by tobybellwood** [comment]
closing in favour of #529
