### ISSUE TITLE
installer UI alignment not pretty

### ISSUE THREAD

**Issue by kattekrab** [govCMS/GovCMS7#45]
Just having a play with govCMS on simplytest me again, and this time remembered to log an issue.

I think the installer could do with a little theme love - the alignment is out of whack and doesn't give a good first impression.

Screenshot below.

![govcms-install-alignment](https://cloud.githubusercontent.com/assets/172755/9599158/d020c1d2-50d4-11e5-895e-694cf03232e5.png)

**Comment by teamglenny** [comment]
Closing as has been made pretty(er) in #68 Will ultimatly be a work in progress
