### ISSUE TITLE
Module Update: Video Filter

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#450]
Available version: 7.x-3.4 (https://www.drupal.org/project/video_filter/releases/7.x-3.4)
Current version: 7.x-3.3

> ## Changes since 7.x-3.3
> Issue #2701283 by dodozhang21: Fix Instagram embed issue.
> Use oEmbed for Instagram
> Issue #2693581 by mandclu, orom: Default Height is 50px

**Comment by Wongad** [comment]
Hi, 
Just checking when will this module update be going ahead?
We're trying to embed some YouTube video for our content using [video:URL].
Used to work previously a year ago but seems to no longer able to embed. Have found out that the WYSIWYG filter is stripping out the video from the function.

**Comment by tobybellwood** [comment]
Hi @Wongad - this _shouldn't_ require these module updates to function properly - drop a support ticket in and someone will check the permissions for you.

As for module update timing - we're working on it - there's a fair backlog to get through - sorry it's taken so long!

**Comment by tobybellwood** [comment]
closing in favour of #529
