### ISSUE TITLE
Module Update: Webform

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#451]
Available version: 7.x-4.14
Current version: 7.x-4.9

> ## Changes since 7.x-4.13
> #2712611 by grahamC: Fixed re-parented components deleted with old parent.
> #2688621 by joelstein: Added hide additional extensions field on file component if no access via form_alter.
> #2614384 by ben.bunk: Added let Drupal determine enctype of a form.
> #2661718 by Nicolaj, DanChadwick: Fixed no server side validation of required grid components.
> #2690815 by guilopes: Fixed integrity constraint violation when trying to save conditionals via features.
> #2673050 by FeyP: Fixed refresh entitycache after changing email status on email overview page.
> #2733427 by anrikun: Fixed PHP warning: min(): Array must contain at least one element in webform_expand_grid.
> #2786933 by grahamC: Fixed conditionals lost during update from 3.x.
> #2788981 by Liam Morland: Fixed documentation for _webform_submission_serial_next_value_used.
> #2627874 by Rade, DanChadwick: Fixed space used as thousands separator produces validation error.
> #2768023 by kanei, DanChadwick: Fixed allow #element_validate and select options_callback to be a php callables rather than function names.
> #2612844 by tom_ek, DanChadwick: Fixed non-required partial dates fail validation with no value entered.
> #2788591: Added warning about opening CSV files with spreadsheets.
> #2678704 by DanChadwick: Fixed description of disabled components to allow for change via JavaScript or dev tools.
> #2784455 by Roshni Patel, 3rik5: Fixed description displays between field prefix and input for number/text components when above.
> #2644830 by DanChadwick: Standardize name of field's form key to "Form key".
> #2784329 by DanChadwick: Fixed defining conditionals with multiple actions.
> ## Changes since 7.x-4.12
> #2752611 by benjy: Fixed webform_results_download_rows() should take $last_sid by reference.
> #2601546 by BR0kEN: Added improvement to e-mail "exclude_empty" processing.
> #2653664 by jacob.embree: Fixed implement hook_update_dependencies().
> #2612428 by joshi.rohit100: Fixed benign duplicated weight property in select options_source.
> #2620216 by Liam Morland: Fixed _webform_render_component(), use #theme_wrappers.
> #2677818 by nicrodgers: Fixed typo in phpdoc for webform_count_terminals().
> #2677798 by nicrodgers: Fixed documentation in phpdoc for webform_input_vars_check().
> #2677794 by nicrodgers: Fixed documentation in phpdoc for webform_page_labels().
> #2677720 by nicrodgers: Fixed benign duplicate array key in webform_theme.
> #2677786 by hamrant, nicrodgers: Fixed _webform_client_form_add_component phpdoc missing @param documentation.
> #2675910 by burgs: Added support for new Webform views status field formatters.
> #2713781 by dpovshed: Fixed code whitespace style issues.
> #2667102 by joelstein: Don't remove #pre_render when selection components are displayed as list.
> #2759623 by DanChadwick: Display required and hide weight when no components are defined.
> #2757751 by DanChadwick, PreviousNext: Sub-conditional and/or expressions
> ## Changes since 7.x-4.11
> #2597045 by DanChadwick: Added relax 128 character limit in Conditionals "set to" command to unlimited.
> #2581891 by DanChadwick: Fixed unintended byte order mark in grid.inc.
> #2581891 by DanChadwick: Added advanced grid (multiple choice, conditionals, non-homogeneous options).
> #1463364 by DanChadwick: Added option to move grid title to first row header.
> #2580221 by amoebanath: Fixed unfiltered form display still applies conditionals.
> #2555051 by DanChadwick, greggles: Added sanitize private data in webform_submitted_data.
> #2577259 by DanChadwick: Added allow tokens to be disabled.
> #2581685 by DanChadwick: Fixed component delete confirmation assumes fieldset.
> #2574577 by DanChadwick: Fixed regression in no results behaviour not triggered for Webform Value fields in views.
> #2579227: Fixed setting a conditional rule to 'is empty' breaks subsequent operators.
> #2578583 by DanChadwick: Fixed conditional code cleanup (no functional change).
> #1133958 by DanChadwick: Added the "Field Key" column to the component table.
> #2577649 by DanChadwick and emek: Fixed values from grid component don't get included in emails when excluding empty values.
> #2560339 by DanChadwick: Fixed webform 3.x to 4.x upgrade when views is disabled.
> #2555853 by DanChadwick: Added warning that component must be Required if required is conditionally set.
> #2575903 by DanChadwick: Fixed conditional form shows set-to operand when it shouldn't.
> #2575901 by DanChadwick: Fixed conditional definition validation incorrect.
> #2575875 by DanChadwick: Added drush command webform-clear to clear submissions.
> #2563467 by DanChadwick: Fixed cannot clear a large number of submissions.
> #2574577 by DanChadwick: Fixed no results behavior not triggered for in views of webform fields.
> #2566017 by DanChadwick: Fixed wfx range-type='new' doesn't set last-downloaded sid.
> #2573523 by DanChadwick: Added number validation reg ex comments.
> #2573523 by DanChadwick: Added allowing numbers starting or ending with a decimal.
> ## Changes since 7.x-4.10
> #2568637 by DanChadwick: Fixed download of multiple select options with key of 0 shows always checked.
> #2555119 by DanChadwick: Provide session when any submission link has passed token access.
> #2565063 by TAT_Audaxis: Fix fatal error when Email component is a Conditional target.
> #2562703 by DanChadwick: Fixed Multistep + File Input = Duplicate Submissions.
> #2555683 by dagmar: Fixed hook_webform_exporters and hook_webform_exporters_alter are not documented
> #284431 by bjmiller121, DanChadwick: Add option to place descriptions above fields.
> #2544990 by DanChadwick: Fixed PHP notices in webform_submission_create with multipage webforms.
> #2542796 by DanChadwick: Fixed markup components on multi-page webform causes watchdog warnings.
> #2538716 by acrollet: Added make original submission data available to modules implementing hook_webform_submission_update.
> #2541948: Fixed JavaScript webform.dateValue docblock is wrong.
> #2539954 by DanChadwick: Fixed whitespace coding standard nonconformance.
> #2536426 by DanChadwick: Fixed position fieldset is incorrectly displayed in "Select options" component edit page.
> #2535378 by DanChadwick: Fixed invalid argument in foreach in webform_format_email_address().
> #2533010 by rv0, DanChadwick: Added support exporting with alternative line endings (e.g.: CRLF).
> #2535066 by asct, DanChadwick: Fixed conditionals watchdog logging format incorrect.
> ## Changes since 7.x-4.9
> #2532878 by dunix: Fix drush component option description and allow for using form keys in component option.
> #2517090 by DanChadwick: Conditionally set values should be validated.
> #2529246 by amoebanath: Includes missed when loading submission, with entitycache installed (revised).
> #2532426 by DanChadwick: Conditional Set sometimes sets only first letter.
> #2529246 by amoebanath, DanChadwick: Includes missed when loading submission, with entitycache installed.
> #2495821 by DanChadwick: Fixed duplicate ID for file field.
> #2528908 by DanChadwick: Webform Conditionals not showing on preview or results when testing select component with "is or is after" or "after" with numeric key.
> #2530588 by agoradesign: Fixed hook_webform_submission_create function name in webform.api.php.
> #2531842: Conditional on select with no value matches is and is-after.
> #2510216: Tests are failing due to static caching in webform_node_types.
> #2501437 by Chris Burge: Fixed Views Field Handlers permission for results link.
> #2482659 by DanChadwick, quicksketch: Added ability to use submission tokens in markup components.
> #2501437 by Chris Burge, DanChadwick: Views Field Handlers Should Check if Content Type is Webform Enabled.
> #2500705 by Chris Burge: Added data-label attribute to grid component option td elements.
> #2498699 by sumitmadan: A component of type Number cannot be "set to"
> #2485371 by sumitmadan, DanChadwick: Added ability to disable Webform email recipients.
> #2503187 by fenstrat: Set webform_node_types_primary variable if webform content type is skipped on install
> #2498925 by sumitmadan: Typo "much" log out

**Comment by tobybellwood** [comment]
closing in favour of #529
