### ISSUE TITLE
Module Update: Webform Phone Number

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#452]
Available version: 7.x-1.23
Current version: 7.x-1.21

> ## Changes since 7.x-1.22
> Added HTML5 required attribute to webform_phone component. - Patch by: idebr.
> ## Changes since 7.x-1.21
> Fix for issue 2464305; added support for using Webform Phone field as the source for a conditional.

**Comment by tobybellwood** [comment]
closing in favour of #529
