### ISSUE TITLE
Module Update: Wysiwyg

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#453]
Available version: 7.x-2.3
Current version: 7.x-2.2+58

**Note: Some of the below changes are already available as we're running a development version**
> ## Changes since 7.x-2.2
> Removed unused stylesheets.
> #1968318 by TwoD, mglaman, Inzor, ofry, rocketeerbkw, et al: TinyMCE 4 support.
> #2375679 by Twod, rocketeerbkw: Improved profile management.
> Added note about JSON settings and a helper function for validation.
> #2289683 by TwoD, JurriaanRoelofs: Fixed notice when saving theme settings.
> Added support for CKEditor version 4.6.1.
> #1671030: Updated CHANGELOG.txt.
> #1963766 by TwoD, agoradesign, BWPanda: Improved support for paste related options.
> #2800063 by temkin: Fixed misleading Editor Appearance options for TinyMCE.
> #2289683 by TwoD: Added the ability to select the in-editor theme.
> #2828802 by Marialoann, TwoD: Fixed filtering of ajax_html_ids adding selectors back.
> #2829260 by Miles Ulrich: Fixed #828718 is generating 404 errors for CSS files.
> #2415623 by googletorp, jansete: Added hook_wysiwyg_editor_alter().
> #2821817 by jenna.tollerson: Added CKEditor specific note to plugin documentation.
> #828718 by theunraveler, danbohea, BrightBold, jonraedeke, colinstillwell88, jennifer.chang, et al.: Fixed hard .css setting cache: how to clear the cache?
> #2821903 by prince_zyxware: Documentation - Spacing issues
> Removed bulk-detaching of editors based only on context.
> Fixed non-empty initial content in jWYSIWYG.
> Dropped TinyMCE 2 support.
> #970892 by TwoD: Dropped openWYSIWYG support.
> #2802769 by prince_zyxware: Fixed coding standard for PHP NULL.
> #2711597 by awebmanager, sillo, TwoD: Added link to supported editor versions.
> #2656266 by loopduplicate: Fixed trailing comma on object literal.
> #2639738 by TwoD: Fixed internal instance tracking for CKEditor.
> #2614826 by lucas.constantino: Fixed CKEditor stylesSets being re-registered too.
> #2614826 by lucas.constantino, TwoD: Fixed registering new plugins after AJAX updated settings.
> Fixed accidental removal of TinyMCE's cross-editor plugin support.
> Added missing implementations for isFullscreen method.
> #923460 by TwoD, ph0enix, jonhattan, rpayanm: Fixed jWYSIWYG website and release package structure.
> #1207170 by TwoD: Whizzywig no longer needs xhtml.js.
> #1230708 by droplet, rpayanm: Fixed mismatched button names.
> #1996626 by delphian: Libraries located in base profiles are not accessible
> #2566175 by eyeless: Drupal.settings.wysiwyg.plugins being overridden on AJAX calls
> #2243413 by TwoD: Fixed AJAX state syncing by isolating editor instances.
> #2522462 by brad.bulger: Fixed empty excludeSelectors array causes JS exception.
> #2496419 by maximpodorov, elpino: Fixed trying to load CSS files removed by the theme.
> #2513712 by rrfegade: Fixed spelling errors.
> #2493443 by TwoD: Added a method of filtering the ajax_html_ids to avoid too many parameters in the request.
> #1081432 by TwoD, arjenlentz: Added primary index to {wysiwyg_user} table.
> By TwoD: Attach a 'none' instance if summary is hidden to have consistency.
> By TwoD: Fixed undefined variable '$field' for Whizzywig.
> By TwoD: Fixed JavaScript variables being created globally.
> #2493433 by TwoD: Fixed EpicEditor instance removed during AJAX opration.
> #2352847 by aaronbauman: Fixed wysiwyg_status button shows on other account edit forms.
> Fixed unnecessary #element_validate callback in the TinyMCE form.
> Improved behavior when wysiwyg.js is included twice.
> Refactored wysiwygAttach(), wysiwygDetach() and #resizable handling.
> Reworded filter recommendations in readme.
> Fixed another regression introduced by #2284955.
> Removed trailing comma to please older browsers.
> Disabled AutoInline mode for CKEditor.
> #2292913 by TwoD: Fixed error when the default format has no editor.
> #594322 by TwoD: Fixed caret position after inserting content in NicEdit.
> #2284955 by TwoD: Fixed detaching when closing CTools Modals.
> #2285913 by jeffam, TwoD: Added option to toggle editors for summary fields.
> Fixed minor issues with editor state tracking during AJAX calls.
> #1038336 by TwoD: Fixed missing editor toggler when using a single format.
> #1927968 by TwoD: Fixed CKEditor insert method in WebKit browsers.
> #741606 by muriqui, plach, smk-ka, TwoD: Added summary support.
> #507696 by hadsie, kndr, ksenzee, mcarbone, gaele, et al: Automatically adjust initial editor height.
> Fixed textarea grippie sometimes being attached to active editors.
> Fixed CKEditor 4 default skin name.
> #2264719 by TwoD: Added instance methods for EpicEditor.
> #1757684 by TwoD: Fixed JS error when given a removed form as context.
> #2120015 by TwoD: Fixed PHP Notice for CKEditor.
> Added support for JavaScript Function references and Regular Expressions in settings.
> #1855138 by Pere Orga, TwoD: Removed old update functions.
> #2210053 by dasjo, broeker: Fixed toggler link may be created multiple times.
> #2054885 by tswaters, TwoD: Fixed adding blank stylesheet in CKEditor proxy plugin function.
> Adjusted the placement of the "Disable rich-text" link.
> #1793704 by ultimike, zhangtaihao, TwoD: Allow altering of CSS paths.
> #2186591 by joelcollinsdc, TwoD: Fixed disabled formats causing noticed on Admin Menu rebuilds.
> #1956778 by mibfire, rocketeerbkw, guillaumev: Added support for configuring CKEditor's Advanced Content Filter.
> #2177309 by galindus_olidop, TwoD: Fixed names for custom formats in CKEditor.
> #767628 by TwoD, rocketeerbkw: Added installation note for markItUp.
> #1214924 by donquixote, TwoD, Shabana Blackborder: Fixed WYMeditor not saving changed content.
> #2018439 by TwoD: Fixed editor-specific settings shown for all editors.
> #934976 by TwoD: Fixed missing editor when denied access to format selection.
> Added support for hook_admin_menu_map().
> #2043081 by stBorchert, TwoD: Allow sub-pages of profile/edit.
> #1987290 by yannickoo: Changed EpicEditor download URL to epiceditor.com.
> #1987290 by yannickoo: Fixed EpicEditor URLs.
> #1988478 by yannickoo: Added missing semicolon in the EpicEditor integration.
> #1963122 by mgifford, TwoD: Added missing dropdown labels for accessibility on the profile overview form.
> #1967204 by stevejburge, TwoD: Updated URL to the TinyMCE website.
> #474588 by TwoD: Added support for forcePasteAsPlainText in CKEditor.
> #1853550 by rwohleb, chrisrd, jm.federico, klaasvw, yanniboi, TwoD: Added CKEditor 4 support.
> #1861174 by TwoD: Fixed problem with relative URLs in CKEditor introduced in 7.x-2.2.
> #1898210 by TwoD: Fixed Administration menu overlaps editors in fullscreen mode.
> #1531896 by Emmanuel_S, TwoD: Fixed strict warning for CKEditor and OpenWYSIWYG.
> #1617706 by TwoD: Fixed typo in last YUI patch and improved cross-browser compatibility.
> #1617706 by mikeaja, acrollet, cecrs: Fixed YUI Editor implementation crashing when no plugins are enabled.
> #1834472 by sun, TravisCarden, Twod: Use vertical tabs on WYSIWYG profile form.
> #1836074 by TravisCarden, sun: Sort list of editors by installation status and title.
> #1794782 by TwoD: Fixed TinyMCE disappears when switching between formats.
> #1802342 by TwoD, sun: Fixed TinyMCE font plugin buttons are not updated to default plugin.
> #1802394 by TwoD: Fixed Warning: file_get_contents() from 7.2.1 to 7.2.2.

**Comment by tobybellwood** [comment]
PR over at #678 - closing to track there
