### ISSUE TITLE
Module Update: WYSIWYG Filter

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#454]
Available version: 7.x-1.6-rc3
Current version: 7.x-1.6-rc2

> ## Changes since 7.x-1.6rc2
> #1783966: Allow altering of blacklist to enable support of forms, embeds, etc.
> #2575617: Support media attribute
> #1687794: Validation occurs on disabled filter
> #2319949: PHP Fatal error: Call to undefined function wysiwyg_filter_get_elements_blacklist()
> #1543044: Warning: Missing argument 4 for wysiwyg_filter
> #Improved attribute filtering for IE

**Comment by Wongad** [comment]
Have mentioned an issue with the video embed in the WYSIWYG, #450 .
Not too sure which module will be the right solution to enable the [video:URL] command in the WYSIWYG.

**Comment by tobybellwood** [comment]
closing in favour of #529
