### ISSUE TITLE
Errors installing the govCMS distribution on Acquia Cloud Free (and possibly other environments)

### ISSUE THREAD

**Issue by aleayr** [govCMS/GovCMS7#462]
No such issues with our build environment on Github, or the specific platforms, however, I've been made aware that the default theme doesn't activate, and the installation process throws a number of errors on Acquia Cloud Free.

Need to conduct further testing to determine the cause and whether this extends to other environments.

**Comment by cjoneill** [comment]
FWIW I've just spun a completely new free environment with the available build of govCMS; it's installed fine from what I can see?

[screenshot on Imgur after install](http://i.imgur.com/8h9g15Z.png)

If problems are happening with Acquia Cloud Free, the right place to take a support issue is here: https://forums.acquia.com/acquia-products-and-services/acquia-cloud

Regards,
Chris O'Neill
Acquia - Senior Manager of Support, Asia/Pacific/Japan (UTC+10)

**Comment by tobybellwood** [comment]
I'm seeing no issues on any of the Acquia platforms.  Closing
