### ISSUE TITLE
Module update: Acquia Connector

### ISSUE THREAD

**Issue by mgdhs** [govCMS/GovCMS7#477]
Available version: 7.x-2.15 (https://www.drupal.org/project/acquia_connector/releases/7.x-2.15)
Current version: 7.x-3.1 (https://www.drupal.org/project/acquia_connector/releases/7.x-3.1)

> [Acquia Connector](https://www.drupal.org/project/acquia_connector) 7.x-3.x is required to use Acquia Insight with the new Acquia Cloud interface.

It means the module currently shipping with govCMS no longer provides [Acquia Insight](https://docs.acquia.com/acquia-cloud/insight) connection. This is used for uptime and site health in non-factory sites.

**Comment by Chris820** [comment]
Worth noting that the updated Acquia Connector module means that Insights no longer work for multisite installations.
An unfortunate step-backwards. I'm hoping this feature returns in a future release of the module.

**Comment by seanhamlin** [comment]
Agreed this module should be updated too.

**Comment by tobybellwood** [comment]
Available version: 7.x-2.17 (https://www.drupal.org/project/acquia_connector/releases/7.x-2.17)

**2.17 Release notes**
> A minor maintenance release for Acquia Connector for Drupal 7.

Changes since 7.x-2.16:
> - Fixed the bug that was breaking the Status page
> - Updated the migrate form to expect non-2xx response codes from Acquia Cloud as the server side code changed.
> - Fixed up the unit tests so they all pass now and make further development/maintenance easier.

**2.16 Release notes**
> Maintenance release for Acquia Connector for Drupal 7.

Changes since 7.x-2.15:
> Issue #2449165 by irek02, dmitrii: Make smarter parser for .htaccess file
> Get connector block is not visible at the Get Acquia Cloud Free subscription page in the Ember theme.
> Fix the bug when Acquia connector module shows DSM to anonymous user.
> Add help link for the 'fix it now' feature.
> Use of isset() in Acquia SPI's admin permissions check causes false positives for some permissions
> Issue #2467501: Environments can not be deleted
> Issue #2622040: Use password_inc variable
> Issue #2094043 by brad.bulger: Notice: Undefined property: view::$disabled
> Issue #2280919 by Josh Waihi: Lock Acquia SPI hook_boot implementation
> Issue #2289903 by Devin Carlson: Generate signup messages at the page level
> Issue #2596675 by janusman, Stanislav Mixnovich, dmitrii, irek02: To ease debugging, add $_ENV['HTTP_X_REQUEST_ID'] (if present) to outgoing acquia_search URLs

**Comment by tobybellwood** [comment]
closing in favour of #529
