### ISSUE TITLE
Scheduler Workbench Integration - Critical - Unsupported - SA-CONTRIB-2017-39

### ISSUE THREAD

**Issue by Feng-Shui** [govCMS/GovCMS7#485]
Morning all,

"The security team is marking this module unsupported. There is a known security issue with the module that has not been fixed by the maintainer."

https://www.drupal.org/node/2869141

I can't seem to find any information on the issue, I suspect the security team doesn't want to disclose the issue until there is a patch available, but that makes it hard to write a patch :-/

@aleayr do you guys have any insight into what this issue is?

**Comment by nathan-w** [comment]
@aleayr is on holiday at the moment... - @seanhamlin do you have any insights? If not appropriate to comment here as security related, please send me info at work, and I can distribute to @Feng-Shui and relay to our internal security team too.

**Comment by Feng-Shui** [comment]
@nathan-w that'd be good, we can possibly (as a project) reach out to the issue reporter and get the details directly from him so we can patch it, or at least determine the severity of the issue.

**Comment by seanhamlin** [comment]
The drupal.org security team will only communicate security issues with the module maintainer(s). I believe @jozhao has [put his hand up](https://www.drupal.org/node/2869207) (together with another person from the community Andrew). It looks like Andrew has a patch and is testing it. I would expect a new security release shortly.

**Comment by seanhamlin** [comment]
Note, the new maintainer Andrew has released a new version with the fix in it https://www.drupal.org/project/scheduler_workbench/releases/7.x-1.3

**Comment by nathan-w** [comment]
This affects functionality that a number of agencies say is essential for their publishing workflow. Can we get a PR done for this and get this through the CAB process, get all necessary testing completed and roll it out as soon as it's ready. We don't need to rush this change through, but its **HIGH** priority please.

**Comment by tobybellwood** [comment]
Merged in #492
