### ISSUE TITLE
Seckit breaks IE

### ISSUE THREAD

**Issue by kurtfoster** [govCMS/GovCMS7#486]
This issue already exists on do
https://www.drupal.org/node/2374803

We're currently facing this issue on the vic budget site.

**Comment by iggymaphone** [comment]
I agree, we need seckit enabled for the Budget website and IE represents 30% of our users so it needs to work for IE9+.

**Comment by kurtfoster** [comment]
Created a PR here https://github.com/govCMS/govCMS/pull/487
