### ISSUE TITLE
Update scheduler module from 1.3 to 1.5

### ISSUE THREAD

**Issue by klonos** [govCMS/GovCMS7#488]
There's this issue that came up with the rebuild/migration of the old ANZACATT site (Australia and New Zealand Association of Clerks-at-the-Table) to a new govCMS-based site...

There is this error message:

`Warning: trim() expects parameter 1 to be string, array given in _scheduler_strtotime() (line 957 of /docroot/profiles/govcms/modules/contrib/scheduler/scheduler.module).`

It comes up after hitting the preview button on the node edit form **but only if the following conditions are met**:

1. The node type needs to be set to allow scheduled publishing/unpublishing.
2. The date fields need to be set to use the datepicker
3. Happens only with existing content; not when previewing content to be created.

Manually upgrading the Scheduler module from the stock version 1.3 that comes with the current version of govCMS ([released back in November 2014](https://www.drupal.org/project/scheduler/releases/7.x-1.3)) to the most current 1.5 solves the issue.

---
PR: https://github.com/govCMS/govCMS/pull/489

**Comment by klonos** [comment]
Steps to reproduce:

1. Install a fresh copy of latest govCMS 7.x-2.10 and make sure you enable the default example content at the last step.
2. Navigate to the content listing page under `/admin/content`
3. Find a random piece of content like say a publication and edit it.
4. Don't need to actually change anything; just hit the preview button: 👎 

![screen shot 2017-04-18 at 4 38 54 pm](https://cloud.githubusercontent.com/assets/2423362/25117447/8cc768cc-2455-11e7-9688-11411610c756.png)

Now, either manually replace the included version of scheduler under `/profiles/govcms/modules/contrib` with a copy of the latest 1.5 version from https://www.drupal.org/project/scheduler , or if you prefer clone the repo, merge my PR changes locally and build govCMS afresh. Repeat the STR above: no error message 👍

**Comment by tobybellwood** [comment]
Merged in #492
