### ISSUE TITLE
Request to apply Seckit patch for incorrect format of X-Frame-Options header

### ISSUE THREAD

**Issue by geek-boy** [govCMS/GovCMS7#491]
There is an issue with the X-Frame-Options header where a colon character ":" is incorrectly added to the header output.

There is a patch in https://www.drupal.org/node/2779169 and https://www.drupal.org/node/2811351. Can this patch be applied to the Seckit module as part of GovCMS ?

**Comment by thisisalistairsaccount** [comment]
These have been applied previously for 7 and 8/9 seckit modules.

7 distro is running 1.11 and 9 is running 2.0.0.
