### ISSUE TITLE
Update userprotect module from 1.1 to 1.2

### ISSUE THREAD

**Issue by klonos** [govCMS/GovCMS7#493]
Yet another issue caused by an out-of-date module that surfaced in the new ANZACATT site (same as #488). When trying to bulk delete or update values using the default listing views for content etc provided by admin_views, there is a series of these messages:

`Notice: Trying to get property of non-object in userprotect_get_user_protection() (line 878 of /docroot/profiles/govcms/modules/contrib/userprotect/userprotect.module).`

...followed by a single instance of this:

`Warning: Invalid argument supplied for foreach() in userprotect_get_user_protection() (line 931 of /var/beetbox/docroot/profiles/govcms/modules/contrib/userprotect/userprotect.module).`

Manually upgrading the User protect module from the stock version 1.1 ([released back in August 2014](https://www.drupal.org/project/userprotect/releases/7.x-1.1)) that comes with the current version of govCMS to the most current 1.2 solves the issue.

Related d.org issue: https://www.drupal.org/node/2380591

---
PR: https://github.com/govCMS/govCMS/pull/494

**Comment by tobybellwood** [comment]
Merged in #408
