### ISSUE TITLE
Media - Moderately Critical - Multiple vulnerabilities - SA-CONTRIB-2017-044

### ISSUE THREAD

**Issue by mgdhs** [govCMS/GovCMS7#496]
https://www.drupal.org/node/2877316

> Versions of this module prior to 7.x-2.1 or 7.x-3.0-alpha5 did not sufficiently whitelist input parameters for the media browser.

> This vulnerability in the versions of media prior to those aforementioned is mitigated by the fact that an attacker must have a role with the permission upload files and view media browser.

> If you use the media module, it is recommended to upgrade to media version 7.x-2.1 (stable)

**Comment by seanhamlin** [comment]
Agree we should update the media module.

Seeing as you need to have a user account with permission to upload files and view the media browser, no public sites are in any immediate danger, but I still would like to see this patched.

**Comment by tobybellwood** [comment]
Version 2.2 just released (https://www.drupal.org/project/media/releases/7.x-2.2) - 

> As of Media 2.1, the parameters sent to the media browser are whitelisted instead of blacklisted. One parameter, "render_multi_edit_form", is needed for the media_bulk_upload / multiform integration, and is not in the whitelist.

**Comment by tobybellwood** [comment]
And again to Version 2.3 (https://www.drupal.org/project/media/releases/7.x-2.3)

> missing square_thumbnail causes Broken images in media browser and file/thumbnail
