### ISSUE TITLE
Module Update: Picture

### ISSUE THREAD

**Issue by gargsuchi** [govCMS/GovCMS7#499]
Available version: 7.x-2.13 (https://www.drupal.org/project/picture/releases/7.x-2.13)
Current version: 7.x-2.9

Changes since 7.x-2.12:

#2570461 by Kristen Pol: Update warning: Undefined index: colorbox picture.install:189
#2450863 by jnettik, Bobík, rolfmeijer, giupenni, supermoos: Option to only use img with srcset
#2443319 by netbek, attiks: Field formatter settings not deleted on uninstall
#2565333: Lazy load support triggering undefined index notices

Changes since 7.x-2.11 (12 commits):

#2555233 by marcvangend: Picture + Media: cannot link image to node
#2450863 by jnettik, Bobík, giupenni, rolfmeijer, supermoos: Option to only use img with srcset
#2556981 by RavindraSingh: few potential issues which needs to be fixed
#2561461: undefined index:class in theme_picture
#2561445 by pixelwhip: Sizes text field has a maxlength of 128 set by default
#2562493 by balis_m: Notice: Undefined index: timestamp in theme_picture_formatter()
#2513714 by Deciphered: CTools plugin issue
#2514354 by ore: PHP warning on Parse error on nbsp's for simplexml load string
#2467585: Link pictures to styled image
#2543834: Undefined property: stdClass::$fallback in flexslider_picture.module on line 246
#2539020 by das-peter: Media (WYSIWYG) / File entity css classes missing
#2491101 by sergesemashko, Baysaa: Implement image lazy load

Changes since 7.x-2.10:

#2273249 by curiosity26, artem.vilkov: Upgrade issue 1.3 to 2.0
#2506389 by nbouhid: Empty fallback image generates a wrong path
#2499065 by Dave Reid: Add picture-mapping-flush Drush command

Changes since 7.x-2.9:

#2456671 by Dave Reid: Add support for cache busting query string
#2401675 by dtamajon: Markup string translation
#2362253 by David Sparks: PHP5.3 fatal error when $variables['path'] is a string rather than an array
#2417939 by brockfanning: Pass correct parameter to picturefill()
#2443295 by netbek: 'picture_polyfill_version' variable not deleted on uninstall
#2403429 by rodrigoaguilera: PDO Integrity constraint [error] violation: 1062 Duplicate entry 'image__default__file_field_picture' for key 'PRIMARY'
#2491293 by Baysaa: "attributes" not passed from theme_picture_formatter to theme_picture
Fixed #2449033, #2280315: Use src as fallback
Fixed #2449033: Always output sizes
Updated to picturfill 2.3.1
#2456057 by charlietoleary: Picture field formatter: #states not working

**Comment by gargsuchi** [comment]
PR - https://github.com/govCMS/govCMS/pull/500

**Comment by tobybellwood** [comment]
Thanks @gargsuchi!

**Comment by tobybellwood** [comment]
Merged in #517!
