### ISSUE TITLE
Alt and title fields were not showing up correctly for some images

### ISSUE THREAD

**Issue by gargsuchi** [govCMS/GovCMS7#504]
More details of the issue here:

https://www.drupal.org/node/2882958

**Comment by tobybellwood** [comment]
Hi @gargsuchi - given than 2.1 is now available (and recommended for other module dependencies) https://www.drupal.org/project/file_entity/releases/7.x-2.1 - can you see if this is still an issue?

**Comment by gargsuchi** [comment]
Yes, this is still an issue.

http://cgit.drupalcode.org/file_entity/tree/file_entity.file.inc?h=7.x-2.x

**Comment by gargsuchi** [comment]
I just uploaded 2 new patches against develop for both D7 and D8. Can someone RTBC it please?

@seanhamlin @gollyg

**Comment by seanhamlin** [comment]
I honestly do not know enough about the file_entity module to RTBC that issue, from the looks, it appears that the file_entity module caters to token and the entity_api and the tokens are slightly different depending on combinations.

**Comment by gargsuchi** [comment]
The D7 patch at https://www.drupal.org/node/2882958 has been accepted. I think we should also upgrade the module as and when a newer stable release comes out.
