### ISSUE TITLE
Updating contrib modules

### ISSUE THREAD

**Issue by mstrelan** [govCMS/GovCMS7#52]
What is the release schedule for updating contrib modules that don't have a security issue? Specifically I am aware of a few relevant bug fixes in new versions of Big Menu, Date and LinkIt. Is it recommended to just update these in sites/all/modules?

**Comment by fiasco** [comment]
Hi @mstrelan, if you're happy to, please file pull requests for each module to update the drush make file to the latest versions. From there, each one will be reviewed by the community and merged in if applicable.

Normally, we release on two major events - Security Updates or feature changes added. If there are people using govCMS and these bugs are causing pain, please provide some insight to that in the pull request so we can evaluate if it makes sense to make a release.

**Comment by fiasco** [comment]
I see you've filed some pull requests so I'll go ahead and close this issue off thanks!
