### ISSUE TITLE
Generate automatic URL alias does not remain checked

### ISSUE THREAD

**Issue by roflcopterDorrie** [govCMS/GovCMS7#539]
Steps to replicate (on fresh govCMS install):
 - Create new Standard page
 - Checked that 'Generate automatic URL alias' is checked
 - Save and Publish
 - The alias is created correctly
 - Create a new draft of that page
 - 'Generate automatic URL alias' is no longer checked
 - Saving will not generate a new alias

This is an issue for the following reasons:
 - If the user changes the title, the URL is not automatically updated
 - If the URL pattern are updated, you cannot regenerate all the aliases via 'Delete aliases' and 'Bulk generate'

The patch in https://www.drupal.org/node/2616854#comment-11334951 seems to work correctly when applied.

Could we get this patch included please?

**Comment by Chris820** [comment]
We used to get this problem on our PaaS sites occasionally too. 
Even back when the PathAuto Persist functionality was included into PathAuto - it would still happen.

After we upgraded to Workbench Moderation 3.0 it seems to be much better. I would recommend this over patching 1.4.

**Comment by tobybellwood** [comment]
We've had a bit of discussion about the Workbench Moderation upgrade to 3.0 (#376 and #392)

We'll have a look into it - some of the issues around the 3.0 update (particularly around the changed workflow) are a cause for concern, particularly with such a diverse portfolio of sites running on the SaaS platform.

**Comment by roflcopterDorrie** [comment]
Agreed, I think upgrading to 3.0 is the smarter solution in the long term. Going to close in light of going to v3.0.

**Comment by rooby** [comment]
@tobybellwood any chance we could revisit applying this patch if it does work?

It's quite a frustrating issue and at this stage that other moderation stuff Doesn't seem like it's going to make it into a release any time soon.

**Comment by rooby** [comment]
There also doesn't really seem to be a way to work around it with alter hooks and whatnot.

Since it is essentially data corruption it's fairly major.
