### ISSUE TITLE
Views - Moderately Critical - Access Bypass - DRUPAL-SA-CONTRIB-2017-068

### ISSUE THREAD

**Issue by fiasco** [govCMS/GovCMS7#546]
Advisory ID: DRUPAL-SA-CONTRIB-2014-0XX
Project: Views (third-party module)
Version: 7.x, 8.x
Date: 2017-August-16
Security risk: 14/25 ( Moderately Critical) AC:None/A:None/CI:Some/II:None/E:Theoretical/TD:Default
Vulnerability: Access bypass

See https://www.drupal.org/node/2902604 for more details.

**Comment by tobybellwood** [comment]
see #548

**Comment by mgdhs** [comment]
Can we close this @tobybellwood?

**Comment by tobybellwood** [comment]
yup - sorry we missed this!
