### ISSUE TITLE
Entity Reference - Moderately Critical - Access Bypass - DRUPAL-SA-CONTRIB-2017-067

### ISSUE THREAD

**Issue by fiasco** [govCMS/GovCMS7#547]
Advisory ID: DRUPAL-SA-CONTRIB-2017-067
Project: Entity reference (third-party module)
Version: 7.x
Date: 2017-August-16
Security risk: 12/25 ( Moderately Critical) AC:Basic/A:None/CI:Some/II:None/E:Theoretical/TD:Default
Vulnerability: Access bypass

More details: https://www.drupal.org/node/2902596

**Comment by tobybellwood** [comment]
see #533

**Comment by seanhamlin** [comment]
Fixed.
