### ISSUE TITLE
Enabling Google Tag Manager on the govCMS distro

### ISSUE THREAD

**Issue by mpigott** [govCMS/GovCMS7#551]
I hope this isn't too dumb a question, but how do I set up Google Tag Manager on the govCMS distro? 

Is it a case of placing the 2 Google Tag Manager code snippets into the PHP templates? 

Is there a case for adding the [Google TagManager module](https://www.drupal.org/project/google_tag) to the distro for non-techies like me?

**Comment by tobybellwood** [comment]
Hi @mpigott,

We've no plans to include the TagManager module into the distro.  Any decision to include the code snippets onto your site should be done with full awareness of the risks involved - which do require a fair few process mitigations.  You'll need to conduct an individual agency risk assessment.

Happy to discuss further offline if you want.
