### ISSUE TITLE
As a content editor I would like to have more control over image cropping

### ISSUE THREAD

**Issue by rooby** [govCMS/GovCMS7#552]
It would be useful to have some sort ability to have more control over the cropping of images, either by manually selecting a crop or setting a focal point.

In terms of usefulness to the largest number, I feel like selecting a focal point is more flexible than manually cropping things, since you can then set up all sorts of different croppings in image styles based on the focal point.

So in that case, the focal point module is the one I would propose: https://www.drupal.org/project/focal_point

**Comment by tobybellwood** [comment]
Hey @rooby - one step ahead of you
![image](https://user-images.githubusercontent.com/4373945/29849482-6eb37802-8d6a-11e7-9c74-f4217205d8ec.png)

Let us know if you have difficulties with it...

**Comment by tobybellwood** [comment]
Closing answered :-)

**Comment by rooby** [comment]
Awesome, thanks.
