### ISSUE TITLE
As a site builder I would like more control over customisation of WYSIWYG editors

### ISSUE THREAD

**Issue by rooby** [govCMS/GovCMS7#590]
The WYSIWYG module doesn't provide all that many options for customising the editing experience via the UI.

Often they recommend the use of hook_wysiwyg_editor_settings_alter(), however that isn't currently feasible in GovCMS due to not having any ability to customise the administration theme (unless I'm wrong about that).

Possible solutions off the top of my head might be:
 * Allow a custom admin theme, which could be a sub theme of the current admin theme.
 * Some sort of custom GovCMS solution to allow altering these settings via an admin UI page or via a special function in the default theme.

**Comment by mgdhs** [comment]
Maybe with a Factory (SaaS) site you should get a single custom module repo for a 'utility module' along with your theme repo. That way you could do this, formatters and lots of other things that can't be done in the theme. It would introduce a bit of risk, but you could solve lots of problems with it.

**Comment by fubarhouse** [comment]
We do this a bit, so it's an interesting case.

We've got a composer files with a bunch of specific CKEditor plugins which we go through and test and release. In addition to this, a website can specify a location for a configuration file for more advanced features.

So, I could have a discussion about how it works on PaaS

But, on SaaS there's additional risk to both the agency and Finance. It would generate a bunch of work on demand for Finance staff - it should work like themes do, but it is a physical piece of work with associated risks.

**Comment by rooby** [comment]
When I originally opened this issue I didn’t realise that it was ok to create an admin theme sub-theme on SaaS.

That realisation means that I can now do what I wanted to do. There could still be scope for some sort of UI but being able to use that WYSIWYG hook for the admin theme is sufficient and it would be extra work to implement a UI that I don’t think should or would be a priority so this can probably be closed.

**Comment by fubarhouse** [comment]
Provided you're never going to need additional CKEditor plugins, that's a clean solution!
