### ISSUE TITLE
Install on php7.1 gives error in libraries_detect()

### ISSUE THREAD

**Issue by tobybellwood** [govCMS/GovCMS7#593]
![image](https://user-images.githubusercontent.com/4373945/33196054-0cfdb338-d131-11e7-8e58-819db7d5d776.png)

Warning: Parameter 1 to _navbar_libraries_get_version() expected to be a reference, value given in libraries_detect() (line 549 of /mnt/www/html/ckandemodecdzfgw83qhlk/docroot/profiles/govcms/modules/contrib/libraries/libraries.module).

This error is caused by installing govCMS on php7.1.  Acquia Cloud allows you to switch php back to 5.6, but we should probably address this.

**Comment by tobybellwood** [comment]
PR in #635

**Comment by rooby** [comment]
Now that the patch has been committed, we can update libraries to the latest version and ditch the patch.
