### ISSUE TITLE
Feeds Tamper incompatible with PHP 7.1

### ISSUE THREAD

**Issue by pandaskii** [govCMS/GovCMS7#607]
> Fatal error: Redefinition of parameter $source ... /profiles/govcms/modules/contrib/feeds_tamper/plugins/default_value.inc on line 36 

Similar PHP 7.1 related issues

- https://github.com/govCMS/govCMS/issues/587

- https://github.com/govCMS/govCMS/issues/593

**Comment by seanhamlin** [comment]
`feeds_tamper` has a 1.2 release, to which addresses this I think https://www.drupal.org/project/feeds_tamper/releases/7.x-1.2
