### ISSUE TITLE
Access automation testing report

### ISSUE THREAD

**Issue by pandaskii** [govCMS/GovCMS7#618]
![screen shot 2017-11-29 at 14 21 14](https://user-images.githubusercontent.com/1326673/33356448-9956e4de-d510-11e7-9deb-001fc9471913.png)

We know something wrong about the checks but cannot access the details.

**Comment by tobybellwood** [comment]
Should be fixed now - using pattern: http://govcms.xyz:8000/blue/organizations/jenkins/govcms_pull_request_builder/detail/govcms_pull_request_builder/$ghprbPullId/pipeline
