### ISSUE TITLE
Consider ckeditor_link module over linkit

### ISSUE THREAD

**Issue by mstrelan** [govCMS/GovCMS7#62]
While [LinkIt](https://www.drupal.org/project/linkit) provides a fairly rich interface, I have found that it can be confusing having the standard Link/Unlink buttons towards the left of the CKEditor toolbar, and the LinkIt button all the way on the other side. [CKEditor Link](https://www.drupal.org/project/ckeditor_link) provides similar functionality, but merges with the existing Link button. Has this been considered as an alternative?

Other points to consider
- CKEditor Link also provides a text filter comparable to Pathologic
- LinkIt is [currently incompatible](https://www.drupal.org/node/2550845#comment-10351297) with editing Paragraphs that have been loaded via ajax (ie. after pressing edit)

**Comment by aleayr** [comment]
Certainly worth having further discussion around, or more likely, how to solve the LinkIt issues so we can keep using it I imagine.

One of the aspects I like about LinkIt is being able to see the author and last modified date at a glance on similarly named pages, but do note the additional button in the interface that users need to be aware is there.

That paragraphs issue is certainly annoying. Does hurt the experience, especially with some sites using paragraphs quite extensively.

**Comment by fiasco** [comment]
Since we already run LinkIt, and we currently have sites running on govCMS, this change could potentially break functionality for those already using this part of govCMS. I think the first preference here would be to make LinkIt work better which is probably something to handle in the LinkIt issue queue. Are there are least issues in that queue to address the issues @mstrelan raised?

**Comment by mstrelan** [comment]
- [Merge link and LinkIT buttons](https://www.drupal.org/node/1453140)
- [Allow to sort editor buttons](https://www.drupal.org/node/277954)
- LinkIt / Paragraphs incompatibility is discussed in #63

**Comment by fiasco** [comment]
Do we have a pull request for this? @teamglenny - would also be good to get you input here.

**Comment by aleayr** [comment]
Do people think this is still worthwhile discussing, especially since PR #161 from @mstrelan when this merges in will solve the longstanding LinkIt issue.

I'm going to close this off, but if we still think it has value, please reopen it and discuss.
