### ISSUE TITLE
composer fail at 'Installing phantomjs

### ISSUE THREAD

**Issue by rsau** [govCMS/GovCMS7#624]
running `composer install --prefer-dist --working-dir=build` fails

``` 
> PhantomInstaller\Installer::installPhantomJS
  - Installing phantomjs (1.9.8): Downloading (failed)
Downloading (failed)
Downloading (failed)Script PhantomInstaller\Installer::installPhantomJS handling the post-install-cmd event terminated with an exception


  [Composer\Downloader\TransportException]
  The "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2" file could not be downloaded: Peer certificate CN=`*.s3.amazonaws.com' did not match expected CN=`bitbucket.org'
  failed to open stream: Cannot connect to HTTPS server through proxy

```

It looks like proxy error as we are behind proxy but other package installs working fine so I am not sure if this is our proxy. 

I know that issue is not directly related to govcms but has anybody else came across this issue?

Thanks

**Comment by Podgkin** [comment]
Do you still get an error at all if you try the same thing outside your proxy? Sometimes proxies can be... *discerning* about blocking specific things and not others

**Comment by tobybellwood** [comment]
Unable to reproduce - assume proxy error.
