### ISSUE TITLE
List of modules included with the distribution?

### ISSUE THREAD

**Issue by klonos** [govCMS/GovCMS7#625]
Where can one get a list of already included modules and also any considered for inclusion in future releases (like a roadmap of some sort)?

**Comment by Podgkin** [comment]
The [drupal-org.make file](https://github.com/govCMS/govCMS/blob/7.x-2.x/drupal-org.make) has a current list of modules. There is also a [module list on the govCMS community](https://community.govcms.gov.au/t/list-of-current-modules-in-the-govcms-distro/322/10) with descriptions.  To get an idea about future releases there is a [govCMS roadmap on Trello](https://trello.com/b/2zz6gfWg/govcms-roadmap-public).

**Comment by tobybellwood** [comment]
As @Podgkin said ^^, noting that we've moved the list to https://www.govcms.gov.au/govCMS-d7-modules 

As for roadmap modules, we'll always take suggestions here or at https://community.govcms.gov.au/c/Suggested-Enhancements 

We're trying to be more transparent around the process, but the reality is that we'll only really add new modules that have wide potential for usage, especially as we meander towards a LTS version of govCMS...
