### ISSUE TITLE
LinkIt and Paragraphs compatibility issue

### ISSUE THREAD

**Issue by mstrelan** [govCMS/GovCMS7#63]
As mentioned in #62, LinkIt is [currently incompatible](https://www.drupal.org/node/2550845#comment-10351297) with editing Paragraphs that have been loaded via ajax.

To reproduce this:
1. Ensure you have a Paragraphs bundle with a field that has a WYSIWYG attached to it
2. Ensure you have a content type with a paragraphs item field with the default edit mode set to "closed" or "preview"
3. Create a new node and add at least one paragraphs item with a wysiwyg
4. Save the node
5. Edit the node, Click "Edit" on the paragraph, Click the LinkIt button

I have submitted a [patch](https://www.drupal.org/node/2550845#comment-10355269) to LinkIt but it has not yet had any response. It is possible to workaround this issue using `hook_element_info_alter()`. 

I will submit two pull requests, one working around the issue in the govcms_editing feature module, and the other applying the patch to LinkIt.

**Comment by teamglenny** [comment]
Giving this a nudge if anyone can have a look.

**Comment by invisigoth** [comment]
@jozhao and I just tried to reproduce this issue and it appears lacking a Linkit profile when setting up the Paragraphs field is the cause of this issue.

Maybe an easier fix is to define and attach a Linkit profile to the Paragraphs field after the field is defined? Please try the following:
- Admin > Configuration > Linkit Profiles
- Clone the existing WYSIWYG profile and name it something like "WYSIWYG-PARAGRAPH"
- Be sure to choose "This profile will be used with: Fields"
- Under Insert Methods > Insert plugin > choose "Raw URL" and save
- Admin > Structure > Paragraph Bundles
- edit bundle > Manage fields
- Edit the fields you created under Paragraphs bundle, tick "Enable Linkit for this field" and pick the above created profile "WYSIWYG-PARAGRAPH" from the dropdown
- Save

In our test this fixed the JS issue and we are able to use the Linkit function on the Paragraphas field with a WYSIWYG.

**Comment by mstrelan** [comment]
"Enable LinkIt for this field" is intended for text fields and link fields to reference content. In fact, it explicitly states in the field description, "Do not use this for CKeditor and TinyMCE fields."

Nonetheless, this issue has been resolved in LinkIt 7.x-3.5.

**Comment by pandaskii** [comment]
It is always good that such issue can be resolved from contrib module itself

If anyone can do a manual testing on https://github.com/govCMS/govCMS/pull/161

I did a local test - all good unless Google Chrome incognito mode (maybe another bug and this mode is with less impact)
