### ISSUE TITLE
Social links block broken with PHP 7.1

### ISSUE THREAD

**Issue by rooby** [govCMS/GovCMS7#649]
The social links block just prints 'A' and throws these errors:

> Warning: Illegal string offset 'twitter' in govcms_social_links_block_view() (line 161 of profiles/govcms/modules/custom/govcms_social_links/govcms_social_links.module).
> Notice: Array to string conversion in govcms_social_links_block_view() (line 161 of profiles/govcms/modules/custom/govcms_social_links/govcms_social_links.module).
> Warning: Illegal string offset 'youtube' in govcms_social_links_block_view() (line 161 of profiles/govcms/modules/custom/govcms_social_links/govcms_social_links.module).
> Notice: Array to string conversion in govcms_social_links_block_view() (line 161 of profiles/govcms/modules/custom/govcms_social_links/govcms_social_links.module).

**Comment by fubarhouse** [comment]
+1

You can get around this temporarily by changing this:
```php
$block['content'] = '';
```
To this:
```php
$block['content'] = array();
```

It's on line 145. PHP 7.1 is stricter with types which is actually a huge positive move, but it appears that it's causing a problem in this situation. Understandably, a variable should be declared as the type intended for use, or `NULL` if absolutely needed.

There's another incompatibility producing the following error in the installation wizard, but it doesn't really hinder anything. I assume that would be covered here too:
````
Notice: Undefined index: hook in defaultconfig_component_rebuild() (line 317 of /vagrant/sites/govcms/docroot/sites/all/modules/contrib/defaultconfig/defaultconfig.module).
Notice: Undefined index: hook in defaultconfig_component_rebuild() (line 320 of /vagrant/sites/govcms/docroot/sites/all/modules/contrib/defaultconfig/defaultconfig.module).
Warning: Illegal offset type in isset or empty in defaultconfig_defaultconfig_component_alter() (line 517 of /vagrant/sites/govcms/docroot/sites/all/modules/contrib/defaultconfig/defaultconfig.module).
````

**Comment by tobybellwood** [comment]
Sorry about not getting this linked earlier - we've got PR #647 in to fix this!
