### ISSUE TITLE
With CKEditor, the spell check plugin breaks the superscript button

### ISSUE THREAD

**Issue by rooby** [govCMS/GovCMS7#652]
The default GovCMS configuration enables the spell checker functionality in the WYSIWYG.

If you also enable the superscript button, the superscript button will not work unless you disable the spell checker (see https://www.drupal.org/project/wysiwyg/issues/2948597).

Since browsers have their own spell checking already, maybe the spell checker plugin could be disabled by default in GovCMS?

I would expect superscript to be a reasonably common requirement.

**Comment by rooby** [comment]
Actually I was still getting erratic behaviour with a number of formatting buttons (eg. bold, italic, sub, sup) after disabling the spell checker and it seems the problem was the govcms_editing feature.
I got rid of that and it is working nicely.

My guess is that even though I have overridden the original feature configuration to remove the spell checker, the govcms_editing_wysiwyg_editor_settings_alter() function is reenabling it.

**Comment by tobybellwood** [comment]
I've been testing CKEditor 4.8.0 over in #656 (after a tip off on other issues it may solve) and it doesn't happen in that version.
The WYSIWYG module itself may pose more headaches, but we'll see how that goes!

**Comment by tobybellwood** [comment]
Does this still occur now we have 4.9.2?

**Comment by rooby** [comment]
Seems to be fixed :)
Pretty sure I'm trying the same things that were not working before and it all works.
