### ISSUE TITLE
When you edit media in the WYSIWYG media browser the workflow breaks

### ISSUE THREAD

**Issue by rooby** [govCMS/GovCMS7#672]
Steps to reproduce:

1. Edit some content with WYSIWYG and the media module's set up.
2. Click the 'Add media' button in the WYSIWYG editor.
3. Upload a new file or select an existing file.
4. When you're on the form where you select the display mode for the file, there is a preview of your image to the left along with an 'Edit file' button. - Click that edit file button.
5. Save the edit file form.
6. The home page of your site will have now loaded in the media browser and you have to close the browser and restart the add media process.

There is a patch that can be applied to fix this at: https://www.drupal.org/project/media/issues/2955935

**Comment by thisisalistairsaccount** [comment]
Also ties to https://www.drupal.org/project/media/issues/2933390 (https://www.drupal.org/project/media/issues/2955935 was closed as dupslicate)

Was resolved previous as part of D7 Media in 2.14. GovCMS D7 currently runs 2.24
