### ISSUE TITLE
govCMS Password Policy should update password strength indicator

### ISSUE THREAD

**Issue by MadeByMike** [govCMS/GovCMS7#71]
The govCMS Password Policy module changes requirements for passwords as a result the password strength indicator gives inaccurate feedback to users.

I watched several users today attempt to set a password, on average without instructions it took them about 3 attempts each.

**Comment by pandaskii** [comment]
I think we need some text here in govCMS to clarify confusions

On another words - weak, fair, good or strong doesn't mean the password is satisfied the requirements

Behind scenes:
1. The password strength indicator is overridden by Password Policy. 
2. The purpose of the module - "Password Policy" is to require users to set a strong password, instead of just suggesting whether the password is "weak", "fair", "good", or "strong".

**Comment by MadeByMike** [comment]
Fair point about the separate interests between the password policy and strength indicator.

But this is a separation of code not purpose. From a users perspective a big green bar indicates the password is good. To say it is strong but still invalid giving mixed messages. 

Not sure a message is the right way to correct this. It feel more like setting up a detour around the problem.

**Comment by fiasco** [comment]
Some fair points here. While Drupal tries to be non-restrictive with password strength, for Aus Gov sites, there is not a variable strength for passwords but rather strong enough or not strong enough. It would be nice if Password Policy module could override the strength indicator to reflect that (or remove the indicator entirely).

This issue feels like its leading towards a feature enhancement to the password policy module so I'm wondering if this is really an issue for govCMS?

**Comment by aleayr** [comment]
I think it's an issue in terms of consistency. Would be good not to have the discrepency if possible. Could we remove the strength indicator, or should we do something to sync them up?

**Comment by fiasco** [comment]
This is a fix we would accept a PR for. We're not provisioning this to a scheduled milestone however due to the lack of engagement on this PR.

**Comment by mgdhs** [comment]
This is a bit of a pain to fix. I've got something close, just need some input from @Feng-Shui for a point I'm stuck at.

**Comment by deanvucic** [comment]
This will be considered for future milestones. For now, I'm closing this PR.

**Comment by deanvucic** [comment]
govCMS currently does this much - see attached. Is this not sufficient?
![screenshot](https://user-images.githubusercontent.com/27907858/33587984-aa717f96-d9c4-11e7-8759-86a83748e852.jpg)

**Comment by tobybellwood** [comment]
Closing - considering the current module provides real-time feedback on compliance.
