### ISSUE TITLE
Consider adding flood_control and flood_unblock modules in the distro.

### ISSUE THREAD

**Issue by klonos** [govCMS/GovCMS7#735]
We should consider adding https://www.drupal.org/project/flood_unblock and/or https://www.drupal.org/project/flood_control to the GovCMS distro. These can help in situations where GovCMS Helpdesk User Agents and/or site owners need to flush the tables from the admin UI as a troubleshooting step (without having to escalate to the Application Support Team or require drush access to run db queries). Also site admins could use it to temporarily increase the thresholds while a crawl/scan is being performed (broken links audit for example).

In Backdrop, we have added flood_control in core after tidying up the UI:

![screenshot from 2018-05-16 13-36-17](https://user-images.githubusercontent.com/1071483/40133550-21ebe7be-590e-11e8-94a9-5f3b66a523d4.png)

...and we are planning to add flood_unblock too in the next release: https://github.com/backdrop/backdrop-issues/issues/3111

I personally find these 2 additions a great admin UX+.

---

https://www.drupal.org/node/1023440

Related known core issues that often come up in GovCMS installations: 

- [User login flood lock doesn't clear when reset password as admin](https://www.drupal.org/project/drupal/issues/2881572)
- Nothing clears the "5 failed login attempts" security message when a user resets their own password:
  - [D8](https://www.drupal.org/project/drupal/issues/992540)
  - [D7](https://www.drupal.org/project/drupal/issues/2880910)

**Comment by thisisalistairsaccount** [comment]
Reviewing and closing this older issue. Flood control module 1.0 is available in D7 distribution https://www.drupal.org/project/flood_control
