### ISSUE TITLE
Update Drupal core to 7.61

### ISSUE THREAD

**Issue by mgdhs** [govCMS/GovCMS7#753]
Drupal 7.61 is available. It is _not_ a security release.

https://www.drupal.org/project/drupal/releases/7.61

> # Release notes
> Maintenance release of the Drupal 7 series. Includes bug fixes and small API/feature improvements only (no major, non-backwards-compatible new functionality).
> 
> No security fixes are included in this release.
> 
> No changes have been made to the .htaccess, web.config, robots.txt in this release, so upgrading custom versions of those files is not necessary.
> 
> There is one change to the `sites/default/default.settings.php` file in this release: 
>    The default form cache expiration of 6 hours is now configurable (API
addition: https://www.drupal.org/node/2857751).

**Comment by tobybellwood** [comment]
In https://github.com/govCMS/govCMS/pull/751 7.61 has been deployed to 7.x-3.x.  Once migrations are complete, we will reassess the ongoing support of the 7.x-2.x branch more thoroughly.  As this is not a security release, we will not be deploying it to SiteFactory, but  I can cut a GovCMS 2.x branch release next week for those on PaaS if you want?

**Comment by mgdhs** [comment]
Thanks for continuing to maintain 7.x-2.x
