### ISSUE TITLE
Robots.txt changes break travis tests

### ISSUE THREAD

**Issue by fiasco** [govCMS/GovCMS7#81]
Since we introduced the robots.txt module, this tests have begun failing because behat cannot obtain a robots.txt file from the install.
![Behat failure](https://cloud.githubusercontent.com/assets/108160/10741612/9d7ae840-7c8d-11e5-9c54-96fd794246b0.png)

It would be ideal to fix this so that we can accept pull requests knowing it is not impacting robots.txt.

**Comment by typhonius** [comment]
#79 should have fixed this :)

**Comment by fiasco** [comment]
I thought so too... perhaps travis had caching issues??

**Comment by stooit** [comment]
Resolved by #79
