### ISSUE TITLE
Requests to updates.drupal.org return 404 Page not found which currently breaks build and test

### ISSUE THREAD

**Issue by pandaskii** [govCMS/GovCMS7#84]
Downloading Drupal.org modules doesn't seem to work with Drush any more

There is an issue report in Drupal community queue now: https://www.drupal.org/node/2602264

**Comment by typhonius** [comment]
Thanks for this. We experienced issues locally and presumed it was network issues.

**Comment by typhonius** [comment]
Drush issue tracked https://github.com/drush-ops/drush/issues/1713

**Comment by pandaskii** [comment]
@typhonius a big day for me, hah cannot handle with both Drush and Drupal suddenly change something at same day.

A interim way is to add curl --compressed in Drush

**Comment by typhonius** [comment]
If nothing changes we can add that to DrushTask.php as a default option or to build.xml as a parameter passed through to Drush.

**Comment by pandaskii** [comment]
Sounds good and nothing to lose. This is really a big change that many services depending on drush make, download will fail

**Comment by typhonius** [comment]
This has been fixed on drupal.org by kicking an NFS mount :athletic_shoe: :computer:
