### ISSUE TITLE
PHP Notice in hierarchical_select module

### ISSUE THREAD

**Issue by sonnykt** [govCMS/GovCMS7#888]
```
Notice: A non well formed numeric value encountered in _hierarchical_select_hierarchy_generate() (line 1946 of /app/profiles/govcms/modules/contrib/hierarchical_select/hierarchical_select.module)
```

**Comment by govindmaloo** [comment]
@sonnykt : This issue already been fixed. 
https://www.drupal.org/project/hierarchical_select/issues/2845621
Need to update GovCMS with latest version.
https://www.drupal.org/project/hierarchical_select/releases/7.x-3.0-beta9

**Comment by govindmaloo** [comment]
PR for this issue
https://github.com/govCMS/govCMS/pull/893

**Comment by thisisalistairsaccount** [comment]
Closing issue. Module previously updated to beta9 to address this
