### ISSUE TITLE
Upgrade Funnelback Search Integration to 7.x-4.0-beta5

### ISSUE THREAD

**Issue by govindmaloo** [govCMS/GovCMS7#891]
Funnelback Search Integration 7.x-4.0-beta4 has a issue 
Funnelback class missing closing bracket (https://www.drupal.org/project/funnelback/issues/3045105) which has been fixed with the latest release 7.x-4.0-beta5

**Comment by thisisalistairsaccount** [comment]
Closing this issue, it's been open for a while, but beta5 had been merged in previously to the 7 distro
