### ISSUE TITLE
Logs flooded with warning messages "Invalid display settings encountered"

### ISSUE THREAD

**Issue by TobyWild** [govCMS/GovCMS7#900]
https://www.drupal.org/project/entity_embed/issues/3077225

There is a patch there, already reviewed and ready to be released.

**Comment by AntoineOsanz** [comment]
Thanks @TobyWild . The patch you've referenced is for D8, but this issue is in the D7 distro for GovCMS. 
Can you please clarify which distribution you are having the problem in?

**Comment by TobyWild** [comment]
Ah, my bad.
