### ISSUE TITLE
How does Solr search work in govCMS platforms? 

### ISSUE THREAD

**Issue by ElviaMaschke** [govCMS/GovCMS7#951]
I need guidance on how Solr is running a search in a private Beta site. 

I don't have access to the configuration area so I can't check how it has been set up. 
I need to know how it indexes searches, how the system deals with misspellings. Is it configured for US spellings?

**Comment by fubarhouse** [comment]
@ElviaMaschke,

There's a few things to note:
* It is running using Docker-Compose, so there's no difference between a private beta, a public beta, a public site or a local environment, what matters here is how the containers are networked and this is handled by default with `docker-compose`.
* Images are based off the images released by amazeeio
  https://github.com/amazeeio/lagoon/tree/master/images/solr
* GovCMS7 uses Solr 6.6, but inherits the defaults from `search_api_solr`
  * https://github.com/govCMS/govCMS/blob/7.x-3.x/.docker/Dockerfile.solr#L5
* You can find the values by looking inside the container of the running project - but I would recommend looking at the image `govcmslagoon/solr:latest` for that.
* As a SaaS customer, there is no control given to Solr config - I myself am not even sure of the specifics so you'd have to ask the service desk for more information. PaaS customers can optionally provide their own configuration files via the Docker files in their project.
* You can use drush to access a local site as the administrator if there isn't enough information here.
* D8 now uses Solr 7.5, but the configuration still comes directly from the `search_api_solr` image.
* I don't actually know the specifics to the default configuration, so I don't know how the default language is configured.

I hope there's enough here for you to find what you're after - but let me know if I missed something.

**Comment by simesy** [comment]
>  there is no control given to Solr config

Yeah the solr xml config is out of bounds, but there is still a lot of Drupal accessible config like what fields to index.

**Comment by fubarhouse** [comment]
Indeed... but I'm not familiar with their processes and they are the official channel for this.

Like, I said:
> you'd have to ask the service desk for more information

**Comment by simesy** [comment]
True, but I'm just talking about the publicly accessible open sourced config defaults for SaaS

FWIW, I'm fairly certain the [solr xml used](https://github.com/govCMS/govcms8lagoon/blob/develop/.docker/Dockerfile.solr#L5) is https://git.drupalcode.org/project/search_api_solr/-/tree/8.x-2.x/solr-conf/7.x

And there are not a lot of forced/overridden Drupal settings for solr, so most should be configurable in the UI if you have permissions. https://github.com/govcms/govcms8lagoon/blob/develop/.docker/images/govcms8/settings/settings.php#L150-L154
